//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Tokens version 0.6.0
// Generated by Tokenator

package com.orange.ouds.theme.orange.tokens.semantic

import androidx.compose.ui.graphics.Color
import com.orange.ouds.theme.orange.tokens.raw.OrangeBrandColorRawTokens
import com.orange.ouds.theme.tokens.semantic.OudsColorContentSemanticTokens
import com.orange.ouds.tokens.global.raw.ColorRawTokens

data class OrangeColorContentSemanticTokens(
    override val contentBrandPrimaryDark: Color = OrangeBrandColorRawTokens.colorOrange500,
    override val contentBrandPrimaryLight: Color = OrangeBrandColorRawTokens.colorOrange550,
    override val contentDefault2Dark: Color = ColorRawTokens.colorContentDefault,
    override val contentDefault2Light: Color = ColorRawTokens.colorContentDefault,
    override val contentDefaultDark: Color = ColorRawTokens.colorFunctionalLightGray160,
    override val contentDefaultLight: Color = ColorRawTokens.colorFunctionalBlack,
    override val contentDisabledDark: Color = ColorRawTokens.colorOpacityWhite200,
    override val contentDisabledLight: Color = ColorRawTokens.colorOpacityBlack200,
    override val contentMutedDark: Color = ColorRawTokens.colorOpacityWhite640,
    override val contentMutedLight: Color = ColorRawTokens.colorOpacityBlack680,
    override val contentOnActionDisabledDark: Color = ColorRawTokens.colorFunctionalBlack,
    override val contentOnActionDisabledLight: Color = ColorRawTokens.colorFunctionalWhite,
    override val contentOnActionEnabledDark: Color = ColorRawTokens.colorFunctionalBlack,
    override val contentOnActionEnabledLight: Color = ColorRawTokens.colorFunctionalWhite,
    override val contentOnActionFocusDark: Color = ColorRawTokens.colorFunctionalBlack,
    override val contentOnActionFocusLight: Color = ColorRawTokens.colorFunctionalWhite,
    override val contentOnActionHighlightedDark: Color = ColorRawTokens.colorFunctionalBlack,
    override val contentOnActionHighlightedLight: Color = ColorRawTokens.colorFunctionalWhite,
    override val contentOnActionHoverDark: Color = ColorRawTokens.colorFunctionalBlack,
    override val contentOnActionHoverLight: Color = ColorRawTokens.colorFunctionalWhite,
    override val contentOnActionLoadingDark: Color = ColorRawTokens.colorFunctionalBlack,
    override val contentOnActionLoadingLight: Color = ColorRawTokens.colorFunctionalWhite,
    override val contentOnActionPressedDark: Color = ColorRawTokens.colorFunctionalBlack,
    override val contentOnActionPressedLight: Color = ColorRawTokens.colorFunctionalWhite,
    override val contentOnBrandPrimaryDark: Color = ColorRawTokens.colorFunctionalBlack,
    override val contentOnBrandPrimaryLight: Color = ColorRawTokens.colorFunctionalBlack,
    override val contentOnOverlayEmphasizedDark: Color = ColorRawTokens.colorFunctionalBlack,
    override val contentOnOverlayEmphasizedLight: Color = ColorRawTokens.colorFunctionalWhite,
    override val contentOnStatusEmphasizedAltDark: Color = ColorRawTokens.colorFunctionalBlack,
    override val contentOnStatusEmphasizedAltLight: Color = ColorRawTokens.colorFunctionalWhite,
    override val contentOnStatusEmphasizedDark: Color = ColorRawTokens.colorFunctionalBlack,
    override val contentOnStatusEmphasizedLight: Color = ColorRawTokens.colorFunctionalBlack,
    override val contentOnStatusMutedDark: Color = ColorRawTokens.colorFunctionalLightGray160,
    override val contentOnStatusMutedLight: Color = ColorRawTokens.colorFunctionalBlack,
    override val contentStatusInfoDark: Color = ColorRawTokens.colorFunctionalDodgerBlue500,
    override val contentStatusInfoLight: Color = ColorRawTokens.colorFunctionalDodgerBlue500,
    override val contentStatusNegativeDark: Color = ColorRawTokens.colorFunctionalScarlet600,
    override val contentStatusNegativeLight: Color = ColorRawTokens.colorFunctionalScarlet600,
    override val contentStatusPositiveDark: Color = ColorRawTokens.colorFunctionalMalachite500,
    override val contentStatusPositiveLight: Color = ColorRawTokens.colorFunctionalMalachite500,
    override val contentStatusWarningDark: Color = ColorRawTokens.colorFunctionalSun500,
    override val contentStatusWarningLight: Color = ColorRawTokens.colorFunctionalSun500
) : OudsColorContentSemanticTokens
