//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Tokens version 1.1.0
// Generated by Tokenator

package com.orange.ouds.theme.orange.tokens.semantic

import androidx.compose.ui.graphics.Color
import com.orange.ouds.theme.orange.tokens.raw.OrangeColorRawTokens
import com.orange.ouds.theme.tokens.semantic.OudsColorBgSemanticTokens
import com.orange.ouds.tokens.global.raw.ColorRawTokens

data class OrangeColorBgSemanticTokens(
    override val bgPrimaryLight: Color = ColorRawTokens.colorFunctionalWhite,
    override val bgPrimaryDark: Color = ColorRawTokens.colorFunctionalGrayDark880,
    override val bgSecondaryLight: Color = ColorRawTokens.colorFunctionalGrayLight80,
    override val bgSecondaryDark: Color = ColorRawTokens.colorFunctionalGrayDark800,
    override val bgTertiaryLight: Color = OrangeColorRawTokens.colorWarmGray100,
    override val bgTertiaryDark: Color = OrangeColorRawTokens.colorWarmGray1000,
    override val bgEmphasizedLight: Color = ColorRawTokens.colorFunctionalGrayDark880,
    override val bgEmphasizedDark: Color = ColorRawTokens.colorFunctionalGrayDark640
) : OudsColorBgSemanticTokens
