//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Orange brand tokens version 2.4.0
// Generated by Tokenator

package com.orange.ouds.theme.orange.tokens.semantic

import com.orange.ouds.theme.tokens.semantic.OudsBorderSemanticTokens
import com.orange.ouds.tokens.raw.OudsBorderRawTokens

internal data class OrangeBorderSemanticTokens(
    override val radiusDefault: Float = OudsBorderRawTokens.BorderRadius0,
    override val radiusLarge: Float = OudsBorderRawTokens.BorderRadius300,
    override val radiusMedium: Float = OudsBorderRawTokens.BorderRadius200,
    override val radiusNone: Float = OudsBorderRawTokens.BorderRadius0,
    override val radiusPill: Float = OudsBorderRawTokens.BorderRadius9999,
    override val radiusSmall: Float = OudsBorderRawTokens.BorderRadius100,
    override val styleDefault: String = OudsBorderRawTokens.BorderStyleSolid,
    override val styleDrag: String = OudsBorderRawTokens.BorderStyleDashed,
    override val widthDefault: Float = OudsBorderRawTokens.BorderWidth25,
    override val widthFocus: Float = OudsBorderRawTokens.BorderWidth125,
    override val widthFocusInset: Float = OudsBorderRawTokens.BorderWidth50,
    override val widthMedium: Float = OudsBorderRawTokens.BorderWidth50,
    override val widthNone: Float = OudsBorderRawTokens.BorderWidth0,
    override val widthThick: Float = OudsBorderRawTokens.BorderWidth75,
    override val widthThicker: Float = OudsBorderRawTokens.BorderWidth100,
    override val widthThin: Float = OudsBorderRawTokens.BorderWidth25
) : OudsBorderSemanticTokens
