//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Orange brand tokens version 2.2.0
// Generated by Tokenator

package com.orange.ouds.theme.orange.tokens.semantic

import com.orange.ouds.theme.tokens.semantic.OudsSizeSemanticTokens
import com.orange.ouds.tokens.raw.OudsDimensionRawTokens

data class OrangeSizeSemanticTokens(
    override val iconDecorative2xlarge: Float = OudsDimensionRawTokens.dimension900,
    override val iconDecorative2xsmall: Float = OudsDimensionRawTokens.dimension200,
    override val iconDecorative3xsmall: Float = OudsDimensionRawTokens.dimension150,
    override val iconDecorative4xsmall: Float = OudsDimensionRawTokens.dimensionOutOfSystem250,
    override val iconDecorativeLarge: Float = OudsDimensionRawTokens.dimension600,
    override val iconDecorativeMedium: Float = OudsDimensionRawTokens.dimension500,
    override val iconDecorativeSmall: Float = OudsDimensionRawTokens.dimension400,
    override val iconDecorativeXlarge: Float = OudsDimensionRawTokens.dimension700,
    override val iconDecorativeXsmall: Float = OudsDimensionRawTokens.dimension300,
    override val iconWithBodyLargeSizeLargeMobile: Float = OudsDimensionRawTokens.dimension350,
    override val iconWithBodyLargeSizeLargeTablet: Float = OudsDimensionRawTokens.dimension350,
    override val iconWithBodyLargeSizeMediumMobile: Float = OudsDimensionRawTokens.dimension300,
    override val iconWithBodyLargeSizeMediumTablet: Float = OudsDimensionRawTokens.dimension300,
    override val iconWithBodyLargeSizeSmallMobile: Float = OudsDimensionRawTokens.dimension250,
    override val iconWithBodyLargeSizeSmallTablet: Float = OudsDimensionRawTokens.dimension250,
    override val iconWithBodyMediumSizeLargeMobile: Float = OudsDimensionRawTokens.dimension300,
    override val iconWithBodyMediumSizeLargeTablet: Float = OudsDimensionRawTokens.dimension300,
    override val iconWithBodyMediumSizeMediumMobile: Float = OudsDimensionRawTokens.dimension250,
    override val iconWithBodyMediumSizeMediumTablet: Float = OudsDimensionRawTokens.dimension250,
    override val iconWithBodyMediumSizeSmallMobile: Float = OudsDimensionRawTokens.dimension200,
    override val iconWithBodyMediumSizeSmallTablet: Float = OudsDimensionRawTokens.dimension200,
    override val iconWithBodySmallSizeLargeMobile: Float = OudsDimensionRawTokens.dimension250,
    override val iconWithBodySmallSizeLargeTablet: Float = OudsDimensionRawTokens.dimension250,
    override val iconWithBodySmallSizeMediumMobile: Float = OudsDimensionRawTokens.dimension200,
    override val iconWithBodySmallSizeMediumTablet: Float = OudsDimensionRawTokens.dimension200,
    override val iconWithBodySmallSizeSmallMobile: Float = OudsDimensionRawTokens.dimension150,
    override val iconWithBodySmallSizeSmallTablet: Float = OudsDimensionRawTokens.dimension150,
    override val iconWithHeadingLargeSizeLargeMobile: Float = OudsDimensionRawTokens.dimension500,
    override val iconWithHeadingLargeSizeLargeTablet: Float = OudsDimensionRawTokens.dimension550,
    override val iconWithHeadingLargeSizeMediumMobile: Float = OudsDimensionRawTokens.dimension450,
    override val iconWithHeadingLargeSizeMediumTablet: Float = OudsDimensionRawTokens.dimension500,
    override val iconWithHeadingLargeSizeSmallMobile: Float = OudsDimensionRawTokens.dimension400,
    override val iconWithHeadingLargeSizeSmallTablet: Float = OudsDimensionRawTokens.dimension450,
    override val iconWithHeadingMediumSizeLargeMobile: Float = OudsDimensionRawTokens.dimension400,
    override val iconWithHeadingMediumSizeLargeTablet: Float = OudsDimensionRawTokens.dimension500,
    override val iconWithHeadingMediumSizeMediumMobile: Float = OudsDimensionRawTokens.dimension350,
    override val iconWithHeadingMediumSizeMediumTablet: Float = OudsDimensionRawTokens.dimension450,
    override val iconWithHeadingMediumSizeSmallMobile: Float = OudsDimensionRawTokens.dimension300,
    override val iconWithHeadingMediumSizeSmallTablet: Float = OudsDimensionRawTokens.dimension400,
    override val iconWithHeadingSmallSizeLargeMobile: Float = OudsDimensionRawTokens.dimension400,
    override val iconWithHeadingSmallSizeLargeTablet: Float = OudsDimensionRawTokens.dimension400,
    override val iconWithHeadingSmallSizeMediumMobile: Float = OudsDimensionRawTokens.dimension350,
    override val iconWithHeadingSmallSizeMediumTablet: Float = OudsDimensionRawTokens.dimension350,
    override val iconWithHeadingSmallSizeSmallMobile: Float = OudsDimensionRawTokens.dimension300,
    override val iconWithHeadingSmallSizeSmallTablet: Float = OudsDimensionRawTokens.dimension300,
    override val iconWithHeadingXlargeSizeLargeMobile: Float = OudsDimensionRawTokens.dimension550,
    override val iconWithHeadingXlargeSizeLargeTablet: Float = OudsDimensionRawTokens.dimension650,
    override val iconWithHeadingXlargeSizeMediumMobile: Float = OudsDimensionRawTokens.dimension500,
    override val iconWithHeadingXlargeSizeMediumTablet: Float = OudsDimensionRawTokens.dimension600,
    override val iconWithHeadingXlargeSizeSmallMobile: Float = OudsDimensionRawTokens.dimension450,
    override val iconWithHeadingXlargeSizeSmallTablet: Float = OudsDimensionRawTokens.dimension550,
    override val iconWithLabelLargeSizeLarge: Float = OudsDimensionRawTokens.dimension400,
    override val iconWithLabelLargeSizeMedium: Float = OudsDimensionRawTokens.dimension350,
    override val iconWithLabelLargeSizeSmall: Float = OudsDimensionRawTokens.dimension300,
    override val iconWithLabelLargeSizeXlarge: Float = OudsDimensionRawTokens.dimension550,
    override val iconWithLabelLargeSizeXsmall: Float = OudsDimensionRawTokens.dimension250,
    override val iconWithLabelMediumSizeLarge: Float = OudsDimensionRawTokens.dimension300,
    override val iconWithLabelMediumSizeMedium: Float = OudsDimensionRawTokens.dimension250,
    override val iconWithLabelMediumSizeSmall: Float = OudsDimensionRawTokens.dimension200,
    override val iconWithLabelMediumSizeXsmall: Float = OudsDimensionRawTokens.dimension150,
    override val iconWithLabelSmallSizeLarge: Float = OudsDimensionRawTokens.dimension250,
    override val iconWithLabelSmallSizeMedium: Float = OudsDimensionRawTokens.dimension200,
    override val iconWithLabelSmallSizeSmall: Float = OudsDimensionRawTokens.dimension150,
    override val iconWithLabelSmallSizeXsmall: Float = OudsDimensionRawTokens.dimensionOutOfSystem250,
    override val iconWithLabelXlargeSizeLarge: Float = OudsDimensionRawTokens.dimension550,
    override val iconWithLabelXlargeSizeMedium: Float = OudsDimensionRawTokens.dimension500,
    override val iconWithLabelXlargeSizeSmall: Float = OudsDimensionRawTokens.dimension400,
    override val maxWidthTypeBodyLargeMobile: Float = OudsDimensionRawTokens.dimension6000,
    override val maxWidthTypeBodyLargeTablet: Float = OudsDimensionRawTokens.dimension6000,
    override val maxWidthTypeBodyMediumMobile: Float = OudsDimensionRawTokens.dimension6000,
    override val maxWidthTypeBodyMediumTablet: Float = OudsDimensionRawTokens.dimension6000,
    override val maxWidthTypeBodySmallMobile: Float = OudsDimensionRawTokens.dimension6000,
    override val maxWidthTypeBodySmallTablet: Float = OudsDimensionRawTokens.dimension6000,
    override val maxWidthTypeDisplayLargeMobile: Float = OudsDimensionRawTokens.dimension9000,
    override val maxWidthTypeDisplayLargeTablet: Float = OudsDimensionRawTokens.dimension9000,
    override val maxWidthTypeDisplayMediumMobile: Float = OudsDimensionRawTokens.dimension9000,
    override val maxWidthTypeDisplayMediumTablet: Float = OudsDimensionRawTokens.dimension9000,
    override val maxWidthTypeDisplaySmallMobile: Float = OudsDimensionRawTokens.dimension9000,
    override val maxWidthTypeDisplaySmallTablet: Float = OudsDimensionRawTokens.dimension9000,
    override val maxWidthTypeHeadingLargeMobile: Float = OudsDimensionRawTokens.dimension7000,
    override val maxWidthTypeHeadingLargeTablet: Float = OudsDimensionRawTokens.dimension9000,
    override val maxWidthTypeHeadingMediumMobile: Float = OudsDimensionRawTokens.dimension7000,
    override val maxWidthTypeHeadingMediumTablet: Float = OudsDimensionRawTokens.dimension7000,
    override val maxWidthTypeHeadingSmallMobile: Float = OudsDimensionRawTokens.dimension6000,
    override val maxWidthTypeHeadingSmallTablet: Float = OudsDimensionRawTokens.dimension7000,
    override val maxWidthTypeHeadingXlargeMobile: Float = OudsDimensionRawTokens.dimension7000,
    override val maxWidthTypeHeadingXlargeTablet: Float = OudsDimensionRawTokens.dimension9000,
    override val minInteractiveArea: Float = OudsDimensionRawTokens.dimension600
) : OudsSizeSemanticTokens
