//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Orange brand tokens version 2.3.0
// Generated by Tokenator

package com.orange.ouds.theme.orange.tokens.semantic

import androidx.compose.ui.graphics.Color
import com.orange.ouds.theme.orange.tokens.raw.OrangeColorRawTokens
import com.orange.ouds.theme.tokens.semantic.OudsColorSurfaceSemanticTokens
import com.orange.ouds.tokens.raw.OudsColorRawTokens

data class OrangeColorSurfaceSemanticTokens(
    override val surfaceBrandPrimaryDark: Color = OrangeColorRawTokens.ColorOrange500,
    override val surfaceBrandPrimaryLight: Color = OrangeColorRawTokens.ColorOrange500,
    override val surfaceBrandSecondaryDark: Color = Color.Unspecified,
    override val surfaceBrandSecondaryLight: Color = Color.Unspecified,
    override val surfaceBrandTertiaryDark: Color = Color.Unspecified,
    override val surfaceBrandTertiaryLight: Color = Color.Unspecified,
    override val surfaceInverseHighDark: Color = OudsColorRawTokens.ColorFunctionalGrayLight160,
    override val surfaceInverseHighLight: Color = OudsColorRawTokens.ColorFunctionalGrayDark720,
    override val surfaceInverseLowDark: Color = OudsColorRawTokens.ColorOpacityWhite120,
    override val surfaceInverseLowLight: Color = OudsColorRawTokens.ColorFunctionalGrayDark720,
    override val surfacePrimaryDark: Color = OudsColorRawTokens.ColorOpacityWhite40,
    override val surfacePrimaryLight: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val surfaceSecondaryDark: Color = OudsColorRawTokens.ColorOpacityWhite80,
    override val surfaceSecondaryLight: Color = OudsColorRawTokens.ColorOpacityBlack40,
    override val surfaceStatusAccentEmphasizedDark: Color = OrangeColorRawTokens.ColorOrange500,
    override val surfaceStatusAccentEmphasizedLight: Color = OrangeColorRawTokens.ColorOrange500,
    override val surfaceStatusAccentMutedDark: Color = OrangeColorRawTokens.ColorOpacityWarmGray400,
    override val surfaceStatusAccentMutedLight: Color = OrangeColorRawTokens.ColorOpacityWarmGray80,
    override val surfaceStatusInfoEmphasizedDark: Color = OudsColorRawTokens.ColorFunctionalDodgerBlue300,
    override val surfaceStatusInfoEmphasizedLight: Color = OudsColorRawTokens.ColorFunctionalDodgerBlue700,
    override val surfaceStatusInfoMutedDark: Color = OudsColorRawTokens.ColorOpacityDodgerBlue520,
    override val surfaceStatusInfoMutedLight: Color = OudsColorRawTokens.ColorOpacityDodgerBlue80,
    override val surfaceStatusNegativeEmphasizedDark: Color = OudsColorRawTokens.ColorFunctionalScarlet300,
    override val surfaceStatusNegativeEmphasizedLight: Color = OudsColorRawTokens.ColorFunctionalScarlet600,
    override val surfaceStatusNegativeMutedDark: Color = OudsColorRawTokens.ColorOpacityScarlet320,
    override val surfaceStatusNegativeMutedLight: Color = OudsColorRawTokens.ColorOpacityScarlet80,
    override val surfaceStatusPositiveEmphasizedDark: Color = OudsColorRawTokens.ColorFunctionalMalachite300,
    override val surfaceStatusPositiveEmphasizedLight: Color = OudsColorRawTokens.ColorFunctionalMalachite750,
    override val surfaceStatusPositiveMutedDark: Color = OudsColorRawTokens.ColorOpacityMalachite640,
    override val surfaceStatusPositiveMutedLight: Color = OudsColorRawTokens.ColorOpacityMalachite120,
    override val surfaceStatusWarningEmphasizedDark: Color = OudsColorRawTokens.ColorFunctionalSun300,
    override val surfaceStatusWarningEmphasizedLight: Color = OudsColorRawTokens.ColorFunctionalSun500,
    override val surfaceStatusWarningMutedDark: Color = OudsColorRawTokens.ColorOpacitySun480,
    override val surfaceStatusWarningMutedLight: Color = OudsColorRawTokens.ColorOpacitySun160,
    override val surfaceTertiaryDark: Color = OrangeColorRawTokens.ColorOpacityWarmGray400,
    override val surfaceTertiaryLight: Color = OrangeColorRawTokens.ColorOpacityWarmGray80
) : OudsColorSurfaceSemanticTokens
