//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Orange brand tokens version 2.2.0
// Generated by Tokenator

package com.orange.ouds.theme.orange.tokens.semantic

import androidx.compose.ui.graphics.Color
import com.orange.ouds.theme.orange.tokens.raw.OrangeColorRawTokens
import com.orange.ouds.theme.tokens.semantic.OudsColorSurfaceSemanticTokens
import com.orange.ouds.tokens.raw.OudsColorRawTokens

data class OrangeColorSurfaceSemanticTokens(
    override val surfaceBrandPrimaryDark: Color = OrangeColorRawTokens.colorOrange500,
    override val surfaceBrandPrimaryLight: Color = OrangeColorRawTokens.colorOrange500,
    override val surfaceBrandSecondaryDark: Color = Color.Unspecified,
    override val surfaceBrandSecondaryLight: Color = Color.Unspecified,
    override val surfaceBrandTertiaryDark: Color = Color.Unspecified,
    override val surfaceBrandTertiaryLight: Color = Color.Unspecified,
    override val surfaceInverseHighDark: Color = OudsColorRawTokens.colorFunctionalGrayLight160,
    override val surfaceInverseHighLight: Color = OudsColorRawTokens.colorFunctionalGrayDark720,
    override val surfaceInverseLowDark: Color = OudsColorRawTokens.colorOpacityWhite120,
    override val surfaceInverseLowLight: Color = OudsColorRawTokens.colorFunctionalGrayDark720,
    override val surfacePrimaryDark: Color = OudsColorRawTokens.colorOpacityWhite40,
    override val surfacePrimaryLight: Color = OudsColorRawTokens.colorFunctionalWhite,
    override val surfaceSecondaryDark: Color = OudsColorRawTokens.colorOpacityWhite80,
    override val surfaceSecondaryLight: Color = OudsColorRawTokens.colorOpacityBlack40,
    override val surfaceStatusAccentEmphasizedDark: Color = OrangeColorRawTokens.colorOrange500,
    override val surfaceStatusAccentEmphasizedLight: Color = OrangeColorRawTokens.colorOrange500,
    override val surfaceStatusAccentMutedDark: Color = OrangeColorRawTokens.colorOpacityWarmGray400,
    override val surfaceStatusAccentMutedLight: Color = OrangeColorRawTokens.colorOpacityWarmGray80,
    override val surfaceStatusInfoEmphasizedDark: Color = OudsColorRawTokens.colorFunctionalDodgerBlue300,
    override val surfaceStatusInfoEmphasizedLight: Color = OudsColorRawTokens.colorFunctionalDodgerBlue700,
    override val surfaceStatusInfoMutedDark: Color = OudsColorRawTokens.colorOpacityDodgerBlue520,
    override val surfaceStatusInfoMutedLight: Color = OudsColorRawTokens.colorOpacityDodgerBlue80,
    override val surfaceStatusNegativeEmphasizedDark: Color = OudsColorRawTokens.colorFunctionalScarlet300,
    override val surfaceStatusNegativeEmphasizedLight: Color = OudsColorRawTokens.colorFunctionalScarlet600,
    override val surfaceStatusNegativeMutedDark: Color = OudsColorRawTokens.colorOpacityScarlet320,
    override val surfaceStatusNegativeMutedLight: Color = OudsColorRawTokens.colorOpacityScarlet80,
    override val surfaceStatusPositiveEmphasizedDark: Color = OudsColorRawTokens.colorFunctionalMalachite300,
    override val surfaceStatusPositiveEmphasizedLight: Color = OudsColorRawTokens.colorFunctionalMalachite750,
    override val surfaceStatusPositiveMutedDark: Color = OudsColorRawTokens.colorOpacityMalachite640,
    override val surfaceStatusPositiveMutedLight: Color = OudsColorRawTokens.colorOpacityMalachite120,
    override val surfaceStatusWarningEmphasizedDark: Color = OudsColorRawTokens.colorFunctionalSun300,
    override val surfaceStatusWarningEmphasizedLight: Color = OudsColorRawTokens.colorFunctionalSun500,
    override val surfaceStatusWarningMutedDark: Color = OudsColorRawTokens.colorOpacitySun480,
    override val surfaceStatusWarningMutedLight: Color = OudsColorRawTokens.colorOpacitySun160,
    override val surfaceTertiaryDark: Color = OrangeColorRawTokens.colorOpacityWarmGray400,
    override val surfaceTertiaryLight: Color = OrangeColorRawTokens.colorOpacityWarmGray80
) : OudsColorSurfaceSemanticTokens
