//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Tokens version 1.1.0
// Generated by Tokenator

package com.orange.ouds.theme.orange.tokens.semantic

import androidx.compose.ui.graphics.Color
import com.orange.ouds.theme.orange.tokens.raw.OrangeBrandColorRawTokens
import com.orange.ouds.theme.tokens.semantic.OudsColorBorderSemanticTokens
import com.orange.ouds.tokens.global.raw.ColorRawTokens

data class OrangeColorBorderSemanticTokens(
    override val borderDefaultLight: Color = ColorRawTokens.colorOpacityBlack200,
    override val borderDefaultDark: Color = ColorRawTokens.colorOpacityWhite200,
    override val borderMutedLight: Color = ColorRawTokens.colorOpacityBlack80,
    override val borderMutedDark: Color = ColorRawTokens.colorOpacityWhite80,
    override val borderEmphasizedLight: Color = ColorRawTokens.colorFunctionalBlack,
    override val borderEmphasizedDark: Color = ColorRawTokens.colorOpacityWhite920,
    override val borderFocusLight: Color = ColorRawTokens.colorFunctionalBlack,
    override val borderFocusDark: Color = ColorRawTokens.colorFunctionalGrayLight160,
    override val borderFocusInsetLight: Color = ColorRawTokens.colorFunctionalWhite,
    override val borderFocusInsetDark: Color = ColorRawTokens.colorFunctionalGrayDark880,
    override val borderBrandPrimaryLight: Color = OrangeBrandColorRawTokens.colorOrange550,
    override val borderBrandPrimaryDark: Color = OrangeBrandColorRawTokens.colorOrange500,
    override val borderOnBrandPrimaryLight: Color = ColorRawTokens.colorFunctionalBlack,
    override val borderOnBrandPrimaryDark: Color = ColorRawTokens.colorFunctionalBlack
) : OudsColorBorderSemanticTokens
