//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Tokens version 1.1.0
// Generated by Tokenator

package com.orange.ouds.theme.orange.tokens.semantic

import androidx.compose.ui.graphics.Color
import com.orange.ouds.theme.orange.tokens.raw.OrangeBrandColorRawTokens
import com.orange.ouds.theme.tokens.semantic.OudsColorDecorativeSemanticTokens
import com.orange.ouds.tokens.global.raw.ColorRawTokens

data class OrangeColorDecorativeSemanticTokens(
    override val decorativeBrandPrimary: Color = OrangeBrandColorRawTokens.colorOrange500,
    override val decorativeBrandSecondary: Color = ColorRawTokens.colorFunctionalBlack,
    override val decorativeBrandTertiary: Color = ColorRawTokens.colorFunctionalWhite,
    override val decorativeNeutralMutedLowest: Color = ColorRawTokens.colorFunctionalGrayLight80,
    override val decorativeNeutralMutedLower: Color = ColorRawTokens.colorFunctionalGrayLight160,
    override val decorativeNeutralMutedLow: Color = ColorRawTokens.colorFunctionalGrayLight240,
    override val decorativeNeutralMutedMedium: Color = ColorRawTokens.colorFunctionalGrayLight320,
    override val decorativeNeutralMutedHigh: Color = ColorRawTokens.colorFunctionalGrayLight400,
    override val decorativeNeutralMutedHigher: Color = ColorRawTokens.colorFunctionalGrayLight800,
    override val decorativeNeutralMutedHighest: Color = ColorRawTokens.colorFunctionalGrayLight960,
    override val decorativeNeutralEmphasizedLowest: Color = ColorRawTokens.colorFunctionalGrayDark240,
    override val decorativeNeutralEmphasizedLower: Color = ColorRawTokens.colorFunctionalGrayDark320,
    override val decorativeNeutralEmphasizedLow: Color = ColorRawTokens.colorFunctionalGrayDark400,
    override val decorativeNeutralEmphasizedHigher: Color = ColorRawTokens.colorFunctionalGrayDark640,
    override val decorativeAccent1Muted: Color = OrangeBrandColorRawTokens.colorDecorativeEmerald200,
    override val decorativeAccent1Default: Color = OrangeBrandColorRawTokens.colorDecorativeEmerald500,
    override val decorativeAccent1Emphasized: Color = OrangeBrandColorRawTokens.colorDecorativeEmerald700,
    override val decorativeAccent2Muted: Color = OrangeBrandColorRawTokens.colorDecorativeSky200,
    override val decorativeAccent2Default: Color = OrangeBrandColorRawTokens.colorDecorativeSky400,
    override val decorativeAccent2Emphasized: Color = OrangeBrandColorRawTokens.colorDecorativeSky700,
    override val decorativeAccent3Muted: Color = ColorRawTokens.colorFunctionalSun200,
    override val decorativeAccent3Default: Color = ColorRawTokens.colorFunctionalSun500,
    override val decorativeAccent3Emphasized: Color = OrangeBrandColorRawTokens.colorDecorativeAmber500,
    override val decorativeAccent4Muted: Color = OrangeBrandColorRawTokens.colorDecorativeAmethyst200,
    override val decorativeAccent4Default: Color = OrangeBrandColorRawTokens.colorDecorativeAmethyst400,
    override val decorativeAccent4Emphasized: Color = OrangeBrandColorRawTokens.colorDecorativeAmethyst800,
    override val decorativeAccent5Muted: Color = OrangeBrandColorRawTokens.colorDecorativeShockingPink100,
    override val decorativeAccent5Default: Color = OrangeBrandColorRawTokens.colorDecorativeShockingPink200,
    override val decorativeAccent5Emphasized: Color = OrangeBrandColorRawTokens.colorDecorativeShockingPink300,
    override val decorativeSkinTint100: Color = OrangeBrandColorRawTokens.colorDecorativeDeepPeach100,
    override val decorativeSkinTint200: Color = OrangeBrandColorRawTokens.colorDecorativeDeepPeach200,
    override val decorativeSkinTint300: Color = OrangeBrandColorRawTokens.colorDecorativeDeepPeach300,
    override val decorativeSkinTint400: Color = OrangeBrandColorRawTokens.colorDecorativeDeepPeach400,
    override val decorativeSkinTint500: Color = OrangeBrandColorRawTokens.colorDecorativeDeepPeach500,
    override val decorativeSkinTint600: Color = OrangeBrandColorRawTokens.colorDecorativeDeepPeach600,
    override val decorativeSkinTint700: Color = OrangeBrandColorRawTokens.colorDecorativeDeepPeach700,
    override val decorativeSkinTint800: Color = OrangeBrandColorRawTokens.colorDecorativeDeepPeach800,
    override val decorativeSkinTint900: Color = OrangeBrandColorRawTokens.colorDecorativeDeepPeach900
) : OudsColorDecorativeSemanticTokens
