//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Orange brand tokens version 2.2.0
// Generated by Tokenator

package com.orange.ouds.theme.orange.tokens.semantic

import com.orange.ouds.theme.tokens.semantic.OudsOpacitySemanticTokens
import com.orange.ouds.tokens.raw.OudsOpacityRawTokens

data class OrangeOpacitySemanticTokens(
    override val disabled: Float = OudsOpacityRawTokens.opacity200,
    override val invisible: Float = OudsOpacityRawTokens.opacity0,
    override val medium: Float = OudsOpacityRawTokens.opacity560,
    override val opaque: Float = OudsOpacityRawTokens.opacity1000,
    override val strong: Float = OudsOpacityRawTokens.opacity640,
    override val weak: Float = OudsOpacityRawTokens.opacity320,
    override val weaker: Float = OudsOpacityRawTokens.opacity160,
    override val weakest: Float = OudsOpacityRawTokens.opacity40
) : OudsOpacitySemanticTokens
