//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Orange brand tokens version 1.6.0
// Generated by Tokenator

package com.orange.ouds.theme.orange.tokens.semantic

import com.orange.ouds.theme.tokens.semantic.OudsSizeSemanticTokens
import com.orange.ouds.tokens.raw.DimensionRawTokens

data class OrangeSizeSemanticTokens(
    override val iconDecorative2xl: Float = DimensionRawTokens.dimension900,
    override val iconDecorative2xs: Float = DimensionRawTokens.dimension200,
    override val iconDecorative3xs: Float = DimensionRawTokens.dimension150,
    override val iconDecorative4xs: Float = DimensionRawTokens.dimensionOutOfSystem250,
    override val iconDecorativeLg: Float = DimensionRawTokens.dimension600,
    override val iconDecorativeMd: Float = DimensionRawTokens.medium,
    override val iconDecorativeSm: Float = DimensionRawTokens.dimension400,
    override val iconDecorativeXl: Float = DimensionRawTokens.dimension700,
    override val iconDecorativeXs: Float = DimensionRawTokens.dimension300,
    override val iconWithBodyLargeSizeLargeMobile: Float = DimensionRawTokens.dimension350,
    override val iconWithBodyLargeSizeLargeTablet: Float = DimensionRawTokens.dimension350,
    override val iconWithBodyLargeSizeMediumMobile: Float = DimensionRawTokens.dimension300,
    override val iconWithBodyLargeSizeMediumTablet: Float = DimensionRawTokens.dimension300,
    override val iconWithBodyLargeSizeSmallMobile: Float = DimensionRawTokens.dimension250,
    override val iconWithBodyLargeSizeSmallTablet: Float = DimensionRawTokens.dimension250,
    override val iconWithBodyMediumSizeLargeMobile: Float = DimensionRawTokens.dimension300,
    override val iconWithBodyMediumSizeLargeTablet: Float = DimensionRawTokens.dimension300,
    override val iconWithBodyMediumSizeMediumMobile: Float = DimensionRawTokens.dimension250,
    override val iconWithBodyMediumSizeMediumTablet: Float = DimensionRawTokens.dimension250,
    override val iconWithBodyMediumSizeSmallMobile: Float = DimensionRawTokens.dimension200,
    override val iconWithBodyMediumSizeSmallTablet: Float = DimensionRawTokens.dimension200,
    override val iconWithBodySmallSizeLargeMobile: Float = DimensionRawTokens.dimension250,
    override val iconWithBodySmallSizeLargeTablet: Float = DimensionRawTokens.dimension250,
    override val iconWithBodySmallSizeMediumMobile: Float = DimensionRawTokens.dimension200,
    override val iconWithBodySmallSizeMediumTablet: Float = DimensionRawTokens.dimension200,
    override val iconWithBodySmallSizeSmallMobile: Float = DimensionRawTokens.dimension150,
    override val iconWithBodySmallSizeSmallTablet: Float = DimensionRawTokens.dimension150,
    override val iconWithHeadingLargeSizeLargeMobile: Float = DimensionRawTokens.dimension500,
    override val iconWithHeadingLargeSizeLargeTablet: Float = DimensionRawTokens.dimension550,
    override val iconWithHeadingLargeSizeMediumMobile: Float = DimensionRawTokens.dimension450,
    override val iconWithHeadingLargeSizeMediumTablet: Float = DimensionRawTokens.dimension500,
    override val iconWithHeadingLargeSizeSmallMobile: Float = DimensionRawTokens.dimension400,
    override val iconWithHeadingLargeSizeSmallTablet: Float = DimensionRawTokens.dimension450,
    override val iconWithHeadingMediumSizeLargeMobile: Float = DimensionRawTokens.dimension400,
    override val iconWithHeadingMediumSizeLargeTablet: Float = DimensionRawTokens.dimension500,
    override val iconWithHeadingMediumSizeMediumMobile: Float = DimensionRawTokens.dimension350,
    override val iconWithHeadingMediumSizeMediumTablet: Float = DimensionRawTokens.dimension450,
    override val iconWithHeadingMediumSizeSmallMobile: Float = DimensionRawTokens.dimension300,
    override val iconWithHeadingMediumSizeSmallTablet: Float = DimensionRawTokens.dimension400,
    override val iconWithHeadingSmallSizeLargeMobile: Float = DimensionRawTokens.dimension400,
    override val iconWithHeadingSmallSizeLargeTablet: Float = DimensionRawTokens.dimension400,
    override val iconWithHeadingSmallSizeMediumMobile: Float = DimensionRawTokens.dimension350,
    override val iconWithHeadingSmallSizeMediumTablet: Float = DimensionRawTokens.dimension350,
    override val iconWithHeadingSmallSizeSmallMobile: Float = DimensionRawTokens.dimension300,
    override val iconWithHeadingSmallSizeSmallTablet: Float = DimensionRawTokens.dimension300,
    override val iconWithHeadingXlargeSizeLargeMobile: Float = DimensionRawTokens.dimension550,
    override val iconWithHeadingXlargeSizeLargeTablet: Float = DimensionRawTokens.dimension650,
    override val iconWithHeadingXlargeSizeMediumMobile: Float = DimensionRawTokens.dimension500,
    override val iconWithHeadingXlargeSizeMediumTablet: Float = DimensionRawTokens.dimension600,
    override val iconWithHeadingXlargeSizeSmallMobile: Float = DimensionRawTokens.dimension450,
    override val iconWithHeadingXlargeSizeSmallTablet: Float = DimensionRawTokens.dimension550,
    override val iconWithLabelLargeSizeLarge: Float = DimensionRawTokens.dimension400,
    override val iconWithLabelLargeSizeMedium: Float = DimensionRawTokens.dimension350,
    override val iconWithLabelLargeSizeSmall: Float = DimensionRawTokens.dimension300,
    override val iconWithLabelLargeSizeXlarge: Float = DimensionRawTokens.large,
    override val iconWithLabelLargeSizeXsmall: Float = DimensionRawTokens.dimension250,
    override val iconWithLabelMediumSizeLarge: Float = DimensionRawTokens.dimension300,
    override val iconWithLabelMediumSizeMedium: Float = DimensionRawTokens.dimension250,
    override val iconWithLabelMediumSizeSmall: Float = DimensionRawTokens.dimension200,
    override val iconWithLabelMediumSizeXsmall: Float = DimensionRawTokens.dimension150,
    override val iconWithLabelSmallSizeLarge: Float = DimensionRawTokens.dimension250,
    override val iconWithLabelSmallSizeMedium: Float = DimensionRawTokens.dimension200,
    override val iconWithLabelSmallSizeSmall: Float = DimensionRawTokens.dimension150,
    override val iconWithLabelSmallSizeXsmall: Float = DimensionRawTokens.dimensionOutOfSystem250,
    override val iconWithLabelXlargeSizeLarge: Float = DimensionRawTokens.large,
    override val iconWithLabelXlargeSizeMedium: Float = DimensionRawTokens.medium,
    override val iconWithLabelXlargeSizeSmall: Float = DimensionRawTokens.dimension400,
    override val maxWidthTypeBodyLargeMobile: Float = DimensionRawTokens.dimension6000,
    override val maxWidthTypeBodyLargeTablet: Float = DimensionRawTokens.dimension6000,
    override val maxWidthTypeBodyMediumMobile: Float = DimensionRawTokens.dimension6000,
    override val maxWidthTypeBodyMediumTablet: Float = DimensionRawTokens.dimension6000,
    override val maxWidthTypeBodySmallMobile: Float = DimensionRawTokens.dimension6000,
    override val maxWidthTypeBodySmallTablet: Float = DimensionRawTokens.dimension6000,
    override val maxWidthTypeDisplayLargeMobile: Float = DimensionRawTokens.dimension9000,
    override val maxWidthTypeDisplayLargeTablet: Float = DimensionRawTokens.dimension9000,
    override val maxWidthTypeDisplayMediumMobile: Float = DimensionRawTokens.dimension9000,
    override val maxWidthTypeDisplayMediumTablet: Float = DimensionRawTokens.dimension9000,
    override val maxWidthTypeDisplaySmallMobile: Float = DimensionRawTokens.dimension9000,
    override val maxWidthTypeDisplaySmallTablet: Float = DimensionRawTokens.dimension9000,
    override val maxWidthTypeHeadingLargeMobile: Float = DimensionRawTokens.dimension7000,
    override val maxWidthTypeHeadingLargeTablet: Float = DimensionRawTokens.dimension9000,
    override val maxWidthTypeHeadingMediumMobile: Float = DimensionRawTokens.dimension7000,
    override val maxWidthTypeHeadingMediumTablet: Float = DimensionRawTokens.dimension7000,
    override val maxWidthTypeHeadingSmallMobile: Float = DimensionRawTokens.dimension6000,
    override val maxWidthTypeHeadingSmallTablet: Float = DimensionRawTokens.dimension7000,
    override val maxWidthTypeHeadingXlargeMobile: Float = DimensionRawTokens.dimension7000,
    override val maxWidthTypeHeadingXlargeTablet: Float = DimensionRawTokens.dimension9000,
    override val minInteractiveArea: Float = DimensionRawTokens.dimension600
) : OudsSizeSemanticTokens
