//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Orange brand tokens version 2.2.0
// Generated by Tokenator

package com.orange.ouds.theme.orange.tokens.semantic

import androidx.compose.ui.graphics.Color
import com.orange.ouds.theme.orange.tokens.raw.OrangeColorRawTokens
import com.orange.ouds.theme.tokens.semantic.OudsColorBgSemanticTokens
import com.orange.ouds.tokens.raw.OudsColorRawTokens

data class OrangeColorBgSemanticTokens(
    override val bgInverseHighDark: Color = OudsColorRawTokens.ColorFunctionalGrayLight160,
    override val bgInverseHighLight: Color = OudsColorRawTokens.ColorFunctionalGrayDark880,
    override val bgInverseLowDark: Color = OudsColorRawTokens.ColorFunctionalGrayDark640,
    override val bgInverseLowLight: Color = OudsColorRawTokens.ColorFunctionalGrayDark880,
    override val bgPrimaryDark: Color = OudsColorRawTokens.ColorFunctionalGrayDark880,
    override val bgPrimaryLight: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val bgSecondaryDark: Color = OudsColorRawTokens.ColorFunctionalGrayDark800,
    override val bgSecondaryLight: Color = OudsColorRawTokens.ColorFunctionalGrayLight80,
    override val bgTertiaryDark: Color = OrangeColorRawTokens.ColorWarmGray900,
    override val bgTertiaryLight: Color = OrangeColorRawTokens.ColorWarmGray100
) : OudsColorBgSemanticTokens
