//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Android system tokens version 1.2.0
// Generated by Tokenator

package com.orange.ouds.theme.orangebusinesstools.tokens.material

import androidx.compose.ui.graphics.Color
import com.orange.ouds.theme.tokens.material.OudsMaterialColorTokens
import com.orange.ouds.tokens.raw.OudsColorRawTokens

internal data class OrangeBusinessToolsMaterialColorTokens(
    override val backgroundDark: Color = OudsColorRawTokens.ColorFunctionalGrayDark880,
    override val backgroundLight: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val errorContainerDark: Color = OudsColorRawTokens.ColorFunctionalScarlet900,
    override val errorContainerLight: Color = OudsColorRawTokens.ColorFunctionalScarlet100,
    override val errorDark: Color = OudsColorRawTokens.ColorFunctionalScarlet300,
    override val errorLight: Color = OudsColorRawTokens.ColorFunctionalScarlet600,
    override val inverseOnSurfaceDark: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val inverseOnSurfaceLight: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val inversePrimaryDark: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val inversePrimaryLight: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val inverseSurfaceDark: Color = OudsColorRawTokens.ColorFunctionalGrayLight160,
    override val inverseSurfaceLight: Color = OudsColorRawTokens.ColorFunctionalGrayDark720,
    override val onBackgroundDark: Color = OudsColorRawTokens.ColorFunctionalGrayLight160,
    override val onBackgroundLight: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val onErrorContainerDark: Color = OudsColorRawTokens.ColorFunctionalGrayLight160,
    override val onErrorContainerLight: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val onErrorDark: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val onErrorLight: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val onPrimaryContainerDark: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val onPrimaryContainerLight: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val onPrimaryDark: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val onPrimaryFixedDark: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val onPrimaryFixedLight: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val onPrimaryFixedVariantDark: Color = OudsColorRawTokens.ColorOpacityWhite640,
    override val onPrimaryFixedVariantLight: Color = OudsColorRawTokens.ColorOpacityWhite640,
    override val onPrimaryLight: Color = OudsColorRawTokens.ColorFunctionalGrayLight160,
    override val onSecondaryContainerDark: Color = OudsColorRawTokens.ColorFunctionalGrayLight160,
    override val onSecondaryContainerLight: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val onSecondaryDark: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val onSecondaryFixedDark: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val onSecondaryFixedLight: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val onSecondaryFixedVariantDark: Color = OudsColorRawTokens.ColorOpacityWhite640,
    override val onSecondaryFixedVariantLight: Color = OudsColorRawTokens.ColorOpacityWhite640,
    override val onSecondaryLight: Color = OudsColorRawTokens.ColorFunctionalGrayLight160,
    override val onSurfaceDark: Color = OudsColorRawTokens.ColorFunctionalGrayLight160,
    override val onSurfaceLight: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val onSurfaceVariantDark: Color = OudsColorRawTokens.ColorOpacityWhite640,
    override val onSurfaceVariantLight: Color = OudsColorRawTokens.ColorOpacityBlack680,
    override val onTertiaryContainerDark: Color = OudsColorRawTokens.ColorFunctionalGrayLight160,
    override val onTertiaryContainerLight: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val onTertiaryDark: Color = OudsColorRawTokens.ColorFunctionalGrayLight160,
    override val onTertiaryFixedDark: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val onTertiaryFixedLight: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val onTertiaryFixedVariantDark: Color = OudsColorRawTokens.ColorOpacityBlack680,
    override val onTertiaryFixedVariantLight: Color = OudsColorRawTokens.ColorOpacityBlack680,
    override val onTertiaryLight: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val outlineDark: Color = OudsColorRawTokens.ColorFunctionalGrayLight160,
    override val outlineLight: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val outlineVariantDark: Color = OudsColorRawTokens.ColorOpacityWhite200,
    override val outlineVariantLight: Color = OudsColorRawTokens.ColorOpacityBlack200,
    override val primaryContainerDark: Color = OudsColorRawTokens.ColorFunctionalGrayLight160,
    override val primaryContainerLight: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val primaryDark: Color = OudsColorRawTokens.ColorFunctionalGrayLight160,
    override val primaryFixedDark: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val primaryFixedDimDark: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val primaryFixedDimLight: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val primaryFixedLight: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val primaryLight: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val scrimDark: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val scrimLight: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val secondaryContainerDark: Color = OudsColorRawTokens.ColorOpacityWhite80,
    override val secondaryContainerLight: Color = OudsColorRawTokens.ColorOpacityBlack40,
    override val secondaryDark: Color = OudsColorRawTokens.ColorFunctionalGrayLight160,
    override val secondaryFixedDark: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val secondaryFixedDimDark: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val secondaryFixedDimLight: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val secondaryFixedLight: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val secondaryLight: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val surfaceBrightDark: Color = OudsColorRawTokens.ColorFunctionalGrayDark640,
    override val surfaceBrightLight: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val surfaceDark: Color = OudsColorRawTokens.ColorFunctionalGrayDark880,
    override val surfaceDimDark: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val surfaceDimLight: Color = OudsColorRawTokens.ColorFunctionalGrayLight80,
    override val surfaceLight: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val surfaceTintDark: Color = OudsColorRawTokens.ColorFunctionalGrayDark720,
    override val surfaceTintLight: Color = OudsColorRawTokens.ColorFunctionalGrayLight80,
    override val surfaceVariantDark: Color = OudsColorRawTokens.ColorFunctionalGrayDark720,
    override val surfaceVariantLight: Color = OudsColorRawTokens.ColorFunctionalGrayLight80,
    override val surfContainerDark: Color = OudsColorRawTokens.ColorFunctionalGrayDark720,
    override val surfContainerHighDark: Color = OudsColorRawTokens.ColorFunctionalGrayDark720,
    override val surfContainerHighestDark: Color = OudsColorRawTokens.ColorFunctionalGrayDark720,
    override val surfContainerHighestLight: Color = OudsColorRawTokens.ColorFunctionalGrayLight80,
    override val surfContainerHighLight: Color = OudsColorRawTokens.ColorFunctionalGrayLight80,
    override val surfContainerLight: Color = OudsColorRawTokens.ColorFunctionalGrayLight80,
    override val surfContainerLowDark: Color = OudsColorRawTokens.ColorFunctionalGrayDark720,
    override val surfContainerLowestDark: Color = OudsColorRawTokens.ColorFunctionalGrayDark720,
    override val surfContainerLowestLight: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val surfContainerLowLight: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val tertiaryContainerDark: Color = OudsColorRawTokens.ColorFunctionalGrayDark880,
    override val tertiaryContainerLight: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val tertiaryDark: Color = OudsColorRawTokens.ColorFunctionalGrayDark880,
    override val tertiaryFixedDark: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val tertiaryFixedDimDark: Color = OudsColorRawTokens.ColorFunctionalGrayLight80,
    override val tertiaryFixedDimLight: Color = OudsColorRawTokens.ColorFunctionalGrayLight80,
    override val tertiaryFixedLight: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val tertiaryLight: Color = OudsColorRawTokens.ColorFunctionalWhite
) : OudsMaterialColorTokens
