//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Orange brand tokens version 2.7.0
// Generated by Tokenator

package com.orange.ouds.theme.tokens

import com.orange.ouds.foundation.InternalOudsApi

/**
 * @suppress
 */
@InternalOudsApi
sealed interface OudsColorKeyToken : OudsKeyToken {
    @InternalOudsApi
    sealed interface Action : OudsColorKeyToken {
        @InternalOudsApi
        data object Disabled : Action

        @InternalOudsApi
        data object Enabled : Action

        @InternalOudsApi
        data object Focus : Action

        @InternalOudsApi
        data object Highlighted : Action

        @InternalOudsApi
        data object Hover : Action

        @InternalOudsApi
        data object Loading : Action

        @InternalOudsApi
        sealed interface Negative : Action {
            @InternalOudsApi
            data object Enabled : Negative

            @InternalOudsApi
            data object Focus : Negative

            @InternalOudsApi
            data object Hover : Negative

            @InternalOudsApi
            data object Loading : Negative

            @InternalOudsApi
            data object Pressed : Negative
        }

        @InternalOudsApi
        data object Pressed : Action

        @InternalOudsApi
        data object ReadOnlyPrimary : Action

        @InternalOudsApi
        data object ReadOnlySecondary : Action

        @InternalOudsApi
        data object Selected : Action

        @InternalOudsApi
        sealed interface Support : Action {
            @InternalOudsApi
            data object Disabled : Support

            @InternalOudsApi
            data object Enabled : Support

            @InternalOudsApi
            data object Focus : Support

            @InternalOudsApi
            data object Hover : Support

            @InternalOudsApi
            data object Loading : Support

            @InternalOudsApi
            data object Pressed : Support
        }

        @InternalOudsApi
        data object Visited : Action
    }

    @InternalOudsApi
    sealed interface Ai : OudsColorKeyToken {
        @InternalOudsApi
        data object Primary : Ai

        @InternalOudsApi
        data object Quaternary : Ai

        @InternalOudsApi
        data object Secondary : Ai

        @InternalOudsApi
        data object Tertiary : Ai
    }

    @InternalOudsApi
    sealed interface Always : OudsColorKeyToken {
        @InternalOudsApi
        data object Black : Always

        @InternalOudsApi
        data object OnBlack : Always

        @InternalOudsApi
        data object OnWhite : Always

        @InternalOudsApi
        data object White : Always
    }

    @InternalOudsApi
    sealed interface Background : OudsColorKeyToken {
        @InternalOudsApi
        data object InverseHigh : Background

        @InternalOudsApi
        data object InverseLow : Background

        @InternalOudsApi
        data object Primary : Background

        @InternalOudsApi
        data object Secondary : Background

        @InternalOudsApi
        data object Tertiary : Background
    }

    @InternalOudsApi
    sealed interface Border : OudsColorKeyToken {
        @InternalOudsApi
        data object BrandPrimary : Border

        @InternalOudsApi
        data object BrandSecondary : Border

        @InternalOudsApi
        data object BrandTertiary : Border

        @InternalOudsApi
        data object Default : Border

        @InternalOudsApi
        data object Emphasized : Border

        @InternalOudsApi
        data object Focus : Border

        @InternalOudsApi
        data object FocusInset : Border

        @InternalOudsApi
        data object Minimal : Border

        @InternalOudsApi
        data object Muted : Border

        @InternalOudsApi
        sealed interface OnBrand : Border {
            @InternalOudsApi
            data object Primary : OnBrand

            @InternalOudsApi
            data object Secondary : OnBrand

            @InternalOudsApi
            data object Tertiary : OnBrand
        }

        @InternalOudsApi
        sealed interface Status : Border {
            @InternalOudsApi
            data object Accent : Status

            @InternalOudsApi
            data object Info : Status

            @InternalOudsApi
            data object Negative : Status

            @InternalOudsApi
            data object Positive : Status

            @InternalOudsApi
            data object Warning : Status
        }
    }

    @InternalOudsApi
    sealed interface Content : OudsColorKeyToken {
        @InternalOudsApi
        data object BrandPrimary : Content

        @InternalOudsApi
        data object BrandSecondary : Content

        @InternalOudsApi
        data object BrandTertiary : Content

        @InternalOudsApi
        data object Default : Content

        @InternalOudsApi
        data object Disabled : Content

        @InternalOudsApi
        data object Inverse : Content

        @InternalOudsApi
        data object Muted : Content

        @InternalOudsApi
        sealed interface OnAction : Content {
            @InternalOudsApi
            data object Disabled : OnAction

            @InternalOudsApi
            data object Enabled : OnAction

            @InternalOudsApi
            data object Focus : OnAction

            @InternalOudsApi
            data object Highlighted : OnAction

            @InternalOudsApi
            data object Hover : OnAction

            @InternalOudsApi
            data object Loading : OnAction

            @InternalOudsApi
            data object Pressed : OnAction

            @InternalOudsApi
            data object Selected : OnAction
        }

        @InternalOudsApi
        sealed interface OnBrand : Content {
            @InternalOudsApi
            data object Primary : OnBrand

            @InternalOudsApi
            data object Secondary : OnBrand

            @InternalOudsApi
            data object Tertiary : OnBrand
        }

        @InternalOudsApi
        sealed interface OnStatus : Content {
            @InternalOudsApi
            sealed interface Accent : OnStatus {
                @InternalOudsApi
                data object Emphasized : Accent

                @InternalOudsApi
                data object Muted : Accent
            }

            @InternalOudsApi
            sealed interface Info : OnStatus {
                @InternalOudsApi
                data object Emphasized : Info

                @InternalOudsApi
                data object Muted : Info
            }

            @InternalOudsApi
            sealed interface Negative : OnStatus {
                @InternalOudsApi
                data object Emphasized : Negative

                @InternalOudsApi
                data object Muted : Negative
            }

            @InternalOudsApi
            sealed interface Positive : OnStatus {
                @InternalOudsApi
                data object Emphasized : Positive

                @InternalOudsApi
                data object Muted : Positive
            }

            @InternalOudsApi
            sealed interface Warning : OnStatus {
                @InternalOudsApi
                data object Emphasized : Warning

                @InternalOudsApi
                data object Muted : Warning
            }
        }

        @InternalOudsApi
        sealed interface Status : Content {
            @InternalOudsApi
            data object Accent : Status

            @InternalOudsApi
            data object Info : Status

            @InternalOudsApi
            sealed interface Inverse : Status {
                @InternalOudsApi
                data object Info : Inverse

                @InternalOudsApi
                data object Negative : Inverse

                @InternalOudsApi
                data object Positive : Inverse

                @InternalOudsApi
                data object Warning : Inverse
            }

            @InternalOudsApi
            data object Negative : Status

            @InternalOudsApi
            data object Positive : Status

            @InternalOudsApi
            data object Warning : Status
        }
    }

    @InternalOudsApi
    sealed interface Opacity : OudsColorKeyToken {
        @InternalOudsApi
        data object Lower : Opacity

        @InternalOudsApi
        data object Lowest : Opacity

        @InternalOudsApi
        data object Transparent : Opacity

        @InternalOudsApi
        data object TransparentInverse : Opacity
    }

    @InternalOudsApi
    sealed interface Overlay : OudsColorKeyToken {
        @InternalOudsApi
        data object Backdrop : Overlay

        @InternalOudsApi
        data object Drag : Overlay

        @InternalOudsApi
        data object Dropdown : Overlay

        @InternalOudsApi
        data object Floating : Overlay

        @InternalOudsApi
        data object ModalSheet : Overlay

        @InternalOudsApi
        data object Tooltip : Overlay
    }

    @InternalOudsApi
    sealed interface Repository : OudsColorKeyToken {
        @InternalOudsApi
        sealed interface Accent : Repository {
            @InternalOudsApi
            data object High : Accent

            @InternalOudsApi
            data object Higher : Accent

            @InternalOudsApi
            data object Highest : Accent

            @InternalOudsApi
            data object Low : Accent

            @InternalOudsApi
            data object Lower : Accent

            @InternalOudsApi
            data object Lowest : Accent

            @InternalOudsApi
            data object Medium : Accent
        }

        @InternalOudsApi
        sealed interface Info : Repository {
            @InternalOudsApi
            data object High : Info

            @InternalOudsApi
            data object Higher : Info

            @InternalOudsApi
            data object Highest : Info

            @InternalOudsApi
            data object Low : Info

            @InternalOudsApi
            data object Lower : Info

            @InternalOudsApi
            data object Lowest : Info

            @InternalOudsApi
            data object Medium : Info
        }

        @InternalOudsApi
        sealed interface Negative : Repository {
            @InternalOudsApi
            data object High : Negative

            @InternalOudsApi
            data object Higher : Negative

            @InternalOudsApi
            data object Highest : Negative

            @InternalOudsApi
            data object Low : Negative

            @InternalOudsApi
            data object Lower : Negative

            @InternalOudsApi
            data object Lowest : Negative

            @InternalOudsApi
            data object Medium : Negative
        }

        @InternalOudsApi
        sealed interface Neutral : Repository {
            @InternalOudsApi
            sealed interface Emphasized : Neutral {
                @InternalOudsApi
                data object Black : Emphasized

                @InternalOudsApi
                data object High : Emphasized

                @InternalOudsApi
                data object Higher : Emphasized

                @InternalOudsApi
                data object Highest : Emphasized

                @InternalOudsApi
                data object Low : Emphasized

                @InternalOudsApi
                data object Lower : Emphasized

                @InternalOudsApi
                data object Lowest : Emphasized

                @InternalOudsApi
                data object Medium : Emphasized
            }

            @InternalOudsApi
            sealed interface Muted : Neutral {
                @InternalOudsApi
                data object High : Muted

                @InternalOudsApi
                data object Higher : Muted

                @InternalOudsApi
                data object Highest : Muted

                @InternalOudsApi
                data object Low : Muted

                @InternalOudsApi
                data object Lower : Muted

                @InternalOudsApi
                data object Lowest : Muted

                @InternalOudsApi
                data object Medium : Muted

                @InternalOudsApi
                data object White : Muted
            }
        }

        @InternalOudsApi
        sealed interface Opacity : Repository {
            @InternalOudsApi
            sealed interface Accent : Opacity {
                @InternalOudsApi
                data object Low : Accent

                @InternalOudsApi
                data object Medium : Accent
            }

            @InternalOudsApi
            sealed interface Black : Opacity {
                @InternalOudsApi
                data object High : Black

                @InternalOudsApi
                data object Higher : Black

                @InternalOudsApi
                data object Highest : Black

                @InternalOudsApi
                data object Low : Black

                @InternalOudsApi
                data object Lower : Black

                @InternalOudsApi
                data object Lowest : Black

                @InternalOudsApi
                data object Medium : Black

                @InternalOudsApi
                data object MediumHigh : Black

                @InternalOudsApi
                data object MediumLow : Black

                @InternalOudsApi
                data object Transparent : Black
            }

            @InternalOudsApi
            sealed interface Info : Opacity {
                @InternalOudsApi
                data object Low : Info

                @InternalOudsApi
                data object Medium : Info
            }

            @InternalOudsApi
            sealed interface Negative : Opacity {
                @InternalOudsApi
                data object Low : Negative

                @InternalOudsApi
                data object Medium : Negative
            }

            @InternalOudsApi
            sealed interface Positive : Opacity {
                @InternalOudsApi
                data object Low : Positive

                @InternalOudsApi
                data object Medium : Positive
            }

            @InternalOudsApi
            sealed interface Primary : Opacity {
                @InternalOudsApi
                data object High : Primary

                @InternalOudsApi
                data object Higher : Primary

                @InternalOudsApi
                data object Highest : Primary

                @InternalOudsApi
                data object Low : Primary

                @InternalOudsApi
                data object Lower : Primary

                @InternalOudsApi
                data object Lowest : Primary

                @InternalOudsApi
                data object Medium : Primary

                @InternalOudsApi
                data object Transparent : Primary
            }

            @InternalOudsApi
            sealed interface Warning : Opacity {
                @InternalOudsApi
                data object Low : Warning

                @InternalOudsApi
                data object Medium : Warning
            }

            @InternalOudsApi
            sealed interface White : Opacity {
                @InternalOudsApi
                data object High : White

                @InternalOudsApi
                data object Higher : White

                @InternalOudsApi
                data object Highest : White

                @InternalOudsApi
                data object Low : White

                @InternalOudsApi
                data object Lower : White

                @InternalOudsApi
                data object Lowest : White

                @InternalOudsApi
                data object Medium : White

                @InternalOudsApi
                data object MediumLow : White

                @InternalOudsApi
                data object Transparent : White
            }
        }

        @InternalOudsApi
        sealed interface Positive : Repository {
            @InternalOudsApi
            data object High : Positive

            @InternalOudsApi
            data object Higher : Positive

            @InternalOudsApi
            data object Highest : Positive

            @InternalOudsApi
            data object Low : Positive

            @InternalOudsApi
            data object Lower : Positive

            @InternalOudsApi
            data object Lowest : Positive

            @InternalOudsApi
            data object Medium : Positive
        }

        @InternalOudsApi
        sealed interface Primary : Repository {
            @InternalOudsApi
            data object High : Primary

            @InternalOudsApi
            data object Higher : Primary

            @InternalOudsApi
            data object Highest : Primary

            @InternalOudsApi
            data object Low : Primary

            @InternalOudsApi
            data object Lower : Primary

            @InternalOudsApi
            data object Lowest : Primary

            @InternalOudsApi
            data object Medium : Primary
        }

        @InternalOudsApi
        sealed interface Secondary : Repository {
            @InternalOudsApi
            data object High : Secondary

            @InternalOudsApi
            data object HigherHigh : Secondary

            @InternalOudsApi
            data object HigherLow : Secondary

            @InternalOudsApi
            data object Highest : Secondary

            @InternalOudsApi
            data object Low : Secondary

            @InternalOudsApi
            data object Lower : Secondary

            @InternalOudsApi
            data object Lowest : Secondary

            @InternalOudsApi
            data object Medium : Secondary
        }

        @InternalOudsApi
        sealed interface Tertiary : Repository {
            @InternalOudsApi
            data object High : Tertiary

            @InternalOudsApi
            data object Higher : Tertiary

            @InternalOudsApi
            data object Highest : Tertiary

            @InternalOudsApi
            data object Low : Tertiary

            @InternalOudsApi
            data object Lower : Tertiary

            @InternalOudsApi
            data object Lowest : Tertiary

            @InternalOudsApi
            data object Medium : Tertiary
        }

        @InternalOudsApi
        sealed interface Warning : Repository {
            @InternalOudsApi
            data object High : Warning

            @InternalOudsApi
            data object Higher : Warning

            @InternalOudsApi
            data object Highest : Warning

            @InternalOudsApi
            data object Low : Warning

            @InternalOudsApi
            data object Lower : Warning

            @InternalOudsApi
            data object Lowest : Warning

            @InternalOudsApi
            data object Medium : Warning
        }
    }

    @InternalOudsApi
    sealed interface Surface : OudsColorKeyToken {
        @InternalOudsApi
        sealed interface Brand : Surface {
            @InternalOudsApi
            data object Primary : Brand

            @InternalOudsApi
            data object Secondary : Brand

            @InternalOudsApi
            data object Tertiary : Brand
        }

        @InternalOudsApi
        data object InverseHigh : Surface

        @InternalOudsApi
        data object InverseLow : Surface

        @InternalOudsApi
        data object Primary : Surface

        @InternalOudsApi
        data object Secondary : Surface

        @InternalOudsApi
        sealed interface Status : Surface {
            @InternalOudsApi
            sealed interface Accent : Status {
                @InternalOudsApi
                data object Emphasized : Accent

                @InternalOudsApi
                data object Muted : Accent
            }

            @InternalOudsApi
            sealed interface Info : Status {
                @InternalOudsApi
                data object Emphasized : Info

                @InternalOudsApi
                data object Muted : Info
            }

            @InternalOudsApi
            sealed interface Negative : Status {
                @InternalOudsApi
                data object Emphasized : Negative

                @InternalOudsApi
                data object Muted : Negative
            }

            @InternalOudsApi
            sealed interface Positive : Status {
                @InternalOudsApi
                data object Emphasized : Positive

                @InternalOudsApi
                data object Muted : Positive
            }

            @InternalOudsApi
            sealed interface Warning : Status {
                @InternalOudsApi
                data object Emphasized : Warning

                @InternalOudsApi
                data object Muted : Warning
            }
        }

        @InternalOudsApi
        data object Tertiary : Surface
    }
}

