//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Android system tokens version 1.2.0
// Generated by Tokenator

package com.orange.ouds.theme.tokens

import com.orange.ouds.foundation.InternalOudsApi

/**
 * @suppress
 */
@InternalOudsApi
sealed interface OudsElevationKeyToken : OudsKeyToken {
    @InternalOudsApi
    data object Default : OudsElevationKeyToken

    @InternalOudsApi
    data object Drag : OudsElevationKeyToken

    @InternalOudsApi
    data object Emphasized : OudsElevationKeyToken

    @InternalOudsApi
    data object None : OudsElevationKeyToken

    @InternalOudsApi
    data object Raised : OudsElevationKeyToken

    @InternalOudsApi
    data object Sticky : OudsElevationKeyToken
}

