//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Tokens version 1.1.0
// Generated by Tokenator

package com.orange.ouds.theme.tokens

import com.orange.ouds.foundation.InternalOudsApi

@InternalOudsApi
sealed interface OudsColorKeyToken : OudsKeyToken {
    sealed interface Background : OudsColorKeyToken {
        data object Primary : Background
        data object Secondary : Background
        data object Tertiary : Background
        data object Emphasized : Background
    }
    sealed interface Surface : OudsColorKeyToken {
        sealed interface Brand : Surface {
            data object Primary : Brand
        }
        sealed interface Status : Surface {
            sealed interface Neutral : Status {
                data object Muted : Neutral
                data object Emphasized : Neutral
            }
            sealed interface Positive : Status {
                data object Muted : Positive
                data object Emphasized : Positive
            }
            sealed interface Info : Status {
                data object Muted : Info
                data object Emphasized : Info
            }
            sealed interface Warning : Status {
                data object Muted : Warning
                data object Emphasized : Warning
            }
            sealed interface Negative : Status {
                data object Muted : Negative
                data object Emphasized : Negative
            }
            sealed interface Accent : Status {
                data object Muted : Accent
                data object Emphasized : Accent
            }
        }
    }
    sealed interface Content : OudsColorKeyToken {
        data object Default : Content
        data object Muted : Content
        data object Disabled : Content
        data object BrandPrimary : Content
        sealed interface Status : Content {
            data object Positive : Status
            data object Info : Status
            data object Warning : Status
            data object Negative : Status
            data object Accent : Status
        }
        sealed interface OnBrand : Content {
            data object Primary : OnBrand
        }
        sealed interface OnStatus : Content {
            sealed interface Neutral : OnStatus {
                data object Muted : Neutral
                data object Emphasized : Neutral
            }
            sealed interface Positive : OnStatus {
                data object Muted : Positive
                data object Emphasized : Positive
            }
            sealed interface Info : OnStatus {
                data object Muted : Info
                data object Emphasized : Info
            }
            sealed interface Warning : OnStatus {
                data object Muted : Warning
                data object Emphasized : Warning
            }
            sealed interface Negative : OnStatus {
                data object Muted : Negative
                data object Emphasized : Negative
            }
            sealed interface Accent : OnStatus {
                data object Muted : Accent
                data object Emphasized : Accent
            }
        }
        sealed interface OnAction : Content {
            data object Enabled : OnAction
            data object Hover : OnAction
            data object Pressed : OnAction
            data object Loading : OnAction
            data object Disabled : OnAction
            data object Focus : OnAction
            data object Highlighted : OnAction
        }
        sealed interface OnOverlay : Content {
            data object Emphasized : OnOverlay
        }
    }
    sealed interface Border : OudsColorKeyToken {
        data object Default : Border
        data object Muted : Border
        data object Emphasized : Border
        data object Focus : Border
        data object FocusInset : Border
        data object BrandPrimary : Border
        sealed interface OnBrand : Border {
            data object Primary : OnBrand
        }
    }
    sealed interface Action : OudsColorKeyToken {
        data object Enabled : Action
        data object Hover : Action
        data object Pressed : Action
        data object Loading : Action
        data object Disabled : Action
        data object Focus : Action
        data object Selected : Action
        data object Visited : Action
        data object Highlighted : Action
        sealed interface Support : Action {
            data object Enabled : Support
            data object Hover : Support
            data object Pressed : Support
            data object Loading : Support
            data object Focus : Support
        }
        sealed interface Negative : Action {
            data object Enabled : Negative
            data object Hover : Negative
            data object Pressed : Negative
            data object Loading : Negative
            data object Focus : Negative
        }
    }
    sealed interface Overlay : OudsColorKeyToken {
        data object Default : Overlay
        data object Emphasized : Overlay
        data object Drag : Overlay
        data object Modal : Overlay
    }
    sealed interface Opacity : OudsColorKeyToken {
        data object Transparent : Opacity
        data object Lowest : Opacity
        data object Lower : Opacity
    }
    sealed interface Always : OudsColorKeyToken {
        data object Black : Always
        data object White : Always
        data object OnBlack : Always
        data object OnWhite : Always
    }
    sealed interface Decorative : OudsColorKeyToken {
        sealed interface Brand : Decorative {
            data object Primary : Brand
            data object Secondary : Brand
            data object Tertiary : Brand
        }
        sealed interface Neutral : Decorative {
            sealed interface Muted : Neutral {
                data object Lowest : Muted
                data object Lower : Muted
                data object Low : Muted
                data object Medium : Muted
                data object High : Muted
                data object Higher : Muted
                data object Highest : Muted
            }
            sealed interface Emphasized : Neutral {
                data object Lowest : Emphasized
                data object Lower : Emphasized
                data object Low : Emphasized
                data object Higher : Emphasized
            }
        }
        sealed interface Accent1 : Decorative {
            data object Muted : Accent1
            data object Default : Accent1
            data object Emphasized : Accent1
        }
        sealed interface Accent2 : Decorative {
            data object Muted : Accent2
            data object Default : Accent2
            data object Emphasized : Accent2
        }
        sealed interface Accent3 : Decorative {
            data object Muted : Accent3
            data object Default : Accent3
            data object Emphasized : Accent3
        }
        sealed interface Accent4 : Decorative {
            data object Muted : Accent4
            data object Default : Accent4
            data object Emphasized : Accent4
        }
        sealed interface Accent5 : Decorative {
            data object Muted : Accent5
            data object Default : Accent5
            data object Emphasized : Accent5
        }
        sealed interface Skin : Decorative {
            data object Tint100 : Skin
            data object Tint200 : Skin
            data object Tint300 : Skin
            data object Tint400 : Skin
            data object Tint500 : Skin
            data object Tint600 : Skin
            data object Tint700 : Skin
            data object Tint800 : Skin
            data object Tint900 : Skin
        }
    }
}

