//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Orange brand tokens version 2.1.0
// Generated by Tokenator

package com.orange.ouds.theme.tokens

import com.orange.ouds.foundation.InternalOudsApi

@InternalOudsApi
sealed interface OudsColorKeyToken : OudsKeyToken {
    sealed interface Action : OudsColorKeyToken {
        data object Disabled : Action
        data object Enabled : Action
        data object Focus : Action
        data object Highlighted : Action
        data object Hover : Action
        data object Loading : Action
        sealed interface Negative : Action {
            data object Enabled : Negative
            data object Focus : Negative
            data object Hover : Negative
            data object Loading : Negative
            data object Pressed : Negative
        }
        data object Pressed : Action
        data object Selected : Action
        sealed interface Support : Action {
            data object Disabled : Support
            data object Enabled : Support
            data object Focus : Support
            data object Hover : Support
            data object Loading : Support
            data object Pressed : Support
        }
        data object Visited : Action
    }
    sealed interface Always : OudsColorKeyToken {
        data object Black : Always
        data object OnBlack : Always
        data object OnWhite : Always
        data object White : Always
    }
    sealed interface Background : OudsColorKeyToken {
        data object InverseHigh : Background
        data object InverseLow : Background
        data object Primary : Background
        data object Secondary : Background
        data object Tertiary : Background
    }
    sealed interface Border : OudsColorKeyToken {
        data object BrandPrimary : Border
        data object BrandSecondary : Border
        data object BrandTertiary : Border
        data object Default : Border
        data object Emphasized : Border
        data object Focus : Border
        data object FocusInset : Border
        data object Muted : Border
        sealed interface OnBrand : Border {
            data object Primary : OnBrand
            data object Secondary : OnBrand
            data object Tertiary : OnBrand
        }
        sealed interface Status : Border {
            data object Accent : Status
            data object Info : Status
            data object Negative : Status
            data object Positive : Status
            data object Warning : Status
        }
    }
    sealed interface Content : OudsColorKeyToken {
        data object BrandPrimary : Content
        data object BrandSecondary : Content
        data object BrandTertiary : Content
        data object Default : Content
        data object Disabled : Content
        data object Inverse : Content
        data object Muted : Content
        sealed interface OnAction : Content {
            data object Disabled : OnAction
            data object Enabled : OnAction
            data object Focus : OnAction
            data object Highlighted : OnAction
            data object Hover : OnAction
            data object Loading : OnAction
            data object Pressed : OnAction
            data object Selected : OnAction
        }
        sealed interface OnBrand : Content {
            data object Primary : OnBrand
            data object Secondary : OnBrand
            data object Tertiary : OnBrand
        }
        sealed interface OnStatus : Content {
            sealed interface Accent : OnStatus {
                data object Emphasized : Accent
                data object Muted : Accent
            }
            sealed interface Info : OnStatus {
                data object Emphasized : Info
                data object Muted : Info
            }
            sealed interface Negative : OnStatus {
                data object Emphasized : Negative
                data object Muted : Negative
            }
            sealed interface Positive : OnStatus {
                data object Emphasized : Positive
                data object Muted : Positive
            }
            sealed interface Warning : OnStatus {
                data object Emphasized : Warning
                data object Muted : Warning
            }
        }
        sealed interface Status : Content {
            data object Accent : Status
            data object Info : Status
            data object Negative : Status
            data object Positive : Status
            data object Warning : Status
        }
    }
    sealed interface Opacity : OudsColorKeyToken {
        data object Lower : Opacity
        data object Lowest : Opacity
        data object Transparent : Opacity
    }
    sealed interface Overlay : OudsColorKeyToken {
        data object Drag : Overlay
        data object Dropdown : Overlay
        data object Modal : Overlay
        data object Tooltip : Overlay
    }
    sealed interface Repository : OudsColorKeyToken {
        sealed interface Accent : Repository {
            data object High : Accent
            data object Higher : Accent
            data object Highest : Accent
            data object Low : Accent
            data object Lower : Accent
            data object Lowest : Accent
            data object Medium : Accent
        }
        sealed interface Info : Repository {
            data object High : Info
            data object Higher : Info
            data object Highest : Info
            data object Low : Info
            data object Lower : Info
            data object Lowest : Info
            data object Medium : Info
        }
        sealed interface Negative : Repository {
            data object High : Negative
            data object Higher : Negative
            data object Highest : Negative
            data object Low : Negative
            data object Lower : Negative
            data object Lowest : Negative
            data object Medium : Negative
        }
        sealed interface Neutral : Repository {
            sealed interface Emphasized : Neutral {
                data object Black : Emphasized
                data object High : Emphasized
                data object Higher : Emphasized
                data object Highest : Emphasized
                data object Low : Emphasized
                data object Lower : Emphasized
                data object Lowest : Emphasized
                data object Medium : Emphasized
            }
            sealed interface Muted : Neutral {
                data object High : Muted
                data object Higher : Muted
                data object Highest : Muted
                data object Low : Muted
                data object Lower : Muted
                data object Lowest : Muted
                data object Medium : Muted
                data object White : Muted
            }
        }
        sealed interface Opacity : Repository {
            sealed interface Accent : Opacity {
                data object Low : Accent
                data object Medium : Accent
            }
            sealed interface Black : Opacity {
                data object High : Black
                data object Higher : Black
                data object Highest : Black
                data object Low : Black
                data object Lower : Black
                data object Lowest : Black
                data object Medium : Black
                data object MediumHigh : Black
                data object MediumLow : Black
                data object Transparent : Black
            }
            sealed interface Info : Opacity {
                data object Low : Info
                data object Medium : Info
            }
            sealed interface Negative : Opacity {
                data object Low : Negative
                data object Medium : Negative
            }
            sealed interface Positive : Opacity {
                data object Low : Positive
                data object Medium : Positive
            }
            sealed interface Primary : Opacity {
                data object High : Primary
                data object Higher : Primary
                data object Highest : Primary
                data object Low : Primary
                data object Lower : Primary
                data object Lowest : Primary
                data object Medium : Primary
                data object Transparent : Primary
            }
            sealed interface Warning : Opacity {
                data object Low : Warning
                data object Medium : Warning
            }
            sealed interface White : Opacity {
                data object High : White
                data object Higher : White
                data object Highest : White
                data object Low : White
                data object Lower : White
                data object Lowest : White
                data object Medium : White
                data object MediumLow : White
                data object Transparent : White
            }
        }
        sealed interface Positive : Repository {
            data object High : Positive
            data object Higher : Positive
            data object Highest : Positive
            data object Low : Positive
            data object Lower : Positive
            data object Lowest : Positive
            data object Medium : Positive
        }
        sealed interface Primary : Repository {
            data object High : Primary
            data object Higher : Primary
            data object Highest : Primary
            data object Low : Primary
            data object Lower : Primary
            data object Lowest : Primary
            data object Medium : Primary
        }
        sealed interface Secondary : Repository {
            data object High : Secondary
            data object Higher : Secondary
            data object Highest : Secondary
            data object Low : Secondary
            data object Lower : Secondary
            data object Lowest : Secondary
            data object Medium : Secondary
        }
        sealed interface Tertiary : Repository {
            data object High : Tertiary
            data object Higher : Tertiary
            data object Highest : Tertiary
            data object Low : Tertiary
            data object Lower : Tertiary
            data object Lowest : Tertiary
            data object Medium : Tertiary
        }
        sealed interface Warning : Repository {
            data object High : Warning
            data object Higher : Warning
            data object Highest : Warning
            data object Low : Warning
            data object Lower : Warning
            data object Lowest : Warning
            data object Medium : Warning
        }
    }
    sealed interface Surface : OudsColorKeyToken {
        sealed interface Brand : Surface {
            data object Primary : Brand
            data object Secondary : Brand
            data object Tertiary : Brand
        }
        data object InverseHigh : Surface
        data object InverseLow : Surface
        data object Primary : Surface
        data object Secondary : Surface
        sealed interface Status : Surface {
            sealed interface Accent : Status {
                data object Emphasized : Accent
                data object Muted : Accent
            }
            sealed interface Info : Status {
                data object Emphasized : Info
                data object Muted : Info
            }
            sealed interface Negative : Status {
                data object Emphasized : Negative
                data object Muted : Negative
            }
            sealed interface Positive : Status {
                data object Emphasized : Positive
                data object Muted : Positive
            }
            sealed interface Warning : Status {
                data object Emphasized : Warning
                data object Muted : Warning
            }
        }
        data object Tertiary : Surface
    }
}

