//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Orange brand tokens version 2.7.0
// Generated by Tokenator

package com.orange.ouds.theme.tokens

import com.orange.ouds.foundation.InternalOudsApi
import com.orange.ouds.foundation.RestrictedOudsApi

/**
 * @suppress
 */
@InternalOudsApi
sealed interface OudsSpaceKeyToken : OudsKeyToken {
    sealed interface ColumnGap : OudsSpaceKeyToken {
        @RestrictedOudsApi data object ExtraLarge : ColumnGap
        @RestrictedOudsApi data object ExtraSmall : ColumnGap
        @RestrictedOudsApi data object Large : ColumnGap
        @RestrictedOudsApi data object Medium : ColumnGap
        @RestrictedOudsApi data object None : ColumnGap
        @RestrictedOudsApi data object Small : ColumnGap
        @RestrictedOudsApi data object ThreeExtraSmall : ColumnGap
        @RestrictedOudsApi data object TwoExtraLarge : ColumnGap
        @RestrictedOudsApi data object TwoExtraSmall : ColumnGap
    }
    sealed interface Fixed : OudsSpaceKeyToken {
        data object ExtraLarge : Fixed
        data object ExtraSmall : Fixed
        data object FiveExtraLarge : Fixed
        data object FourExtraLarge : Fixed
        data object Large : Fixed
        data object Medium : Fixed
        data object None : Fixed
        data object Small : Fixed
        data object ThreeExtraLarge : Fixed
        data object ThreeExtraSmall : Fixed
        data object TwoExtraLarge : Fixed
        data object TwoExtraSmall : Fixed
    }
    sealed interface Inset : OudsSpaceKeyToken {
        @RestrictedOudsApi data object ExtraLarge : Inset
        @RestrictedOudsApi data object ExtraSmall : Inset
        @RestrictedOudsApi data object FiveExtraSmall : Inset
        @RestrictedOudsApi data object FourExtraSmall : Inset
        @RestrictedOudsApi data object Large : Inset
        @RestrictedOudsApi data object Medium : Inset
        @RestrictedOudsApi data object None : Inset
        @RestrictedOudsApi data object Small : Inset
        @RestrictedOudsApi data object ThreeExtraLarge : Inset
        @RestrictedOudsApi data object ThreeExtraSmall : Inset
        @RestrictedOudsApi data object TwoExtraLarge : Inset
        @RestrictedOudsApi data object TwoExtraSmall : Inset
    }
    sealed interface PaddingBlock : OudsSpaceKeyToken {
        @RestrictedOudsApi data object ExtraLarge : PaddingBlock
        @RestrictedOudsApi data object ExtraSmall : PaddingBlock
        @RestrictedOudsApi data object FiveExtraLarge : PaddingBlock
        @RestrictedOudsApi data object FourExtraLarge : PaddingBlock
        @RestrictedOudsApi data object FourExtraSmall : PaddingBlock
        @RestrictedOudsApi data object Large : PaddingBlock
        @RestrictedOudsApi data object Medium : PaddingBlock
        @RestrictedOudsApi data object None : PaddingBlock
        @RestrictedOudsApi data object Small : PaddingBlock
        @RestrictedOudsApi data object ThreeExtraLarge : PaddingBlock
        @RestrictedOudsApi data object ThreeExtraSmall : PaddingBlock
        @RestrictedOudsApi data object TwoExtraLarge : PaddingBlock
        @RestrictedOudsApi data object TwoExtraSmall : PaddingBlock
    }
    sealed interface PaddingInline : OudsSpaceKeyToken {
        @RestrictedOudsApi data object ExtraLarge : PaddingInline
        @RestrictedOudsApi data object ExtraSmall : PaddingInline
        @RestrictedOudsApi data object FiveExtraLarge : PaddingInline
        @RestrictedOudsApi data object FourExtraLarge : PaddingInline
        @RestrictedOudsApi data object FourExtraSmall : PaddingInline
        @RestrictedOudsApi data object Large : PaddingInline
        @RestrictedOudsApi data object Medium : PaddingInline
        @RestrictedOudsApi data object None : PaddingInline
        @RestrictedOudsApi data object SixExtraLarge : PaddingInline
        @RestrictedOudsApi data object Small : PaddingInline
        @RestrictedOudsApi data object ThreeExtraLarge : PaddingInline
        @RestrictedOudsApi data object ThreeExtraSmall : PaddingInline
        @RestrictedOudsApi data object TwoExtraLarge : PaddingInline
        @RestrictedOudsApi data object TwoExtraSmall : PaddingInline
    }
    sealed interface RowGap : OudsSpaceKeyToken {
        @RestrictedOudsApi data object ExtraSmall : RowGap
        @RestrictedOudsApi data object Large : RowGap
        @RestrictedOudsApi data object Medium : RowGap
        @RestrictedOudsApi data object None : RowGap
        @RestrictedOudsApi data object Small : RowGap
        @RestrictedOudsApi data object ThreeExtraSmall : RowGap
        @RestrictedOudsApi data object TwoExtraSmall : RowGap
    }
    sealed interface Scaled : OudsSpaceKeyToken {
        data object ExtraLarge : Scaled
        data object ExtraSmall : Scaled
        data object Large : Scaled
        data object Medium : Scaled
        data object None : Scaled
        data object Small : Scaled
        data object ThreeExtraLarge : Scaled
        data object ThreeExtraSmall : Scaled
        data object TwoExtraLarge : Scaled
        data object TwoExtraSmall : Scaled
    }
}

