//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Tokens version 1.1.0
// Generated by Tokenator

package com.orange.ouds.theme.tokens

import com.orange.ouds.foundation.InternalOudsApi

@InternalOudsApi
sealed interface OudsBorderKeyToken : OudsKeyToken {
    sealed interface Width : OudsBorderKeyToken {
        data object None : Width
        data object Default : Width
        data object Thin : Width
        data object Medium : Width
        data object Thick : Width
        data object Thicker : Width
        data object Focus : Width
        data object FocusInset : Width
    }
    sealed interface Radius : OudsBorderKeyToken {
        data object None : Radius
        data object Default : Radius
        data object Small : Radius
        data object Medium : Radius
        data object Large : Radius
        data object Pill : Radius
    }
    sealed interface Style : OudsBorderKeyToken {
        data object Default : Style
        data object Drag : Style
    }
}

