//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Tokens version 1.1.0
// Generated by Tokenator

package com.orange.ouds.theme.tokens

import com.orange.ouds.foundation.InternalOudsApi

@InternalOudsApi
sealed interface OudsSpaceKeyToken : OudsKeyToken {
    sealed interface Scaled : OudsSpaceKeyToken {
        data object None : Scaled
        data object 3xs : Scaled
        data object ExtraExtraSmall : Scaled
        data object ExtraSmall : Scaled
        data object Small : Scaled
        data object Medium : Scaled
        data object Large : Scaled
        data object ExtraLarge : Scaled
        data object ExtraExtraLarge : Scaled
        data object 3xl : Scaled
    }
    sealed interface Fixed : OudsSpaceKeyToken {
        data object None : Fixed
        data object 3xs : Fixed
        data object ExtraExtraSmall : Fixed
        data object ExtraSmall : Fixed
        data object Small : Fixed
        data object Medium : Fixed
        data object Large : Fixed
        data object ExtraLarge : Fixed
        data object ExtraExtraLarge : Fixed
        data object 3xl : Fixed
        data object 4xl : Fixed
        data object 5xl : Fixed
    }
    sealed interface PaddingInline : OudsSpaceKeyToken {
        data object None : PaddingInline
        data object 4xs : PaddingInline
        data object 3xs : PaddingInline
        data object ExtraExtraSmall : PaddingInline
        data object ExtraSmall : PaddingInline
        data object Small : PaddingInline
        data object Medium : PaddingInline
        data object Large : PaddingInline
        data object ExtraLarge : PaddingInline
        data object ExtraExtraLarge : PaddingInline
        data object 3xl : PaddingInline
        data object 4xl : PaddingInline
    }
    sealed interface PaddingBlock : OudsSpaceKeyToken {
        data object None : PaddingBlock
        data object 3xs : PaddingBlock
        data object ExtraExtraSmall : PaddingBlock
        data object ExtraSmall : PaddingBlock
        data object Small : PaddingBlock
        data object Medium : PaddingBlock
        data object Large : PaddingBlock
        data object ExtraLarge : PaddingBlock
        data object ExtraExtraLarge : PaddingBlock
        data object 3xl : PaddingBlock
        data object 4xl : PaddingBlock
    }
    sealed interface Inset : OudsSpaceKeyToken {
        data object None : Inset
        data object 4xs : Inset
        data object 3xs : Inset
        data object ExtraExtraSmall : Inset
        data object ExtraSmall : Inset
        data object Small : Inset
        data object Medium : Inset
        data object Large : Inset
        data object ExtraLarge : Inset
        data object ExtraExtraLarge : Inset
        data object 3xl : Inset
    }
    sealed interface ColumnGap : OudsSpaceKeyToken {
        data object None : ColumnGap
        data object 3xs : ColumnGap
        data object ExtraExtraSmall : ColumnGap
        data object ExtraSmall : ColumnGap
        data object Small : ColumnGap
        data object Medium : ColumnGap
        data object Large : ColumnGap
        data object ExtraLarge : ColumnGap
        data object ExtraExtraLarge : ColumnGap
    }
    sealed interface RowGap : OudsSpaceKeyToken {
        data object None : RowGap
        data object 3xs : RowGap
        data object ExtraExtraSmall : RowGap
        data object ExtraSmall : RowGap
        data object Small : RowGap
        data object Medium : RowGap
        data object Large : RowGap
    }
}

