plugins: [
  "@semantic-release/commit-analyzer",
  "@semantic-release/release-notes-generator",
  [
    "@semantic-release/changelog",
    {
      "changelogFile": "changelog.md",
      "changelogTitle": "# OUDS Android library changelog\n\nAll notable changes done in OUDS Android library will be documented in this file.\n\nThe format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),\nand this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html)."
    }
  ],
  #  [ "@semantic-release/exec", {
  #    "verifyConditionsCmd": "./verify.sh",
  #    "publishCmd": "./publish.sh ${nextRelease.version} ${branch.name} ${commits.length} ${Date.now()}"
  #  } ],
  [
    "@semantic-release/git",
    {
      "assets": [ "changelog.md" ],
      "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
    }
  ],
  #  [
  #    "@semantic-release/github",
  #    {
  #      "draftRelease": true
  #    }
  #  ]
]

branches: [
  { name: "main" },
  { name: "dryrun", prerelease: true },
  { name: "beta", channel: "beta", prerelease: true }
]

tagFormat: "${version}"
