//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Sosh brand tokens version 2.5.0
// Generated by Tokenator

package com.orange.ouds.theme.sosh.tokens.components

import com.orange.ouds.theme.tokens.OudsColorKeyToken
import com.orange.ouds.theme.tokens.OudsLightDarkColorKeyToken
import com.orange.ouds.theme.tokens.components.OudsLightDarkColor
import com.orange.ouds.theme.tokens.components.OudsProgressIndicatorMonoTokens
import com.orange.ouds.tokens.raw.OudsColorRawTokens

internal data class SoshProgressIndicatorMonoTokens(
    override val colorContentIndicator: OudsColorKeyToken = OudsLightDarkColorKeyToken(OudsColorKeyToken.Repository.Neutral.Emphasized.Black, OudsColorKeyToken.Repository.Neutral.Muted.White),
    override val colorContentTrack: OudsLightDarkColor = OudsLightDarkColor(OudsColorRawTokens.ColorFunctionalGrayLight400, OudsColorRawTokens.ColorFunctionalGrayDark480)
) : OudsProgressIndicatorMonoTokens
