//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Sosh brand tokens version 1.2.0
// Generated by Tokenator

package com.orange.ouds.theme.sosh.tokens.components

import com.orange.ouds.theme.tokens.OudsBorderKeyToken
import com.orange.ouds.theme.tokens.OudsColorKeyToken
import com.orange.ouds.theme.tokens.OudsSizeKeyToken
import com.orange.ouds.theme.tokens.OudsSpaceKeyToken
import com.orange.ouds.tokens.raw.DimensionRawTokens

data class SoshChipTokens(
    override val badgeColorBg: OudsColorKeyToken = undefined,
    override val badgeColorContent: OudsColorKeyToken = undefined,
    override val borderRadius: OudsBorderKeyToken.Radius = undefined,
    override val borderWidthSelected: OudsBorderKeyToken.Width = undefined,
    override val borderWidthUnselected: OudsBorderKeyToken.Width = undefined,
    override val borderWidthUnselectedInteraction: OudsBorderKeyToken.Width = undefined,
    override val colorBgSelectedDisabled: OudsColorKeyToken = undefined,
    override val colorBgSelectedEnabled: OudsColorKeyToken = undefined,
    override val colorBgSelectedFocus: OudsColorKeyToken = undefined,
    override val colorBgSelectedHover: OudsColorKeyToken = undefined,
    override val colorBgSelectedPressed: OudsColorKeyToken = undefined,
    override val colorBgUnselectedDisabled: OudsColorKeyToken = undefined,
    override val colorBgUnselectedEnabled: OudsColorKeyToken = undefined,
    override val colorBgUnselectedFocus: OudsColorKeyToken = undefined,
    override val colorBgUnselectedHover: OudsColorKeyToken = undefined,
    override val colorBgUnselectedPressed: OudsColorKeyToken = undefined,
    override val colorBorderSelectedDisabled: OudsColorKeyToken = undefined,
    override val colorBorderSelectedEnabled: OudsColorKeyToken = undefined,
    override val colorBorderSelectedFocus: OudsColorKeyToken = undefined,
    override val colorBorderSelectedHover: OudsColorKeyToken = undefined,
    override val colorBorderSelectedPressed: OudsColorKeyToken = undefined,
    override val colorBorderUnselectedDisabled: OudsColorKeyToken = undefined,
    override val colorBorderUnselectedEnabled: OudsColorKeyToken = undefined,
    override val colorBorderUnselectedFocus: OudsColorKeyToken = undefined,
    override val colorBorderUnselectedHover: OudsColorKeyToken = undefined,
    override val colorBorderUnselectedPressed: OudsColorKeyToken = undefined,
    override val colorContentSelectedDisabled: OudsColorKeyToken = undefined,
    override val colorContentSelectedEnabled: OudsColorKeyToken = undefined,
    override val colorContentSelectedFocus: OudsColorKeyToken = undefined,
    override val colorContentSelectedHover: OudsColorKeyToken = undefined,
    override val colorContentSelectedPressed: OudsColorKeyToken = undefined,
    override val colorContentSelectedTickEnabled: OudsColorKeyToken = undefined,
    override val colorContentUnselectedDisabled: OudsColorKeyToken = undefined,
    override val colorContentUnselectedEnabled: OudsColorKeyToken = undefined,
    override val colorContentUnselectedFocus: OudsColorKeyToken = undefined,
    override val colorContentUnselectedHover: OudsColorKeyToken = undefined,
    override val colorContentUnselectedPressed: OudsColorKeyToken = undefined,
    override val sizeIcon: OudsSizeKeyToken.Icon = undefined,
    override val sizeMinHeight: Float = undefined,
    override val sizeMinHeightInteractiveArea: OudsSizeKeyToken = undefined,
    override val sizeMinWidth: Float = undefined,
    override val spaceColumnGapBadgeArrow: OudsSpaceKeyToken.ColumnGap = undefined,
    override val spaceColumnGapIcon: OudsSpaceKeyToken.ColumnGap = undefined,
    override val spacePaddingBlock: OudsSpaceKeyToken.PaddingBlock = undefined,
    override val spacePaddingBlockIconOnly: OudsSpaceKeyToken.PaddingBlock = undefined,
    override val spacePaddingInlineArrowEnd: OudsSpaceKeyToken.PaddingInline = undefined,
    override val spacePaddingInlineBadgeStart: OudsSpaceKeyToken.PaddingInline = undefined,
    override val spacePaddingInlineIcon: OudsSpaceKeyToken.PaddingInline = undefined,
    override val spacePaddingInlineIconNone: OudsSpaceKeyToken.PaddingInline = undefined
) : OudsChipTokens
