//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Sosh brand tokens version 1.2.0
// Generated by Tokenator

package com.orange.ouds.theme.sosh.tokens.components

import com.orange.ouds.theme.tokens.OudsColorKeyToken
import com.orange.ouds.theme.tokens.OudsLightDarkColorKeyToken
import com.orange.ouds.theme.tokens.OudsSizeKeyToken
import com.orange.ouds.theme.tokens.OudsSpaceKeyToken
import com.orange.ouds.tokens.raw.DimensionRawTokens

open class SoshLinkTokens(
    val colorArrowEnabled: OudsColorKeyToken = OudsColorKeyToken.Action.Enabled,
    val colorArrowFocus: OudsColorKeyToken = OudsColorKeyToken.Action.Enabled,
    val colorArrowHover: OudsColorKeyToken = OudsLightDarkColorKeyToken(OudsColorKeyToken.Content.BrandPrimary, OudsColorKeyToken.Action.Enabled),
    val colorArrowPressed: OudsColorKeyToken = OudsColorKeyToken.Action.Pressed,
    val colorContentEnabled: OudsColorKeyToken = OudsColorKeyToken.Content.Default,
    val colorContentFocus: OudsColorKeyToken = OudsColorKeyToken.Action.Focus,
    val colorContentHover: OudsColorKeyToken = OudsColorKeyToken.Action.Hover,
    val colorContentPressed: OudsColorKeyToken = OudsColorKeyToken.Action.Pressed,
    val sizeIconDefault: OudsSizeKeyToken.Icon = OudsSizeKeyToken.Icon.WithLabel.Large.SizeExtraSmall,
    val sizeIconSmall: OudsSizeKeyToken.Icon = OudsSizeKeyToken.Icon.WithLabel.Medium.SizeSmall,
    val sizeMinHeightDefault: OudsSizeKeyToken = OudsSizeKeyToken.MinInteractiveArea,
    val sizeMinHeightSmall: Float = DimensionRawTokens.dimension550,
    val sizeMinWidthDefault: OudsSizeKeyToken = OudsSizeKeyToken.MinInteractiveArea,
    val sizeMinWidthSmall: Float = DimensionRawTokens.dimension550,
    val spaceColumnGapArrowDefault: OudsSpaceKeyToken.ColumnGap = OudsSpaceKeyToken.ColumnGap.TwoExtraSmall,
    val spaceColumnGapArrowSmall: OudsSpaceKeyToken.ColumnGap = OudsSpaceKeyToken.ColumnGap.TwoExtraSmall,
    val spaceColumnGapIconDefault: OudsSpaceKeyToken.ColumnGap = OudsSpaceKeyToken.ColumnGap.Small,
    val spaceColumnGapIconSmall: OudsSpaceKeyToken.ColumnGap = OudsSpaceKeyToken.ColumnGap.ExtraSmall,
    val spacePaddingBlock: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.Medium,
    val spacePaddingInline: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.None
)
