//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Sosh brand tokens version 2.0.1
// Generated by Tokenator

package com.orange.ouds.theme.sosh.tokens.components

import com.orange.ouds.theme.tokens.components.OudsControlItemTokens
import com.orange.ouds.theme.tokens.OudsBorderKeyToken
import com.orange.ouds.theme.tokens.OudsColorKeyToken
import com.orange.ouds.theme.tokens.OudsSizeKeyToken
import com.orange.ouds.theme.tokens.OudsSpaceKeyToken
import com.orange.ouds.tokens.raw.DimensionRawTokens

data class SoshControlItemTokens(
    override val borderRadius: OudsBorderKeyToken.Radius = OudsBorderKeyToken.Radius.None,
    override val borderRadiusItemOnly: OudsBorderKeyToken.Radius = OudsBorderKeyToken.Radius.Default,
    override val colorBgFocus: OudsColorKeyToken = OudsColorKeyToken.Action.Support.Focus,
    override val colorBgHover: OudsColorKeyToken = OudsColorKeyToken.Action.Support.Hover,
    override val colorBgLoading: OudsColorKeyToken = OudsColorKeyToken.Action.Support.Loading,
    override val colorBgPressed: OudsColorKeyToken = OudsColorKeyToken.Action.Support.Pressed,
    override val colorContentLoader: OudsColorKeyToken = OudsColorKeyToken.Content.Default,
    override val sizeIcon: OudsSizeKeyToken.Icon = OudsSizeKeyToken.Icon.WithLabel.Large.SizeMedium,
    override val sizeListItemSizeMinHeightText: OudsSizeKeyToken.Icon = OudsSizeKeyToken.Icon.WithLabel.Large.SizeMedium,
    override val sizeLoader: OudsSizeKeyToken.Icon = OudsSizeKeyToken.Icon.WithLabel.Large.SizeSmall,
    override val sizeMaxHeightAssetsContainer: Float = DimensionRawTokens.dimension1200,
    override val sizeMaxWidth: Float = DimensionRawTokens.dimension4000,
    override val sizeMinHeight: Float = DimensionRawTokens.dimension650,
    override val sizeMinWidth: Float = DimensionRawTokens.dimension2000,
    override val spaceColumnGap: OudsSpaceKeyToken.ColumnGap = OudsSpaceKeyToken.ColumnGap.Medium,
    override val spacePaddingBlock: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.Medium,
    override val spacePaddingInline: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.Large,
    override val spaceRowGap: OudsSpaceKeyToken.RowGap = OudsSpaceKeyToken.RowGap.None
) : OudsControlItemTokens
