//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Sosh brand tokens version 2.5.0
// Generated by Tokenator

package com.orange.ouds.theme.sosh.tokens.components

import com.orange.ouds.theme.tokens.OudsBorderKeyToken
import com.orange.ouds.theme.tokens.OudsSpaceKeyToken
import com.orange.ouds.theme.tokens.components.OudsLightDarkColor
import com.orange.ouds.theme.tokens.components.OudsProgressIndicatorTokens
import com.orange.ouds.tokens.raw.OudsColorRawTokens
import com.orange.ouds.tokens.raw.OudsDimensionRawTokens

internal data class SoshProgressIndicatorTokens(
    override val borderRadiusDefault: OudsBorderKeyToken.Radius = OudsBorderKeyToken.Radius.Pill,
    override val borderRadiusRounded: OudsBorderKeyToken.Radius = OudsBorderKeyToken.Radius.Pill,
    override val colorContentTrack: OudsLightDarkColor = OudsLightDarkColor(OudsColorRawTokens.ColorFunctionalGrayLight400, OudsColorRawTokens.ColorFunctionalGrayDark480),
    override val sizeLinearIndicatorHeight: Float = OudsDimensionRawTokens.Dimension50,
    override val spacePaddingBlock: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.ExtraSmall
) : OudsProgressIndicatorTokens
