//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Tokens version 1.1.0
// Generated by Tokenator

package com.orange.ouds.theme.tokens.material

import androidx.compose.ui.graphics.Color

interface OudsMaterialColorTokens {
    val primaryLight: Color
    val primaryDark: Color
    val onPrimaryLight: Color
    val onPrimaryDark: Color
    val primaryContainerLight: Color
    val primaryContainerDark: Color
    val onPrimaryContainerLight: Color
    val onPrimaryContainerDark: Color
    val secondaryLight: Color
    val secondaryDark: Color
    val onSecondaryLight: Color
    val onSecondaryDark: Color
    val secondaryContainerLight: Color
    val secondaryContainerDark: Color
    val onSecondaryContainerLight: Color
    val onSecondaryContainerDark: Color
    val tertiaryLight: Color
    val tertiaryDark: Color
    val onTertiaryLight: Color
    val onTertiaryDark: Color
    val tertiaryContainerLight: Color
    val tertiaryContainerDark: Color
    val onTertiaryContainerLight: Color
    val onTertiaryContainerDark: Color
    val errorLight: Color
    val errorDark: Color
    val onErrorLight: Color
    val onErrorDark: Color
    val errorContainerLight: Color
    val errorContainerDark: Color
    val onErrorContainerLight: Color
    val onErrorContainerDark: Color
    val primaryFixedLight: Color
    val primaryFixedDark: Color
    val primaryFixedDimLight: Color
    val primaryFixedDimDark: Color
    val onPrimaryFixedLight: Color
    val onPrimaryFixedDark: Color
    val onPrimaryFixedVariantLight: Color
    val onPrimaryFixedVariantDark: Color
    val secondaryFixedLight: Color
    val secondaryFixedDark: Color
    val secondaryFixedDimLight: Color
    val secondaryFixedDimDark: Color
    val onSecondaryFixedLight: Color
    val onSecondaryFixedDark: Color
    val onSecondaryFixedVariantLight: Color
    val onSecondaryFixedVariantDark: Color
    val tertiaryFixedLight: Color
    val tertiaryFixedDark: Color
    val tertiaryFixedDimLight: Color
    val tertiaryFixedDimDark: Color
    val onTertiaryFixedLight: Color
    val onTertiaryFixedDark: Color
    val onTertiaryFixedVariantLight: Color
    val onTertiaryFixedVariantDark: Color
    val surfaceDimLight: Color
    val surfaceDimDark: Color
    val surfaceLight: Color
    val surfaceDark: Color
    val surfaceBrightLight: Color
    val surfaceBrightDark: Color
    val onSurfaceLight: Color
    val onSurfaceDark: Color
    val onSurfaceVariantLight: Color
    val onSurfaceVariantDark: Color
    val surfContainerLowestLight: Color
    val surfContainerLowestDark: Color
    val surfContainerLowLight: Color
    val surfContainerLowDark: Color
    val surfContainerLight: Color
    val surfContainerDark: Color
    val surfContainerHighLight: Color
    val surfContainerHighDark: Color
    val surfContainerHighestLight: Color
    val surfContainerHighestDark: Color
    val inverseSurfaceLight: Color
    val inverseSurfaceDark: Color
    val inverseOnSurfaceLight: Color
    val inverseOnSurfaceDark: Color
    val inversePrimaryLight: Color
    val inversePrimaryDark: Color
    val outlineLight: Color
    val outlineDark: Color
    val outlineVariantLight: Color
    val outlineVariantDark: Color
    val scrimLight: Color
    val scrimDark: Color
    val backgroundLight: Color
    val backgroundDark: Color
    val onBackgroundLight: Color
    val onBackgroundDark: Color
    val surfaceVariantLight: Color
    val surfaceVariantDark: Color
    val surfaceTintLight: Color
    val surfaceTintDark: Color
}
