//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Orange Compact brand tokens version 2.4.0
// Generated by Tokenator

package com.orange.ouds.theme.orangecompact.tokens.components

import com.orange.ouds.theme.tokens.OudsBorderKeyToken
import com.orange.ouds.theme.tokens.components.OudsDividerTokens

internal data class OrangeCompactDividerTokens(
    override val borderWidth: OudsBorderKeyToken.Width = OudsBorderKeyToken.Width.Thin
) : OudsDividerTokens
