//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Orange Compact brand tokens version 2.5.0
// Generated by Tokenator

package com.orange.ouds.theme.orangecompact.tokens.components

import com.orange.ouds.theme.tokens.OudsBorderKeyToken
import com.orange.ouds.theme.tokens.OudsColorKeyToken
import com.orange.ouds.theme.tokens.OudsOpacityKeyToken
import com.orange.ouds.theme.tokens.OudsSizeKeyToken
import com.orange.ouds.theme.tokens.OudsSpaceKeyToken
import com.orange.ouds.theme.tokens.components.OudsListItemTokens
import com.orange.ouds.tokens.raw.OudsDimensionRawTokens
import com.orange.ouds.tokens.raw.OudsFontRawTokens

internal data class OrangeCompactListItemTokens(
    override val borderRadiusCurrentIndicator: OudsBorderKeyToken.Radius = OudsBorderKeyToken.Radius.None,
    override val borderRadiusDefault: OudsBorderKeyToken.Radius = OudsBorderKeyToken.Radius.Default,
    override val borderRadiusMedia: OudsBorderKeyToken.Radius = OudsBorderKeyToken.Radius.Default,
    override val borderRadiusMediaRounded: OudsBorderKeyToken.Radius = OudsBorderKeyToken.Radius.Small,
    override val borderRadiusRounded: OudsBorderKeyToken.Radius = OudsBorderKeyToken.Radius.Medium,
    override val borderWidthCurrentPage: OudsBorderKeyToken.Width = OudsBorderKeyToken.Width.Medium,
    override val borderWidthDefault: OudsBorderKeyToken.Width = OudsBorderKeyToken.Width.Default,
    override val colorBgBadgeSafetyArea: OudsColorKeyToken = OudsColorKeyToken.Background.Primary,
    override val colorBgCurrentDisabled: OudsColorKeyToken = OudsColorKeyToken.Action.Support.Disabled,
    override val colorBgCurrentEnabled: OudsColorKeyToken = OudsColorKeyToken.Action.Support.Enabled,
    override val colorBgCurrentFocus: OudsColorKeyToken = OudsColorKeyToken.Action.Support.Focus,
    override val colorBgCurrentHover: OudsColorKeyToken = OudsColorKeyToken.Action.Support.Hover,
    override val colorBgCurrentPressed: OudsColorKeyToken = OudsColorKeyToken.Action.Support.Pressed,
    override val colorContentCurrentDisabled: OudsColorKeyToken = OudsColorKeyToken.Content.Default,
    override val colorContentCurrentEnabled: OudsColorKeyToken = OudsColorKeyToken.Content.Default,
    override val colorContentCurrentFocus: OudsColorKeyToken = OudsColorKeyToken.Content.Default,
    override val colorContentCurrentHover: OudsColorKeyToken = OudsColorKeyToken.Content.Default,
    override val colorContentCurrentPressed: OudsColorKeyToken = OudsColorKeyToken.Content.Default,
    override val fontLetterSpacingAvatarInitialXlarge: Float = OudsFontRawTokens.FontLetterSpacing350,
    override val fontLineHeightAvatarInitialXlarge: Int = OudsFontRawTokens.FontLineHeight550,
    override val fontSizeAvatarInitialXlarge: Int = OudsFontRawTokens.FontSize350,
    override val opacityCurrentDivider: OudsOpacityKeyToken = OudsOpacityKeyToken.Opaque,
    override val opacityCurrentIndicator: OudsOpacityKeyToken = OudsOpacityKeyToken.Opaque,
    override val sizeAssetLarge: Float = OudsDimensionRawTokens.Dimension450,
    override val sizeAssetMedium: OudsSizeKeyToken.Icon = OudsSizeKeyToken.Icon.WithLabel.Large.SizeMedium,
    override val sizeAssetSmall: OudsSizeKeyToken.Icon = OudsSizeKeyToken.Icon.WithLabel.Large.SizeSmall,
    override val sizeAssetXlarge: Float = OudsDimensionRawTokens.Dimension650,
    override val sizeControlIndicator: OudsSizeKeyToken.Icon = OudsSizeKeyToken.Icon.WithLabel.Large.SizeExtraSmall,
    override val sizeCurrentIndicatorWidth: Float = OudsDimensionRawTokens.Dimension50,
    override val sizeFlagHeight: OudsSizeKeyToken.Icon = OudsSizeKeyToken.Icon.WithLabel.Large.SizeExtraSmall,
    override val sizeMaxWidth: Float = OudsDimensionRawTokens.Dimension4000,
    override val sizeMinHeightDefault: Float = OudsDimensionRawTokens.Dimension650,
    override val sizeMinHeightSmall: OudsSizeKeyToken = OudsSizeKeyToken.MinInteractiveArea,
    override val sizeMinWidth: Float = OudsDimensionRawTokens.Dimension1800,
    override val spaceColumnGap: OudsSpaceKeyToken.ColumnGap = OudsSpaceKeyToken.ColumnGap.Medium,
    override val spacePaddingBlockBottomSlotListItemContainer: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.Large,
    override val spacePaddingBlockBottomSlotTextContainer: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.FourExtraSmall,
    override val spacePaddingBlockDefault: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.Medium,
    override val spacePaddingBlockSmall: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.ExtraSmall,
    override val spacePaddingBlockTopAlignmentTopCounterweightDefault: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.Small,
    override val spacePaddingBlockTopAlignmentTopCounterweightSmall: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.ExtraSmall,
    override val spacePaddingBlockTopAlignmentTopTextContainerDefault: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.FourExtraSmall,
    override val spacePaddingBlockTopAlignmentTopTextContainerSmall: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.None,
    override val spacePaddingBlockTopHelperText: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.ExtraSmall,
    override val spacePaddingInline: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.Large,
    override val spaceRowGap: OudsSpaceKeyToken.RowGap = OudsSpaceKeyToken.RowGap.None
) : OudsListItemTokens
