//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Orange Compact brand tokens version 2.6.0
// Generated by Tokenator

package com.orange.ouds.theme.orangecompact.tokens.components

import com.orange.ouds.theme.tokens.OudsColorKeyToken
import com.orange.ouds.theme.tokens.OudsSizeKeyToken
import com.orange.ouds.theme.tokens.OudsSpaceKeyToken
import com.orange.ouds.theme.tokens.components.OudsLinkTokens
import com.orange.ouds.tokens.raw.OudsDimensionRawTokens

internal data class OrangeCompactLinkTokens(
    override val colorChevronEnabled: OudsColorKeyToken = OudsColorKeyToken.Content.BrandPrimary,
    @Deprecated("") override val colorChevronFocus: OudsColorKeyToken = OudsColorKeyToken.Content.BrandPrimary,
    @Deprecated("") override val colorChevronHover: OudsColorKeyToken = OudsColorKeyToken.Content.BrandPrimary,
    @Deprecated("") override val colorChevronPressed: OudsColorKeyToken = OudsColorKeyToken.Content.BrandPrimary,
    override val colorContentEnabled: OudsColorKeyToken = OudsColorKeyToken.Action.Enabled,
    override val colorContentFocus: OudsColorKeyToken = OudsColorKeyToken.Action.Focus,
    override val colorContentHover: OudsColorKeyToken = OudsColorKeyToken.Action.Hover,
    override val colorContentPressed: OudsColorKeyToken = OudsColorKeyToken.Action.Pressed,
    override val sizeIconDefault: OudsSizeKeyToken.Icon = OudsSizeKeyToken.Icon.WithLabel.Large.SizeExtraSmall,
    override val sizeIconSmall: OudsSizeKeyToken.Icon = OudsSizeKeyToken.Icon.WithLabel.Medium.SizeSmall,
    override val sizeMinHeightCompactDensity: Float = OudsDimensionRawTokens.Dimension350,
    override val sizeMinHeightDefault: OudsSizeKeyToken = OudsSizeKeyToken.MinInteractiveAreaDefault,
    override val sizeMinHeightSmall: OudsSizeKeyToken = OudsSizeKeyToken.MinInteractiveAreaSmall,
    override val sizeMinWidth: Float = OudsDimensionRawTokens.Dimension350,
    @Deprecated("") override val sizeMinWidthSmall: OudsSizeKeyToken = OudsSizeKeyToken.MinInteractiveAreaSmall,
    override val spaceColumnGapChevronDefault: OudsSpaceKeyToken.ColumnGap = OudsSpaceKeyToken.ColumnGap.TwoExtraSmall,
    override val spaceColumnGapChevronSmall: OudsSpaceKeyToken.ColumnGap = OudsSpaceKeyToken.ColumnGap.TwoExtraSmall,
    override val spaceColumnGapIconDefault: OudsSpaceKeyToken.ColumnGap = OudsSpaceKeyToken.ColumnGap.ExtraSmall,
    override val spaceColumnGapIconSmall: OudsSpaceKeyToken.ColumnGap = OudsSpaceKeyToken.ColumnGap.ExtraSmall,
    override val spacePaddingBlockCompactDensityDefault: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.ThreeExtraSmall,
    override val spacePaddingBlockCompactDensitySmall: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.TwoExtraSmall,
    override val spacePaddingBlockDefault: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.Medium,
    override val spacePaddingBlockSmall: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.Small,
    override val spacePaddingInline: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.None
) : OudsLinkTokens
