//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Orange Compact brand tokens version 2.4.0
// Generated by Tokenator

package com.orange.ouds.theme.orangecompact.tokens.components

import com.orange.ouds.theme.tokens.OudsSpaceKeyToken
import com.orange.ouds.theme.tokens.components.OudsBadgeTokens
import com.orange.ouds.tokens.raw.OudsDimensionRawTokens

internal data class OrangeCompactBadgeTokens(
    override val sizeLarge: Float = OudsDimensionRawTokens.Dimension250,
    override val sizeMedium: Float = OudsDimensionRawTokens.Dimension200,
    override val sizeSmall: Float = OudsDimensionRawTokens.Dimension150,
    override val sizeXsmall: Float = OudsDimensionRawTokens.Dimension100,
    override val spaceInsetMediumLarge: Float = OudsDimensionRawTokens.DimensionOutOfSystem75,
    override val spaceInsetSmall: Float = OudsDimensionRawTokens.DimensionOutOfSystem50,
    override val spaceInsetXsmall: Float = OudsDimensionRawTokens.DimensionOutOfSystem25,
    override val spacePaddingInlineLarge: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.TwoExtraSmall,
    override val spacePaddingInlineMedium: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.ThreeExtraSmall
) : OudsBadgeTokens
