//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Orange core tokens version 1.2.0
// Generated by Tokenator

package com.orange.ouds.theme.orange.tokens.raw

import androidx.compose.ui.graphics.Color

object OrangeColorRawTokens {
  val ColorDecorativeAmber100 = Color(0xfffff0cc)
  val ColorDecorativeAmber200 = Color(0xffffe199)
  val ColorDecorativeAmber300 = Color(0xffffd266)
  val ColorDecorativeAmber400 = Color(0xffffc333)
  val ColorDecorativeAmber500 = Color(0xffffb400)
  val ColorDecorativeAmber600 = Color(0xffcc9000)
  val ColorDecorativeAmber700 = Color(0xff996c00)
  val ColorDecorativeAmber800 = Color(0xff664800)
  val ColorDecorativeAmber900 = Color(0xff332400)
  val ColorDecorativeAmethyst100 = Color(0xfff1ecf9)
  val ColorDecorativeAmethyst200 = Color(0xffe0d4f2)
  val ColorDecorativeAmethyst300 = Color(0xffc5ade6)
  val ColorDecorativeAmethyst400 = Color(0xffa885d8)
  val ColorDecorativeAmethyst500 = Color(0xff8d60cd)
  val ColorDecorativeAmethyst600 = Color(0xff5b2f98)
  val ColorDecorativeAmethyst700 = Color(0xff432371)
  val ColorDecorativeAmethyst800 = Color(0xff2c174a)
  val ColorDecorativeAmethyst900 = Color(0xff150b23)
  val ColorDecorativeDeepPeach100 = Color(0xfffbebdf)
  val ColorDecorativeDeepPeach200 = Color(0xfff4cfb2)
  val ColorDecorativeDeepPeach300 = Color(0xffe3b591)
  val ColorDecorativeDeepPeach400 = Color(0xffc19372)
  val ColorDecorativeDeepPeach500 = Color(0xffcf7e3f)
  val ColorDecorativeDeepPeach600 = Color(0xffaa6631)
  val ColorDecorativeDeepPeach700 = Color(0xff7e4f2a)
  val ColorDecorativeDeepPeach800 = Color(0xff553720)
  val ColorDecorativeDeepPeach900 = Color(0xff2e2014)
  val ColorDecorativeEmerald100 = Color(0xffe5f5ed)
  val ColorDecorativeEmerald200 = Color(0xffc0e8d4)
  val ColorDecorativeEmerald300 = Color(0xff9bdaba)
  val ColorDecorativeEmerald400 = Color(0xff75cca1)
  val ColorDecorativeEmerald500 = Color(0xff50be87)
  val ColorDecorativeEmerald600 = Color(0xff3ba06e)
  val ColorDecorativeEmerald700 = Color(0xff2e7b54)
  val ColorDecorativeEmerald800 = Color(0xff20563b)
  val ColorDecorativeEmerald900 = Color(0xff123021)
  val ColorDecorativeShockingPink100 = Color(0xffffe5f6)
  val ColorDecorativeShockingPink200 = Color(0xffffb4e6)
  val ColorDecorativeShockingPink300 = Color(0xffff80d4)
  val ColorDecorativeShockingPink400 = Color(0xffff4dc3)
  val ColorDecorativeShockingPink500 = Color(0xffff1ab2)
  val ColorDecorativeShockingPink600 = Color(0xffe50099)
  val ColorDecorativeShockingPink700 = Color(0xffb20077)
  val ColorDecorativeShockingPink800 = Color(0xff800055)
  val ColorDecorativeShockingPink900 = Color(0xff4d0033)
  val ColorDecorativeSky100 = Color(0xffd2ecf9)
  val ColorDecorativeSky200 = Color(0xffa5daf3)
  val ColorDecorativeSky300 = Color(0xff79c7ec)
  val ColorDecorativeSky400 = Color(0xff4ab4e6)
  val ColorDecorativeSky500 = Color(0xff1fa2e0)
  val ColorDecorativeSky600 = Color(0xff1982b3)
  val ColorDecorativeSky700 = Color(0xff136186)
  val ColorDecorativeSky800 = Color(0xff0c415a)
  val ColorDecorativeSky900 = Color(0xff06202d)
  val ColorOpacityWarmGray80 = Color(0x14bd793c)
  val ColorOpacityWarmGray400 = Color(0x66685d50)
  val ColorOrange50 = Color(0xfffff2e6)
  val ColorOrange100 = Color(0xffffd5b0)
  val ColorOrange200 = Color(0xffffc18a)
  val ColorOrange300 = Color(0xffffa554)
  val ColorOrange400 = Color(0xffff9433)
  val ColorOrange500 = Color(0xffff7900)
  val ColorOrange550 = Color(0xfff15e00)
  val ColorOrange600 = Color(0xffe86e00)
  val ColorOrange700 = Color(0xffb55600)
  val ColorOrange800 = Color(0xff8c4300)
  val ColorOrange900 = Color(0xff6b3300)
  val ColorWarmGray100 = Color(0xfff9f5f0)
  val ColorWarmGray200 = Color(0xffe9ddce)
  val ColorWarmGray300 = Color(0xffd6c4ae)
  val ColorWarmGray400 = Color(0xffc1ab90)
  val ColorWarmGray500 = Color(0xffa99275)
  val ColorWarmGray600 = Color(0xff8a7860)
  val ColorWarmGray700 = Color(0xff685d50)
  val ColorWarmGray800 = Color(0xff48433d)
  val ColorWarmGray900 = Color(0xff353228)
  val ColorWarmGray1000 = Color(0xff23211a)
}
