[versions]
activityCompose = "1.9.0"
appcompat = "1.7.0"
androidCompileSdk = "34"
androidMinSdk = "21"
androidTargetSdk = "34"
browser = "1.8.0"
composeBom = "2024.06.00"
coreKtx = "1.13.1"
firebaseAppDistribution = "5.0.0"
firebaseBom = "33.1.1"
firebaseCrashlytics = "3.0.2"
googleAuthLibraryOauth2Http = "1.19.0"
googleServices = "4.4.2"
dataStorePreferences = "1.1.1"
gradle = "8.5.0"
hilt = "2.51.1"
javaPoet = "1.13.0"
json = "20240303"
kotlin = "2.0.0"
material = "1.12.0"
navigationCompose = "2.7.7"
zxingCore = "3.5.1"
zxingJavaSe = "3.5.1"


[libraries]
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "gradle" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "dataStorePreferences" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
google-auth-library-oauth2-http = { module = "com.google.auth:google-auth-library-oauth2-http", version.ref = "googleAuthLibraryOauth2Http" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
javapoet = { group = "com.squareup", name = "javapoet", version.ref = "javaPoet" }
json = { module = "org.json:json", version.ref = "json" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
zxing-core = { module = "com.google.zxing:core", version.ref = "zxingCore" }
zxing-javase = { module = "com.google.zxing:javase", version.ref = "zxingJavaSe" }

[plugins]
android-application = { id = "com.android.application", version.ref = "gradle" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
firebase-appdistribution = { id = "com.google.firebase.appdistribution", version.ref = "firebaseAppDistribution" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlytics" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "gradle" }

