//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Orange brand tokens version 1.5.0
// Generated by Tokenator

package com.orange.ouds.theme.tokens.components

import com.orange.ouds.theme.tokens.OudsColorKeyToken
import com.orange.ouds.theme.tokens.OudsSizeKeyToken
import com.orange.ouds.theme.tokens.OudsSpaceKeyToken
import com.orange.ouds.tokens.raw.DimensionRawTokens

interface OudsLinkTokens {
    val colorChevronEnabled: OudsColorKeyToken
    val colorChevronFocus: OudsColorKeyToken
    val colorChevronHover: OudsColorKeyToken
    val colorChevronPressed: OudsColorKeyToken
    val colorContentEnabled: OudsColorKeyToken
    val colorContentFocus: OudsColorKeyToken
    val colorContentHover: OudsColorKeyToken
    val colorContentPressed: OudsColorKeyToken
    val sizeIconDefault: OudsSizeKeyToken.Icon
    val sizeIconSmall: OudsSizeKeyToken.Icon
    val sizeMinHeightDefault: OudsSizeKeyToken
    val sizeMinHeightSmall: Float
    val sizeMinWidthDefault: OudsSizeKeyToken
    val sizeMinWidthSmall: Float
    val spaceColumnGapChevronDefault: OudsSpaceKeyToken.ColumnGap
    val spaceColumnGapChevronSmall: OudsSpaceKeyToken.ColumnGap
    val spaceColumnGapIconDefault: OudsSpaceKeyToken.ColumnGap
    val spaceColumnGapIconSmall: OudsSpaceKeyToken.ColumnGap
    val spacePaddingBlock: OudsSpaceKeyToken.PaddingBlock
    val spacePaddingInline: OudsSpaceKeyToken.PaddingInline
}
