//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Orange brand tokens version 1.6.0
// Generated by Tokenator

package com.orange.ouds.theme.tokens.components

import com.orange.ouds.theme.tokens.OudsBorderKeyToken
import com.orange.ouds.theme.tokens.OudsColorKeyToken

interface OudsInputTagTokens {
    val borderWidthDefault: OudsBorderKeyToken.Width
    val borderWidthDefaultInteraction: OudsBorderKeyToken.Width
    val colorBgEnabled: OudsColorKeyToken
    val colorBgFocus: OudsColorKeyToken
    val colorBgHover: OudsColorKeyToken
    val colorBgPressed: OudsColorKeyToken
    val colorBorderEnabled: OudsColorKeyToken
    val colorBorderFocus: OudsColorKeyToken
    val colorBorderHover: OudsColorKeyToken
    val colorBorderPressed: OudsColorKeyToken
    val colorContentEnabled: OudsColorKeyToken
    val colorContentFocus: OudsColorKeyToken
    val colorContentHover: OudsColorKeyToken
    val colorContentPressed: OudsColorKeyToken
}
