//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Orange brand tokens version 2.4.0
// Generated by Tokenator

package com.orange.ouds.theme.tokens.components

import com.orange.ouds.foundation.InternalOudsApi
import com.orange.ouds.theme.tokens.OudsBorderKeyToken
import com.orange.ouds.theme.tokens.OudsColorKeyToken
import com.orange.ouds.theme.tokens.OudsOpacityKeyToken

/** @suppress */
@InternalOudsApi
interface OudsBarTokens {
    val borderRadiusCurrentIndicatorCustomBottom: OudsBorderKeyToken.Radius
    val borderRadiusCurrentIndicatorCustomTop: OudsBorderKeyToken.Radius
    val colorBgOpaque: OudsColorKeyToken
    val colorBgTranslucent: OudsLightDarkColor
    val colorBorderBadge: OudsColorKeyToken
    val colorContentOnIosAccent: OudsColorKeyToken
    val colorContentSelectedEnabled: OudsColorKeyToken
    val colorContentSelectedFocus: OudsColorKeyToken
    val colorContentSelectedHover: OudsColorKeyToken
    val colorContentSelectedPressed: OudsColorKeyToken
    val colorContentUnselectedEnabled: OudsColorKeyToken
    val colorContentUnselectedFocus: OudsColorKeyToken
    val colorContentUnselectedHover: OudsColorKeyToken
    val colorContentUnselectedPressed: OudsColorKeyToken
    val colorCurrentIndicatorAndroidSelectedDisabled: OudsColorKeyToken
    val colorCurrentIndicatorAndroidSelectedEnabled: OudsColorKeyToken
    val colorCurrentIndicatorAndroidSelectedFocus: OudsColorKeyToken
    val colorCurrentIndicatorAndroidSelectedHover: OudsColorKeyToken
    val colorCurrentIndicatorAndroidSelectedPressed: OudsColorKeyToken
    val colorCurrentIndicatorAndroidUnselectedDisabled: OudsColorKeyToken
    val colorCurrentIndicatorAndroidUnselectedFocus: OudsColorKeyToken
    val colorCurrentIndicatorAndroidUnselectedHover: OudsColorKeyToken
    val colorCurrentIndicatorAndroidUnselectedPressed: OudsColorKeyToken
    val colorCurrentIndicatorCustomSelectedEnabled: OudsColorKeyToken
    val colorCurrentIndicatorCustomSelectedFocus: OudsColorKeyToken
    val colorCurrentIndicatorCustomSelectedHover: OudsColorKeyToken
    val colorCurrentIndicatorCustomSelectedPressed: OudsColorKeyToken
    val colorIosAccent: OudsColorKeyToken
    val effectBgBlur: Int
    val opacityCurrentIndicatorCustom: OudsOpacityKeyToken
    val sizeHeightCurrentIndicatorCustom: Float
    val sizeWidthCurrentIndicatorCustomBottom: Float
    val sizeWidthCurrentIndicatorCustomTop: Float
}
