//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Orange brand tokens version 2.4.0
// Generated by Tokenator

package com.orange.ouds.theme.tokens.components

import com.orange.ouds.foundation.InternalOudsApi
import com.orange.ouds.theme.tokens.OudsSpaceKeyToken

/** @suppress */
@InternalOudsApi
interface OudsBadgeTokens {
    val sizeLarge: Float
    val sizeMedium: Float
    val sizeSmall: Float
    val sizeXsmall: Float
    val spaceInsetMediumLarge: Float
    val spaceInsetSmall: Float
    val spaceInsetXsmall: Float
    val spacePaddingInlineLarge: OudsSpaceKeyToken.PaddingInline
    val spacePaddingInlineMedium: OudsSpaceKeyToken.PaddingInline
}
