//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Orange brand tokens version 2.1.0
// Generated by Tokenator

package com.orange.ouds.theme.tokens.components

import com.orange.ouds.theme.tokens.OudsBorderKeyToken
import com.orange.ouds.theme.tokens.OudsColorKeyToken
import com.orange.ouds.theme.tokens.OudsSizeKeyToken
import com.orange.ouds.theme.tokens.OudsSpaceKeyToken

interface OudsControlItemTokens {
    val borderRadius: OudsBorderKeyToken.Radius
    val borderRadiusItemOnly: OudsBorderKeyToken.Radius
    val colorBgFocus: OudsColorKeyToken
    val colorBgHover: OudsColorKeyToken
    val colorBgLoading: OudsColorKeyToken
    val colorBgPressed: OudsColorKeyToken
    val colorContentLoader: OudsColorKeyToken
    val sizeErrorIcon: OudsSizeKeyToken.Icon
    val sizeIcon: OudsSizeKeyToken.Icon
    val sizeListItemSizeMinHeightText: OudsSizeKeyToken.Icon
    val sizeLoader: OudsSizeKeyToken.Icon
    val sizeMaxHeightAssetsContainer: Float
    val sizeMaxWidth: Float
    val sizeMinHeight: Float
    val sizeMinWidth: Float
    val spaceColumnGap: OudsSpaceKeyToken.ColumnGap
    val spacePaddingBlock: OudsSpaceKeyToken.PaddingBlock
    val spacePaddingInline: OudsSpaceKeyToken.PaddingInline
    val spacePaddingInlineErrorIcon: OudsSpaceKeyToken.PaddingInline
    val spaceRowGap: OudsSpaceKeyToken.RowGap
}
