//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Orange brand tokens version 1.3.0
// Generated by Tokenator

package com.orange.ouds.theme.tokens.components

import com.orange.ouds.theme.tokens.OudsSpaceKeyToken
import com.orange.ouds.tokens.raw.DimensionRawTokens

open class OudsBadgeTokens(
    val sizeLarge: Float = DimensionRawTokens.dimension250,
    val sizeMedium: Float = DimensionRawTokens.dimension200,
    val sizeSmall: Float = DimensionRawTokens.dimension150,
    val sizeXsmall: Float = DimensionRawTokens.dimension100,
    val spaceInset: Float = DimensionRawTokens.dimensionOutOfSystem75,
    val spacePaddingInlineLarge: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.TwoExtraSmall,
    val spacePaddingInlineMedium: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.ThreeExtraSmall
)
