//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Orange brand tokens version 1.3.0
// Generated by Tokenator

package com.orange.ouds.theme.tokens.components

import com.orange.ouds.theme.tokens.OudsBorderKeyToken
import com.orange.ouds.theme.tokens.OudsColorKeyToken
import com.orange.ouds.theme.tokens.OudsSizeKeyToken
import com.orange.ouds.theme.tokens.OudsSpaceKeyToken

open class OudsButtonTokens(
    val borderRadius: OudsBorderKeyToken.Radius = OudsBorderKeyToken.Radius.Default,
    val borderWidthDefault: OudsBorderKeyToken.Width = OudsBorderKeyToken.Width.Default,
    val borderWidthDefaultInteraction: OudsBorderKeyToken.Width = OudsBorderKeyToken.Width.Medium,
    val borderWidthDefaultInteractionMono: OudsBorderKeyToken.Width = OudsBorderKeyToken.Width.None,
    val borderWidthMinimal: OudsBorderKeyToken.Width = OudsBorderKeyToken.Width.None,
    val borderWidthMinimalInteraction: OudsBorderKeyToken.Width = OudsBorderKeyToken.Width.None,
    val colorBgDefaultDisabled: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    val colorBgDefaultEnabled: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    val colorBgDefaultFocus: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    val colorBgDefaultHover: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    val colorBgDefaultLoading: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    val colorBgDefaultPressed: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    val colorBgMinimalDisabled: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    val colorBgMinimalEnabled: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    val colorBgMinimalFocus: OudsColorKeyToken = OudsColorKeyToken.Action.Support.Focus,
    val colorBgMinimalHover: OudsColorKeyToken = OudsColorKeyToken.Action.Support.Hover,
    val colorBgMinimalLoading: OudsColorKeyToken = OudsColorKeyToken.Action.Support.Loading,
    val colorBgMinimalPressed: OudsColorKeyToken = OudsColorKeyToken.Action.Support.Pressed,
    val colorBorderDefaultDisabled: OudsColorKeyToken = OudsColorKeyToken.Action.Disabled,
    val colorBorderDefaultEnabled: OudsColorKeyToken = OudsColorKeyToken.Action.Enabled,
    val colorBorderDefaultFocus: OudsColorKeyToken = OudsColorKeyToken.Action.Focus,
    val colorBorderDefaultHover: OudsColorKeyToken = OudsColorKeyToken.Action.Hover,
    val colorBorderDefaultLoading: OudsColorKeyToken = OudsColorKeyToken.Action.Loading,
    val colorBorderDefaultPressed: OudsColorKeyToken = OudsColorKeyToken.Action.Pressed,
    val colorBorderMinimalDisabled: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    val colorBorderMinimalEnabled: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    val colorBorderMinimalFocus: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    val colorBorderMinimalHover: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    val colorBorderMinimalLoading: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    val colorBorderMinimalPressed: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    val colorContentDefaultDisabled: OudsColorKeyToken = OudsColorKeyToken.Action.Disabled,
    val colorContentDefaultEnabled: OudsColorKeyToken = OudsColorKeyToken.Action.Enabled,
    val colorContentDefaultFocus: OudsColorKeyToken = OudsColorKeyToken.Action.Focus,
    val colorContentDefaultHover: OudsColorKeyToken = OudsColorKeyToken.Action.Hover,
    val colorContentDefaultLoading: OudsColorKeyToken = OudsColorKeyToken.Action.Loading,
    val colorContentDefaultPressed: OudsColorKeyToken = OudsColorKeyToken.Action.Pressed,
    val colorContentMinimalDisabled: OudsColorKeyToken = OudsColorKeyToken.Action.Disabled,
    val colorContentMinimalEnabled: OudsColorKeyToken = OudsColorKeyToken.Action.Enabled,
    val colorContentMinimalFocus: OudsColorKeyToken = OudsColorKeyToken.Action.Focus,
    val colorContentMinimalHover: OudsColorKeyToken = OudsColorKeyToken.Action.Hover,
    val colorContentMinimalLoading: OudsColorKeyToken = OudsColorKeyToken.Content.Default,
    val colorContentMinimalPressed: OudsColorKeyToken = OudsColorKeyToken.Action.Pressed,
    val sizeIcon: OudsSizeKeyToken.Icon = OudsSizeKeyToken.Icon.WithLabel.Large.SizeExtraSmall,
    val sizeIconOnly: OudsSizeKeyToken.Icon = OudsSizeKeyToken.Icon.WithLabel.Large.SizeSmall,
    val sizeLoader: OudsSizeKeyToken.Icon = OudsSizeKeyToken.Icon.WithLabel.Large.SizeExtraSmall,
    val sizeMaxHeightIconOnly: OudsSizeKeyToken = OudsSizeKeyToken.MinInteractiveArea,
    val sizeMinHeight: OudsSizeKeyToken = OudsSizeKeyToken.MinInteractiveArea,
    val sizeMinWidth: OudsSizeKeyToken = OudsSizeKeyToken.MinInteractiveArea,
    val spaceColumnGapChevron: OudsSpaceKeyToken.ColumnGap = OudsSpaceKeyToken.ColumnGap.ExtraSmall,
    val spaceColumnGapIcon: OudsSpaceKeyToken.ColumnGap = OudsSpaceKeyToken.ColumnGap.Small,
    val spaceColumnGapIconChevron: OudsSpaceKeyToken.ColumnGap = OudsSpaceKeyToken.ColumnGap.TwoExtraSmall,
    val spaceInsetIconOnly: OudsSpaceKeyToken.Inset = OudsSpaceKeyToken.Inset.Medium,
    val spacePaddingBlock: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.Medium,
    val spacePaddingInlineChevronEnd: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.Large,
    val spacePaddingInlineChevronStart: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.Large,
    val spacePaddingInlineEndIconStart: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.ThreeExtraLarge,
    val spacePaddingInlineIconNone: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.FourExtraLarge,
    val spacePaddingInlineIconStart: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.ExtraLarge,
    val spacePaddingInlineStartIconEnd: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.ThreeExtraLarge
)
