//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Tokens version 1.1.0
// Generated by Tokenator

package com.orange.ouds.theme.tokens.components

import com.orange.ouds.theme.tokens.OudsBorderKeyToken
import com.orange.ouds.theme.tokens.OudsColorKeyToken
import com.orange.ouds.theme.tokens.OudsSizeKeyToken
import com.orange.ouds.theme.tokens.OudsSpaceKeyToken
import com.orange.ouds.tokens.raw.DimensionRawTokens

open class OudsChipTokens(
    val badgeColorBg: OudsColorKeyToken = OudsColorKeyToken.Surface.Status.Neutral.Emphasized,
    val badgeColorContent: OudsColorKeyToken = OudsColorKeyToken.Content.OnStatus.Neutral.Emphasized,
    val borderRadius: OudsBorderKeyToken.Radius = OudsBorderKeyToken.Radius.Pill,
    val borderWidthSelected: OudsBorderKeyToken.Width = OudsBorderKeyToken.Width.Medium,
    val borderWidthUnselected: OudsBorderKeyToken.Width = OudsBorderKeyToken.Width.Default,
    val borderWidthUnselectedInteraction: OudsBorderKeyToken.Width = OudsBorderKeyToken.Width.Medium,
    val colorBgSelectedDisabled: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    val colorBgSelectedEnabled: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    val colorBgSelectedFocus: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    val colorBgSelectedHover: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    val colorBgSelectedPressed: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    val colorBgUnselectedDisabled: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    val colorBgUnselectedEnabled: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    val colorBgUnselectedFocus: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    val colorBgUnselectedHover: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    val colorBgUnselectedPressed: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    val colorBorderSelectedDisabled: OudsColorKeyToken = OudsColorKeyToken.Action.Disabled,
    val colorBorderSelectedEnabled: OudsColorKeyToken = OudsColorKeyToken.Action.Selected,
    val colorBorderSelectedFocus: OudsColorKeyToken = OudsColorKeyToken.Action.Focus,
    val colorBorderSelectedHover: OudsColorKeyToken = OudsColorKeyToken.Action.Hover,
    val colorBorderSelectedPressed: OudsColorKeyToken = OudsColorKeyToken.Action.Pressed,
    val colorBorderUnselectedDisabled: OudsColorKeyToken = OudsColorKeyToken.Action.Disabled,
    val colorBorderUnselectedEnabled: OudsColorKeyToken = OudsColorKeyToken.Border.Default,
    val colorBorderUnselectedFocus: OudsColorKeyToken = OudsColorKeyToken.Action.Focus,
    val colorBorderUnselectedHover: OudsColorKeyToken = OudsColorKeyToken.Action.Hover,
    val colorBorderUnselectedPressed: OudsColorKeyToken = OudsColorKeyToken.Action.Pressed,
    val colorContentSelectedDisabled: OudsColorKeyToken = OudsColorKeyToken.Action.Disabled,
    val colorContentSelectedEnabled: OudsColorKeyToken = OudsColorKeyToken.Action.Enabled,
    val colorContentSelectedFocus: OudsColorKeyToken = OudsColorKeyToken.Action.Focus,
    val colorContentSelectedHover: OudsColorKeyToken = OudsColorKeyToken.Action.Hover,
    val colorContentSelectedPressed: OudsColorKeyToken = OudsColorKeyToken.Action.Pressed,
    val colorContentSelectedTickEnabled: OudsColorKeyToken = OudsColorKeyToken.Action.Selected,
    val colorContentUnselectedDisabled: OudsColorKeyToken = OudsColorKeyToken.Action.Disabled,
    val colorContentUnselectedEnabled: OudsColorKeyToken = OudsColorKeyToken.Action.Enabled,
    val colorContentUnselectedFocus: OudsColorKeyToken = OudsColorKeyToken.Action.Focus,
    val colorContentUnselectedHover: OudsColorKeyToken = OudsColorKeyToken.Action.Hover,
    val colorContentUnselectedPressed: OudsColorKeyToken = OudsColorKeyToken.Action.Pressed,
    val sizeIcon: OudsSizeKeyToken.Icon = OudsSizeKeyToken.Icon.WithLabel.Medium.SizeSmall,
    val sizeMinHeight: Float = DimensionRawTokens.dimension400,
    val sizeMinHeightInteractiveArea: OudsSizeKeyToken = OudsSizeKeyToken.MinInteractiveArea,
    val sizeMinWidth: Float = DimensionRawTokens.dimension650,
    val spaceColumnGapBadgeArrow: OudsSpaceKeyToken.ColumnGap = OudsSpaceKeyToken.ColumnGap.TwoExtraSmall,
    val spaceColumnGapIcon: OudsSpaceKeyToken.ColumnGap = OudsSpaceKeyToken.ColumnGap.ExtraSmall,
    val spacePaddingBlock: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.ExtraSmall,
    val spacePaddingBlockIconOnly: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.Small,
    val spacePaddingInlineArrowEnd: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.ExtraSmall,
    val spacePaddingInlineBadgeStart: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.FourExtraSmall,
    val spacePaddingInlineIcon: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.Small,
    val spacePaddingInlineIconNone: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.Large
)
