//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Orange brand tokens version 2.5.0
// Generated by Tokenator

package com.orange.ouds.theme.tokens.components

import com.orange.ouds.foundation.InternalOudsApi
import com.orange.ouds.theme.tokens.OudsBorderKeyToken
import com.orange.ouds.theme.tokens.OudsColorKeyToken
import com.orange.ouds.theme.tokens.OudsOpacityKeyToken
import com.orange.ouds.theme.tokens.OudsSizeKeyToken
import com.orange.ouds.theme.tokens.OudsSpaceKeyToken

/** @suppress */
@InternalOudsApi
interface OudsListItemTokens {
    val borderRadiusCurrentIndicator: OudsBorderKeyToken.Radius
    val borderRadiusDefault: OudsBorderKeyToken.Radius
    val borderRadiusMedia: OudsBorderKeyToken.Radius
    val borderRadiusMediaRounded: OudsBorderKeyToken.Radius
    val borderRadiusRounded: OudsBorderKeyToken.Radius
    val borderWidthCurrentPage: OudsBorderKeyToken.Width
    val borderWidthDefault: OudsBorderKeyToken.Width
    val colorBgBadgeSafetyArea: OudsColorKeyToken
    val colorBgCurrentDisabled: OudsColorKeyToken
    val colorBgCurrentEnabled: OudsColorKeyToken
    val colorBgCurrentFocus: OudsColorKeyToken
    val colorBgCurrentHover: OudsColorKeyToken
    val colorBgCurrentPressed: OudsColorKeyToken
    val colorContentCurrentDisabled: OudsColorKeyToken
    val colorContentCurrentEnabled: OudsColorKeyToken
    val colorContentCurrentFocus: OudsColorKeyToken
    val colorContentCurrentHover: OudsColorKeyToken
    val colorContentCurrentPressed: OudsColorKeyToken
    val fontLetterSpacingAvatarInitialXlarge: Float
    val fontLineHeightAvatarInitialXlarge: Int
    val fontSizeAvatarInitialXlarge: Int
    val opacityCurrentDivider: OudsOpacityKeyToken
    val opacityCurrentIndicator: OudsOpacityKeyToken
    val sizeAssetLarge: Float
    val sizeAssetMedium: OudsSizeKeyToken.Icon
    val sizeAssetSmall: OudsSizeKeyToken.Icon
    val sizeAssetXlarge: Float
    val sizeControlIndicator: OudsSizeKeyToken.Icon
    val sizeCurrentIndicatorWidth: Float
    val sizeFlagHeight: OudsSizeKeyToken.Icon
    val sizeMaxWidth: Float
    val sizeMinHeightDefault: Float
    val sizeMinHeightSmall: OudsSizeKeyToken
    val sizeMinWidth: Float
    val spaceColumnGap: OudsSpaceKeyToken.ColumnGap
    val spacePaddingBlockBottomSlotListItemContainer: OudsSpaceKeyToken.PaddingBlock
    val spacePaddingBlockBottomSlotTextContainer: OudsSpaceKeyToken.PaddingBlock
    val spacePaddingBlockDefault: OudsSpaceKeyToken.PaddingBlock
    val spacePaddingBlockSmall: OudsSpaceKeyToken.PaddingBlock
    val spacePaddingBlockTopAlignmentTopCounterweightDefault: OudsSpaceKeyToken.PaddingBlock
    val spacePaddingBlockTopAlignmentTopCounterweightSmall: OudsSpaceKeyToken.PaddingBlock
    val spacePaddingBlockTopAlignmentTopTextContainerDefault: OudsSpaceKeyToken.PaddingBlock
    val spacePaddingBlockTopAlignmentTopTextContainerSmall: OudsSpaceKeyToken.PaddingBlock
    val spacePaddingBlockTopHelperText: OudsSpaceKeyToken.PaddingBlock
    val spacePaddingInline: OudsSpaceKeyToken.PaddingInline
    val spaceRowGap: OudsSpaceKeyToken.RowGap
}
