name: Demo app update
description: Propose a change in the Design Toolbox application
title: "[Design Toolbox]: "
labels: [ "📱 demo app", "🔍 triage" ]
assignees: [ "florentmaitre", "paulinea" ]
projects: [ "⚛️ [OUDS] Project" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve the Design Toolbox demo app!
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Take a couple minutes to help our maintainers work faster.
      options:
        - label: I have [searched the backlog](https://github.com/Orange-OpenSource/ouds-android/issues) for duplicate or closed feature requests.
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe your need in details. Which screens? Which tokens, components or modules?
    validations:
      required: true