name: Feature request
description: Suggest a new feature to be added to the backlog
labels: [ "🗳️ feature", "🔍 triage" ]
assignees: [ "florentmaitre", "paulinea" ]
projects: [ "⚛️ [OUDS] Project" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve OUDS Android!
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Take a couple minutes to help our maintainers work faster.
      options:
        - label: I have [searched the backlog](https://github.com/Orange-OpenSource/ouds-android/issues) for duplicate or closed issues.
          required: true
  - type: markdown
    attributes:
      value: |
        ### New feature description
  - type: textarea
    id: user
    attributes:
      label: As a
      placeholder: type of user / context of use
    validations:
      required: true
  - type: textarea
    id: need
    attributes:
      label: ... I want to
      placeholder: perform some task
    validations:
      required: true
  - type: textarea
    id: goal
    attributes:
      label: ... so that I can
      placeholder: achieve some goal
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation and context
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
  - type: textarea
    id: other
    attributes:
      label: Other
      description: Additional context
      placeholder: Add any other context about the problem here.
  - type: input
    id: contact
    attributes:
      label: Contact details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
