//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Orange brand tokens version 1.6.0
// Generated by Tokenator

package com.orange.ouds.theme.orange.tokens.components

import com.orange.ouds.theme.tokens.components.OudsTagTokens
import com.orange.ouds.theme.tokens.OudsBorderKeyToken
import com.orange.ouds.theme.tokens.OudsDimensionKeyToken
import com.orange.ouds.theme.tokens.OudsSizeKeyToken
import com.orange.ouds.theme.tokens.OudsSpaceKeyToken
import com.orange.ouds.tokens.raw.DimensionRawTokens

data class OrangeTagTokens(
    override val borderRadius: OudsBorderKeyToken.Radius = OudsBorderKeyToken.Radius.Pill,
    override val sizeAssetDefault: OudsSizeKeyToken.Icon = OudsSizeKeyToken.Icon.WithLabel.Medium.SizeSmall,
    override val sizeAssetSmall: OudsSizeKeyToken.Icon = OudsSizeKeyToken.Icon.WithLabel.Small.SizeSmall,
    override val sizeMinHeightDefault: Float = DimensionRawTokens.dimension400,
    override val sizeMinHeightInteractiveArea: OudsSizeKeyToken = OudsSizeKeyToken.MinInteractiveArea,
    override val sizeMinHeightSmall: Float = DimensionRawTokens.dimension300,
    override val sizeMinWidthDefault: Float = DimensionRawTokens.dimension600,
    override val sizeMinWidthSmall: OudsDimensionKeyToken = OudsDimensionKeyToken.Large,
    override val spaceColumnGapDefault: OudsSpaceKeyToken.ColumnGap = OudsSpaceKeyToken.ColumnGap.TwoExtraSmall,
    override val spaceColumnGapSmall: OudsSpaceKeyToken.ColumnGap = OudsSpaceKeyToken.ColumnGap.TwoExtraSmall,
    override val spaceInsetBulletDefault: Float = DimensionRawTokens.dimensionOutOfSystem75,
    override val spaceInsetBulletSmall: OudsSpaceKeyToken.Inset = OudsSpaceKeyToken.Inset.ThreeExtraSmall,
    override val spaceInsetIconDefault: OudsSpaceKeyToken.Inset = OudsSpaceKeyToken.Inset.FourExtraSmall,
    override val spaceInsetIconSmall: OudsSpaceKeyToken.Inset = OudsSpaceKeyToken.Inset.None,
    override val spaceInsetLoaderDefault: OudsSpaceKeyToken.Inset = OudsSpaceKeyToken.Inset.ThreeExtraSmall,
    override val spaceInsetLoaderSmall: OudsSpaceKeyToken.Inset = OudsSpaceKeyToken.Inset.FourExtraSmall,
    override val spacePaddingBlockDefault: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.TwoExtraSmall,
    override val spacePaddingBlockSmall: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.ThreeExtraSmall,
    override val spacePaddingInlineAssetDefault: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.ExtraSmall,
    override val spacePaddingInlineAssetSmall: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.TwoExtraSmall,
    override val spacePaddingInlineDefault: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.Medium,
    override val spacePaddingInlineSmall: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.Small
) : OudsTagTokens
