//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Orange brand tokens version 2.7.0
// Generated by Tokenator

package com.orange.ouds.theme.orange.tokens.components

import com.orange.ouds.theme.tokens.OudsColorKeyToken
import com.orange.ouds.theme.tokens.OudsSpaceKeyToken
import com.orange.ouds.theme.tokens.components.OudsTypographyTokens

internal data class OrangeTypographyTokens(
    override val colorContentMarker: OudsColorKeyToken = OudsColorKeyToken.Content.BrandPrimary,
    override val headingLargeMarker: Boolean = true,
    @Deprecated("") override val spacePaddingBlockBottomHeadingLargeMarker: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.FourExtraSmall,
    @Deprecated("") override val spacePaddingBlockTopHeadingLargeMarker: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.ThreeExtraSmall
) : OudsTypographyTokens
