//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Orange brand tokens version 2.0.1
// Generated by Tokenator

package com.orange.ouds.theme.orange.tokens.components

import com.orange.ouds.theme.tokens.components.OudsRadioButtonTokens
import com.orange.ouds.theme.tokens.OudsBorderKeyToken
import com.orange.ouds.theme.tokens.OudsSizeKeyToken

data class OrangeRadioButtonTokens(
    override val borderRadius: OudsBorderKeyToken.Radius = OudsBorderKeyToken.Radius.Pill,
    override val borderWidthSelected: OudsBorderKeyToken.Width = OudsBorderKeyToken.Width.Medium,
    override val borderWidthSelectedFocus: OudsBorderKeyToken.Width = OudsBorderKeyToken.Width.Medium,
    override val borderWidthSelectedHover: OudsBorderKeyToken.Width = OudsBorderKeyToken.Width.Medium,
    override val borderWidthSelectedPressed: OudsBorderKeyToken.Width = OudsBorderKeyToken.Width.Medium,
    override val borderWidthUnselected: OudsBorderKeyToken.Width = OudsBorderKeyToken.Width.Thin,
    override val borderWidthUnselectedFocus: OudsBorderKeyToken.Width = OudsBorderKeyToken.Width.Medium,
    override val borderWidthUnselectedHover: OudsBorderKeyToken.Width = OudsBorderKeyToken.Width.Medium,
    override val borderWidthUnselectedPressed: OudsBorderKeyToken.Width = OudsBorderKeyToken.Width.Medium,
    override val sizeIndicator: OudsSizeKeyToken.Icon = OudsSizeKeyToken.Icon.WithLabel.Large.SizeExtraSmall,
    override val sizeMaxHeight: OudsSizeKeyToken = OudsSizeKeyToken.MinInteractiveArea,
    override val sizeMinHeight: OudsSizeKeyToken = OudsSizeKeyToken.MinInteractiveArea,
    override val sizeMinWidth: OudsSizeKeyToken = OudsSizeKeyToken.MinInteractiveArea
) : OudsRadioButtonTokens
