//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Orange brand tokens version 2.5.0
// Generated by Tokenator

package com.orange.ouds.theme.orange.tokens.components

import com.orange.ouds.theme.tokens.OudsBorderKeyToken
import com.orange.ouds.theme.tokens.OudsColorKeyToken
import com.orange.ouds.theme.tokens.OudsLightDarkColorKeyToken
import com.orange.ouds.theme.tokens.OudsSizeKeyToken
import com.orange.ouds.theme.tokens.OudsSpaceKeyToken
import com.orange.ouds.theme.tokens.components.OudsButtonTokens

internal data class OrangeButtonTokens(
    override val borderRadiusAiIconOnly: OudsBorderKeyToken.Radius = OudsBorderKeyToken.Radius.Pill,
    override val borderRadiusDefault: OudsBorderKeyToken.Radius = OudsBorderKeyToken.Radius.Default,
    override val borderRadiusRounded: OudsBorderKeyToken.Radius = OudsBorderKeyToken.Radius.Medium,
    override val borderRadiusSocial: OudsBorderKeyToken.Radius = OudsBorderKeyToken.Radius.Pill,
    override val borderWidthAi: OudsBorderKeyToken.Width = OudsBorderKeyToken.Width.Default,
    override val borderWidthAiInteraction: OudsBorderKeyToken.Width = OudsBorderKeyToken.Width.Medium,
    override val borderWidthDefault: OudsBorderKeyToken.Width = OudsBorderKeyToken.Width.Default,
    override val borderWidthDefaultInteraction: OudsBorderKeyToken.Width = OudsBorderKeyToken.Width.Medium,
    override val borderWidthDefaultInteractionMono: OudsBorderKeyToken.Width = OudsBorderKeyToken.Width.None,
    override val colorBgAiDisabled: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    override val colorBgAiEnabled: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    override val colorBgAiFocus: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    override val colorBgAiHover: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    override val colorBgAiLoading: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    override val colorBgAiPressed: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    override val colorBgBrandEnabled: OudsColorKeyToken = OudsColorKeyToken.Surface.Brand.Primary,
    override val colorBgBrandFocus: OudsColorKeyToken = OudsColorKeyToken.Action.Focus,
    override val colorBgBrandHover: OudsColorKeyToken = OudsColorKeyToken.Action.Hover,
    override val colorBgBrandLoading: OudsColorKeyToken = OudsLightDarkColorKeyToken(OudsColorKeyToken.Repository.Neutral.Emphasized.Black, OudsColorKeyToken.Repository.Neutral.Muted.Lower),
    override val colorBgBrandPressed: OudsColorKeyToken = OudsLightDarkColorKeyToken(OudsColorKeyToken.Repository.Neutral.Emphasized.Black, OudsColorKeyToken.Repository.Neutral.Muted.Lower),
    override val colorBgDefaultDisabled: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    override val colorBgDefaultEnabled: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    override val colorBgDefaultFocus: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    override val colorBgDefaultHover: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    override val colorBgDefaultLoading: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    override val colorBgDefaultPressed: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    override val colorBgMinimalFocus: OudsColorKeyToken = OudsColorKeyToken.Action.Support.Focus,
    override val colorBgMinimalHover: OudsColorKeyToken = OudsColorKeyToken.Action.Support.Hover,
    override val colorBgMinimalPressed: OudsColorKeyToken = OudsColorKeyToken.Action.Support.Pressed,
    override val colorBorderAiDisabled: OudsColorKeyToken = OudsColorKeyToken.Action.Disabled,
    override val colorBorderAiEnabled: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    override val colorBorderAiFocus: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    override val colorBorderAiHover: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    override val colorBorderAiLoading: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    override val colorBorderAiPressed: OudsColorKeyToken = OudsColorKeyToken.Opacity.Transparent,
    override val colorBorderDefaultDisabled: OudsColorKeyToken = OudsColorKeyToken.Action.Disabled,
    override val colorBorderDefaultEnabled: OudsColorKeyToken = OudsColorKeyToken.Action.Enabled,
    override val colorBorderDefaultFocus: OudsColorKeyToken = OudsColorKeyToken.Action.Focus,
    override val colorBorderDefaultHover: OudsColorKeyToken = OudsColorKeyToken.Action.Hover,
    override val colorBorderDefaultLoading: OudsColorKeyToken = OudsColorKeyToken.Action.Loading,
    override val colorBorderDefaultPressed: OudsColorKeyToken = OudsColorKeyToken.Action.Pressed,
    override val colorContentAiDisabled: OudsColorKeyToken = OudsColorKeyToken.Action.Disabled,
    override val colorContentAiEnabled: OudsColorKeyToken = OudsColorKeyToken.Action.Enabled,
    override val colorContentAiFocus: OudsColorKeyToken = OudsColorKeyToken.Action.Focus,
    override val colorContentAiHover: OudsColorKeyToken = OudsColorKeyToken.Action.Hover,
    override val colorContentAiLoading: OudsColorKeyToken = OudsColorKeyToken.Action.Loading,
    override val colorContentAiPressed: OudsColorKeyToken = OudsColorKeyToken.Action.Pressed,
    override val colorContentBrandEnabled: OudsColorKeyToken = OudsColorKeyToken.Content.OnBrand.Primary,
    override val colorContentBrandFocus: OudsColorKeyToken = OudsColorKeyToken.Content.OnAction.Focus,
    override val colorContentBrandHover: OudsColorKeyToken = OudsColorKeyToken.Content.OnAction.Hover,
    override val colorContentBrandLoading: OudsColorKeyToken = OudsLightDarkColorKeyToken(OudsColorKeyToken.Repository.Neutral.Muted.White, OudsColorKeyToken.Repository.Neutral.Emphasized.Black),
    override val colorContentBrandPressed: OudsColorKeyToken = OudsLightDarkColorKeyToken(OudsColorKeyToken.Repository.Neutral.Muted.White, OudsColorKeyToken.Repository.Neutral.Emphasized.Black),
    override val colorContentDefaultDisabled: OudsColorKeyToken = OudsColorKeyToken.Action.Disabled,
    override val colorContentDefaultEnabled: OudsColorKeyToken = OudsColorKeyToken.Action.Enabled,
    override val colorContentDefaultFocus: OudsColorKeyToken = OudsColorKeyToken.Action.Focus,
    override val colorContentDefaultHover: OudsColorKeyToken = OudsColorKeyToken.Action.Hover,
    override val colorContentDefaultLoading: OudsColorKeyToken = OudsColorKeyToken.Action.Loading,
    override val colorContentDefaultPressed: OudsColorKeyToken = OudsColorKeyToken.Action.Pressed,
    override val colorContentMinimalDisabled: OudsColorKeyToken = OudsColorKeyToken.Action.Disabled,
    override val colorContentMinimalEnabled: OudsColorKeyToken = OudsColorKeyToken.Action.Enabled,
    override val colorContentMinimalFocus: OudsColorKeyToken = OudsColorKeyToken.Action.Focus,
    override val colorContentMinimalHover: OudsColorKeyToken = OudsColorKeyToken.Action.Hover,
    override val colorContentMinimalLoading: OudsColorKeyToken = OudsColorKeyToken.Content.Default,
    override val colorContentMinimalPressed: OudsColorKeyToken = OudsColorKeyToken.Action.Pressed,
    override val sizeIconDefault: OudsSizeKeyToken.Icon = OudsSizeKeyToken.Icon.WithLabel.Large.SizeExtraSmall,
    override val sizeIconOnlyDefault: OudsSizeKeyToken.Icon = OudsSizeKeyToken.Icon.WithLabel.Large.SizeSmall,
    override val sizeIconOnlySmall: OudsSizeKeyToken.Icon = OudsSizeKeyToken.Icon.WithLabel.Large.SizeExtraSmall,
    override val sizeIconSmall: OudsSizeKeyToken.Icon = OudsSizeKeyToken.Icon.WithLabel.Medium.SizeSmall,
    @Deprecated("")
    override val sizeLoader: OudsSizeKeyToken.Icon = OudsSizeKeyToken.Icon.WithLabel.Large.SizeExtraSmall,
    override val sizeMaxWidthHeightIconOnlyDefault: OudsSizeKeyToken = OudsSizeKeyToken.MinInteractiveAreaDefault,
    override val sizeMaxWidthHeightIconOnlySmall: OudsSizeKeyToken = OudsSizeKeyToken.MinInteractiveAreaSmall,
    override val sizeMinHeightDefault: OudsSizeKeyToken = OudsSizeKeyToken.MinInteractiveAreaDefault,
    override val sizeMinHeightSmall: OudsSizeKeyToken = OudsSizeKeyToken.MinInteractiveAreaSmall,
    override val sizeMinWidthDefault: OudsSizeKeyToken = OudsSizeKeyToken.MinInteractiveAreaDefault,
    override val sizeMinWidthSmall: OudsSizeKeyToken = OudsSizeKeyToken.MinInteractiveAreaSmall,
    override val sizeProgressIndicatorDefault: OudsSizeKeyToken.Icon = OudsSizeKeyToken.Icon.WithLabel.Large.SizeExtraSmall,
    override val sizeProgressIndicatorSmall: OudsSizeKeyToken.Icon = OudsSizeKeyToken.Icon.WithLabel.Medium.SizeSmall,
    override val spaceColumnGapChevronDefault: OudsSpaceKeyToken.ColumnGap = OudsSpaceKeyToken.ColumnGap.ExtraSmall,
    override val spaceColumnGapChevronSmall: OudsSpaceKeyToken.ColumnGap = OudsSpaceKeyToken.ColumnGap.TwoExtraSmall,
    override val spaceColumnGapIconChevronDefault: OudsSpaceKeyToken.ColumnGap = OudsSpaceKeyToken.ColumnGap.TwoExtraSmall,
    override val spaceColumnGapIconChevronSmall: OudsSpaceKeyToken.ColumnGap = OudsSpaceKeyToken.ColumnGap.ThreeExtraSmall,
    override val spaceColumnGapIconDefault: OudsSpaceKeyToken.ColumnGap = OudsSpaceKeyToken.ColumnGap.Small,
    override val spaceColumnGapIconSmall: OudsSpaceKeyToken.ColumnGap = OudsSpaceKeyToken.ColumnGap.ExtraSmall,
    override val spaceInsetIconOnlyDefault: OudsSpaceKeyToken.Inset = OudsSpaceKeyToken.Inset.Medium,
    override val spaceInsetIconOnlySmall: OudsSpaceKeyToken.Inset = OudsSpaceKeyToken.Inset.Small,
    override val spaceInsetProgressIndicartorOnlyDefault: OudsSpaceKeyToken.Inset = OudsSpaceKeyToken.Inset.FourExtraSmall,
    override val spaceInsetProgressIndicartorOnlySmall: OudsSpaceKeyToken.Inset = OudsSpaceKeyToken.Inset.FourExtraSmall,
    override val spacePaddingBlockDefault: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.Medium,
    override val spacePaddingBlockSmall: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.Small,
    override val spacePaddingInlineChevronEndDefault: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.Large,
    override val spacePaddingInlineChevronEndSmall: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.Medium,
    override val spacePaddingInlineChevronStartDefault: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.Large,
    override val spacePaddingInlineChevronStartSmall: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.Medium,
    override val spacePaddingInlineEndIconStartDefault: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.ThreeExtraLarge,
    override val spacePaddingInlineEndIconStartSmall: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.TwoExtraLarge,
    override val spacePaddingInlineIconNoneDefault: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.FourExtraLarge,
    override val spacePaddingInlineIconNoneSmall: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.TwoExtraLarge,
    override val spacePaddingInlineIconStartDefault: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.ExtraLarge,
    override val spacePaddingInlineIconStartSmall: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.Large,
    override val spacePaddingInlineStartIconEndDefault: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.ThreeExtraLarge,
    override val spacePaddingInlineStartIconEndSmall: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.TwoExtraLarge
) : OudsButtonTokens
