//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Tokens version 1.1.0
// Generated by Tokenator

package com.orange.ouds.tokens.global.raw

object GridRawTokens {
  const val gridWidth100 = 360
  const val gridWidth200 = 390
  const val gridWidth300 = 480
  const val gridWidth400 = 768
  const val gridWidth500 = 1024
  const val gridWidth600 = 1440
  const val gridWidth700 = 1680
  const val gridWidth800 = 1920
  const val gridMinWidth100 = 1
  const val gridMinWidth200 = 390
  const val gridMinWidth300 = 480
  const val gridMinWidth400 = 736
  const val gridMinWidth500 = 1024
  const val gridMinWidth600 = 1320
  const val gridMinWidth700 = 1640
  const val gridMinWidth800 = 1880
  const val gridMinWidthExtraCompact = 320
  const val gridMinWidthCompact = 390
  const val gridMinWidthMedium = 600
  const val gridMaxWidth100 = 389
  const val gridMaxWidth200 = 479
  const val gridMaxWidth300 = 735
  const val gridMaxWidth400 = 1023
  const val gridMaxWidth500 = 1319
  const val gridMaxWidth600 = 1639
  const val gridMaxWidth650 = 1680
  const val gridMaxWidth700 = 1879
  const val gridMaxWidth800 = 1920
  const val gridMaxWidthExtraCompact = 389
  const val gridMaxWidthCompact = 599
  const val gridMaxWidthMedium = 1200
  const val gridMargin100 = DimensionRawTokens.dimensionBase * 4 // 16
  const val gridMargin300 = DimensionRawTokens.dimensionBase * 6 // 24
  const val gridMargin400 = DimensionRawTokens.dimensionBase * 7 // 28
  const val gridMargin500 = DimensionRawTokens.dimensionBase * 8 // 32
  const val gridMargin600 = DimensionRawTokens.dimensionBase * 9 // 36
  const val gridMargin700 = DimensionRawTokens.dimensionBase * 10 // 40
  const val gridMargin1000 = DimensionRawTokens.dimensionBase * 13 // 52
  const val gridMargin1100 = DimensionRawTokens.dimensionBase * 14 // 56
  const val gridMargin1700 = DimensionRawTokens.dimensionBase * 20 // 80
  const val gridMargin2500 = DimensionRawTokens.dimensionBase * 28 // 112
  const val gridColumnGap10 = DimensionRawTokens.dimensionBase * 0.25f // 1
  const val gridColumnGap100 = DimensionRawTokens.dimensionBase * 2f // 8
  const val gridColumnGap200 = DimensionRawTokens.dimensionBase * 4f // 16
  const val gridColumnGap300 = DimensionRawTokens.dimensionBase * 5f // 20
  const val gridColumnGap400 = DimensionRawTokens.dimensionBase * 6f // 24
  const val gridColumnGap600 = DimensionRawTokens.dimensionBase * 8f // 32
  const val gridColumnGap800 = DimensionRawTokens.dimensionBase * 10f // 40
  const val gridColumnCount100 = 1
  const val gridColumnCount200 = 2
  const val gridColumnCount400 = 4
  const val gridColumnCount600 = 6
  const val gridColumnCount800 = 8
  const val gridColumnCount1000 = 10
  const val gridColumnCount1200 = 12
}
