//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Tokens version 0.6.0
// Generated by Tokenator

package com.orange.ouds.theme.tokens.semantic

import androidx.compose.ui.graphics.Color

interface OudsColorSurfaceSemanticTokens {
    val surfaceBrandPrimaryLight: Color
    val surfaceBrandPrimaryDark: Color
    val surfaceStatusAccentEmphasizedLight: Color
    val surfaceStatusAccentMutedLight: Color
    val surfaceStatusAccentEmphasizedDark: Color
    val surfaceStatusAccentMutedDark: Color
    val surfaceStatusInfoEmphasizedLight: Color
    val surfaceStatusInfoMutedLight: Color
    val surfaceStatusInfoEmphasizedDark: Color
    val surfaceStatusInfoMutedDark: Color
    val surfaceStatusNegativeEmphasizedLight: Color
    val surfaceStatusNegativeMutedLight: Color
    val surfaceStatusNegativeEmphasizedDark: Color
    val surfaceStatusNegativeMutedDark: Color
    val surfaceStatusNeutralEmphasizedLight: Color
    val surfaceStatusNeutralMutedLight: Color
    val surfaceStatusNeutralEmphasizedDark: Color
    val surfaceStatusNeutralMutedDark: Color
    val surfaceStatusPositiveEmphasizedLight: Color
    val surfaceStatusPositiveMutedLight: Color
    val surfaceStatusPositiveEmphasizedDark: Color
    val surfaceStatusPositiveMutedDark: Color
    val surfaceStatusWarningEmphasizedLight: Color
    val surfaceStatusWarningMutedLight: Color
    val surfaceStatusWarningEmphasizedDark: Color
    val surfaceStatusWarningMutedDark: Color
}
