//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

package com.orange.ouds.theme.tokens.semantic

import com.orange.ouds.tokens.global.raw.DimensionRawTokens

data class OudsSizeSemanticTokens(
  val iconDecorativeMedium: Float = DimensionRawTokens.dimension500,
  val iconDecorativeShort: Float = DimensionRawTokens.dimension400,
  val iconDecorativeShorter: Float = DimensionRawTokens.dimension300,
  val iconDecorativeShortest: Float = DimensionRawTokens.dimension200,
  val iconDecorativeTall: Float = DimensionRawTokens.dimension600,
  val iconDecorativeTaller: Float = DimensionRawTokens.dimension700,
  val iconDecorativeTallest: Float = DimensionRawTokens.dimension900,
  val iconWithBodyLargeSizeMediumMobile: Float = DimensionRawTokens.dimension300,
  val iconWithBodyLargeSizeMediumTablet: Float = DimensionRawTokens.dimension300,
  val iconWithBodyLargeSizeShortMobile: Float = DimensionRawTokens.dimension250,
  val iconWithBodyLargeSizeShortTablet: Float = DimensionRawTokens.dimension250,
  val iconWithBodyLargeSizeTallMobile: Float = DimensionRawTokens.dimension350,
  val iconWithBodyLargeSizeTallTablet: Float = DimensionRawTokens.dimension350,
  val iconWithBodyMediumSizeMediumMobile: Float = DimensionRawTokens.dimension250,
  val iconWithBodyMediumSizeMediumTablet: Float = DimensionRawTokens.dimension250,
  val iconWithBodyMediumSizeShortMobile: Float = DimensionRawTokens.dimension200,
  val iconWithBodyMediumSizeShortTablet: Float = DimensionRawTokens.dimension200,
  val iconWithBodyMediumSizeTallMobile: Float = DimensionRawTokens.dimension300,
  val iconWithBodyMediumSizeTallTablet: Float = DimensionRawTokens.dimension300,
  val iconWithBodySmallSizeMediumMobile: Float = DimensionRawTokens.dimension200,
  val iconWithBodySmallSizeMediumTablet: Float = DimensionRawTokens.dimension200,
  val iconWithBodySmallSizeShortMobile: Float = DimensionRawTokens.dimension150,
  val iconWithBodySmallSizeShortTablet: Float = DimensionRawTokens.dimension150,
  val iconWithBodySmallSizeTallMobile: Float = DimensionRawTokens.dimension250,
  val iconWithBodySmallSizeTallTablet: Float = DimensionRawTokens.dimension250,
  val iconWithHeadingLargeSizeMediumMobile: Float = DimensionRawTokens.dimension550,
  val iconWithHeadingLargeSizeMediumTablet: Float = DimensionRawTokens.dimension600,
  val iconWithHeadingLargeSizeShortMobile: Float = DimensionRawTokens.dimension500,
  val iconWithHeadingLargeSizeShortTablet: Float = DimensionRawTokens.dimension550,
  val iconWithHeadingLargeSizeTallMobile: Float = DimensionRawTokens.dimension600,
  val iconWithHeadingLargeSizeTallTablet: Float = DimensionRawTokens.dimension650,
  val iconWithHeadingMediumSizeMediumMobile: Float = DimensionRawTokens.dimension500,
  val iconWithHeadingMediumSizeMediumTablet: Float = DimensionRawTokens.dimension550,
  val iconWithHeadingMediumSizeShortMobile: Float = DimensionRawTokens.dimension400,
  val iconWithHeadingMediumSizeShortTablet: Float = DimensionRawTokens.dimension500,
  val iconWithHeadingMediumSizeTallMobile: Float = DimensionRawTokens.dimension550,
  val iconWithHeadingMediumSizeTallTablet: Float = DimensionRawTokens.dimension600,
  val iconWithHeadingSmallSizeMediumMobile: Float = DimensionRawTokens.dimension500,
  val iconWithHeadingSmallSizeMediumTablet: Float = DimensionRawTokens.dimension500,
  val iconWithHeadingSmallSizeShortMobile: Float = DimensionRawTokens.dimension400,
  val iconWithHeadingSmallSizeShortTablet: Float = DimensionRawTokens.dimension400,
  val iconWithHeadingSmallSizeTallMobile: Float = DimensionRawTokens.dimension550,
  val iconWithHeadingSmallSizeTallTablet: Float = DimensionRawTokens.dimension550,
  val iconWithHeadingXlargeSizeMediumMobile: Float = DimensionRawTokens.dimension600,
  val iconWithHeadingXlargeSizeMediumTablet: Float = DimensionRawTokens.dimension700,
  val iconWithHeadingXlargeSizeShortMobile: Float = DimensionRawTokens.dimension550,
  val iconWithHeadingXlargeSizeShortTablet: Float = DimensionRawTokens.dimension650,
  val iconWithHeadingXlargeSizeTallMobile: Float = DimensionRawTokens.dimension650,
  val iconWithHeadingXlargeSizeTallTablet: Float = DimensionRawTokens.dimension800,
  val iconWithLabelLargeSizeMedium: Float = DimensionRawTokens.dimension350,
  val iconWithLabelLargeSizeShort: Float = DimensionRawTokens.dimension300,
  val iconWithLabelLargeSizeShorter: Float = DimensionRawTokens.dimension250,
  val iconWithLabelLargeSizeTall: Float = DimensionRawTokens.dimension400,
  val iconWithLabelLargeSizeTaller: Float = DimensionRawTokens.dimension550,
  val iconWithLabelMediumSizeMedium: Float = DimensionRawTokens.dimension250,
  val iconWithLabelMediumSizeShort: Float = DimensionRawTokens.dimension200,
  val iconWithLabelMediumSizeTall: Float = DimensionRawTokens.dimension300,
  val iconWithLabelSmallSizeMedium: Float = DimensionRawTokens.dimension200,
  val iconWithLabelSmallSizeShort: Float = DimensionRawTokens.dimension150,
  val iconWithLabelSmallSizeTall: Float = DimensionRawTokens.dimension250,
  val iconWithLabelXlargeSizeMedium: Float = DimensionRawTokens.dimension500,
  val iconWithLabelXlargeSizeShort: Float = DimensionRawTokens.dimension400,
  val iconWithLabelXlargeSizeTall: Float = DimensionRawTokens.dimension550,
  val maxWidthTypeBodyLargeMobile: Float = DimensionRawTokens.dimension6000,
  val maxWidthTypeBodyLargeTablet: Float = DimensionRawTokens.dimension6000,
  val maxWidthTypeBodyMediumMobile: Float = DimensionRawTokens.dimension6000,
  val maxWidthTypeBodyMediumTablet: Float = DimensionRawTokens.dimension6000,
  val maxWidthTypeBodySmallMobile: Float = DimensionRawTokens.dimension6000,
  val maxWidthTypeBodySmallTablet: Float = DimensionRawTokens.dimension6000,
  val maxWidthTypeDisplayLargeMobile: Float = DimensionRawTokens.dimension9000,
  val maxWidthTypeDisplayLargeTablet: Float = DimensionRawTokens.dimension9000,
  val maxWidthTypeDisplayMediumMobile: Float = DimensionRawTokens.dimension9000,
  val maxWidthTypeDisplayMediumTablet: Float = DimensionRawTokens.dimension9000,
  val maxWidthTypeDisplaySmallMobile: Float = DimensionRawTokens.dimension9000,
  val maxWidthTypeDisplaySmallTablet: Float = DimensionRawTokens.dimension9000,
  val maxWidthTypeHeadingLargeMobile: Float = DimensionRawTokens.dimension9000,
  val maxWidthTypeHeadingLargeTablet: Float = DimensionRawTokens.dimension9000,
  val maxWidthTypeHeadingMediumMobile: Float = DimensionRawTokens.dimension9000,
  val maxWidthTypeHeadingMediumTablet: Float = DimensionRawTokens.dimension9000,
  val maxWidthTypeHeadingSmallMobile: Float = DimensionRawTokens.dimension6000,
  val maxWidthTypeHeadingSmallTablet: Float = DimensionRawTokens.dimension6000,
  val maxWidthTypeHeadingXlargeMobile: Float = DimensionRawTokens.dimension9000,
  val maxWidthTypeHeadingXlargeTablet: Float = DimensionRawTokens.dimension9000
)
