//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Tokens version 1.1.0
// Generated by Tokenator

package com.orange.ouds.theme.tokens.semantic

import androidx.compose.ui.graphics.Color

interface OudsColorRepositorySemanticTokens {
    val repositoryAccentDefault: Color
    val repositoryAccentHigh: Color
    val repositoryAccentHigher: Color
    val repositoryAccentHighest: Color
    val repositoryAccentLow: Color
    val repositoryAccentLower: Color
    val repositoryAccentLowest: Color
    val repositoryInfoDefault: Color
    val repositoryInfoHigh: Color
    val repositoryInfoHigher: Color
    val repositoryInfoHighest: Color
    val repositoryInfoLow: Color
    val repositoryInfoLower: Color
    val repositoryInfoLowest: Color
    val repositoryNegativeDefault: Color
    val repositoryNegativeHigh: Color
    val repositoryNegativeHigher: Color
    val repositoryNegativeHighest: Color
    val repositoryNegativeLow: Color
    val repositoryNegativeLower: Color
    val repositoryNegativeLowest: Color
    val repositoryNeutralEmphasizedBlack: Color
    val repositoryNeutralEmphasizedHigh: Color
    val repositoryNeutralEmphasizedHigher: Color
    val repositoryNeutralEmphasizedHighest: Color
    val repositoryNeutralEmphasizedLow: Color
    val repositoryNeutralEmphasizedLower: Color
    val repositoryNeutralEmphasizedLowest: Color
    val repositoryNeutralEmphasizedMedium: Color
    val repositoryNeutralMutedHigh: Color
    val repositoryNeutralMutedHigher: Color
    val repositoryNeutralMutedHighest: Color
    val repositoryNeutralMutedLow: Color
    val repositoryNeutralMutedLower: Color
    val repositoryNeutralMutedLowest: Color
    val repositoryNeutralMutedMedium: Color
    val repositoryNeutralMutedWhite: Color
    val repositoryOpacityBlackHigh: Color
    val repositoryOpacityBlackHigher: Color
    val repositoryOpacityBlackHighest: Color
    val repositoryOpacityBlackLow: Color
    val repositoryOpacityBlackLower: Color
    val repositoryOpacityBlackLowest: Color
    val repositoryOpacityBlackMedium: Color
    val repositoryOpacityBlackMediumHigh: Color
    val repositoryOpacityBlackMediumLow: Color
    val repositoryOpacityBlackTransparent: Color
    val repositoryOpacityInfo: Color
    val repositoryOpacityNegative: Color
    val repositoryOpacityPositive: Color
    val repositoryOpacityPrimaryHigh: Color
    val repositoryOpacityPrimaryHigher: Color
    val repositoryOpacityPrimaryHighest: Color
    val repositoryOpacityPrimaryLow: Color
    val repositoryOpacityPrimaryLower: Color
    val repositoryOpacityPrimaryLowest: Color
    val repositoryOpacityPrimaryMedium: Color
    val repositoryOpacityPrimaryTransparent: Color
    val repositoryOpacityWarning: Color
    val repositoryOpacityWhiteHigh: Color
    val repositoryOpacityWhiteHigher: Color
    val repositoryOpacityWhiteHighest: Color
    val repositoryOpacityWhiteLow: Color
    val repositoryOpacityWhiteLower: Color
    val repositoryOpacityWhiteLowest: Color
    val repositoryOpacityWhiteMedium: Color
    val repositoryOpacityWhiteMediumLow: Color
    val repositoryOpacityWhiteTransparent: Color
    val repositoryPositiveDefault: Color
    val repositoryPositiveHigh: Color
    val repositoryPositiveHigher: Color
    val repositoryPositiveHighest: Color
    val repositoryPositiveLow: Color
    val repositoryPositiveLower: Color
    val repositoryPositiveLowest: Color
    val repositoryPrimaryDefault: Color
    val repositoryPrimaryHigh: Color
    val repositoryPrimaryHigher: Color
    val repositoryPrimaryHighest: Color
    val repositoryPrimaryLow: Color
    val repositoryPrimaryLower: Color
    val repositoryPrimaryLowest: Color
    val repositorySecondaryDefault: Color
    val repositorySecondaryHigh: Color
    val repositorySecondaryHigher: Color
    val repositorySecondaryHighest: Color
    val repositorySecondaryLow: Color
    val repositorySecondaryLower: Color
    val repositorySecondaryLowest: Color
    val repositoryTertiaryDefault: Color
    val repositoryTertiaryHigh: Color
    val repositoryTertiaryHigher: Color
    val repositoryTertiaryHighest: Color
    val repositoryTertiaryLow: Color
    val repositoryTertiaryLower: Color
    val repositoryTertiaryLowest: Color
    val repositoryWarningDefault: Color
    val repositoryWarningHigh: Color
    val repositoryWarningHigher: Color
    val repositoryWarningHighest: Color
    val repositoryWarningLow: Color
    val repositoryWarningLower: Color
    val repositoryWarningLowest: Color
}
