/*
 * Software Name: OUDS Android
 * SPDX-FileCopyrightText: Copyright (c) Orange SA
 * SPDX-License-Identifier: MIT
 *
 * This software is distributed under the MIT license,
 * the text of which is available at https://opensource.org/license/MIT/
 * or see the "LICENSE" file for more details.
 *
 * Software description: Android library of reusable graphical components
 */

package com.orange.ouds.theme.tokens.semantic

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import com.orange.ouds.theme.OudsColors

class OudsColorTokens(
    var primary: OudsColorTokenValue,
    var onPrimary: OudsColorTokenValue,
    var primaryContainer: OudsColorTokenValue,
    var onPrimaryContainer: OudsColorTokenValue,
    var inversePrimary: OudsColorTokenValue,
    var secondary: OudsColorTokenValue,
    var onSecondary: OudsColorTokenValue,
    var secondaryContainer: OudsColorTokenValue,
    var onSecondaryContainer: OudsColorTokenValue,
    var tertiary: OudsColorTokenValue,
    var onTertiary: OudsColorTokenValue,
    var tertiaryContainer: OudsColorTokenValue,
    var onTertiaryContainer: OudsColorTokenValue,
    var background: OudsColorTokenValue,
    var onBackground: OudsColorTokenValue,
    var surface: OudsColorTokenValue,
    var onSurface: OudsColorTokenValue,
    var surfaceVariant: OudsColorTokenValue,
    var onSurfaceVariant: OudsColorTokenValue,
    var surfaceTint: OudsColorTokenValue,
    var inverseSurface: OudsColorTokenValue,
    var inverseOnSurface: OudsColorTokenValue,
    var error: OudsColorTokenValue,
    var onError: OudsColorTokenValue,
    var errorContainer: OudsColorTokenValue,
    var onErrorContainer: OudsColorTokenValue,
    var outline: OudsColorTokenValue,
    var outlineVariant: OudsColorTokenValue,
    var scrim: OudsColorTokenValue,
    var positive: OudsColorTokenValue,
    var onPositive: OudsColorTokenValue,
    var negative: OudsColorTokenValue,
    var onNegative: OudsColorTokenValue,
    var info: OudsColorTokenValue,
    var alert: OudsColorTokenValue,
) {

    val lightColors: OudsColors
        get() = OudsColors(
            primary = primary.light,
            onPrimary = onPrimary.light,
            primaryContainer = primaryContainer.light,
            onPrimaryContainer = onPrimaryContainer.light,
            inversePrimary = inversePrimary.light,
            secondary = secondary.light,
            onSecondary = onSecondary.light,
            secondaryContainer = secondaryContainer.light,
            onSecondaryContainer = onSecondaryContainer.light,
            tertiary = tertiary.light,
            onTertiary = onTertiary.light,
            tertiaryContainer = tertiaryContainer.light,
            onTertiaryContainer = onTertiaryContainer.light,
            background = background.light,
            onBackground = onBackground.light,
            surface = surface.light,
            onSurface = onSurface.light,
            surfaceVariant = surfaceVariant.light,
            onSurfaceVariant = onSurfaceVariant.light,
            surfaceTint = surfaceTint.light,
            inverseSurface = inverseSurface.light,
            inverseOnSurface = inverseOnSurface.light,
            error = error.light,
            onError = onError.light,
            errorContainer = errorContainer.light,
            onErrorContainer = onErrorContainer.light,
            outline = outline.light,
            outlineVariant = outlineVariant.light,
            scrim = scrim.light,
            positive = positive.light,
            onPositive = onPositive.light,
            negative = negative.light,
            onNegative = onNegative.light,
            info = info.light,
            alert = alert.light
        )

    val darkColors: OudsColors
        get() = OudsColors(
            primary = primary.dark,
            onPrimary = onPrimary.dark,
            primaryContainer = primaryContainer.dark,
            onPrimaryContainer = onPrimaryContainer.dark,
            inversePrimary = inversePrimary.dark,
            secondary = secondary.dark,
            onSecondary = onSecondary.dark,
            secondaryContainer = secondaryContainer.dark,
            onSecondaryContainer = onSecondaryContainer.dark,
            tertiary = tertiary.dark,
            onTertiary = onTertiary.dark,
            tertiaryContainer = tertiaryContainer.dark,
            onTertiaryContainer = onTertiaryContainer.dark,
            background = background.dark,
            onBackground = onBackground.dark,
            surface = surface.dark,
            onSurface = onSurface.dark,
            surfaceVariant = surfaceVariant.dark,
            onSurfaceVariant = onSurfaceVariant.dark,
            surfaceTint = surfaceTint.dark,
            inverseSurface = inverseSurface.dark,
            inverseOnSurface = inverseOnSurface.dark,
            error = error.dark,
            onError = onError.dark,
            errorContainer = errorContainer.dark,
            onErrorContainer = onErrorContainer.dark,
            outline = outline.dark,
            outlineVariant = outlineVariant.dark,
            scrim = scrim.dark,
            positive = positive.dark,
            onPositive = onPositive.dark,
            negative = negative.dark,
            onNegative = onNegative.dark,
            info = info.dark,
            alert = alert.dark
        )

    val materialLightColorScheme: ColorScheme
        get() = lightColorScheme(
            primary = primary.light,
            onPrimary = onPrimary.light,
            primaryContainer = primaryContainer.light,
            onPrimaryContainer = onPrimaryContainer.light,
            inversePrimary = inversePrimary.light,
            secondary = secondary.light,
            onSecondary = onSecondary.light,
            secondaryContainer = secondaryContainer.light,
            onSecondaryContainer = onSecondaryContainer.light,
            tertiary = tertiary.light,
            onTertiary = onTertiary.light,
            tertiaryContainer = tertiaryContainer.light,
            onTertiaryContainer = onTertiaryContainer.light,
            background = background.light,
            onBackground = onBackground.light,
            surface = surface.light,
            onSurface = onSurface.light,
            surfaceVariant = surfaceVariant.light,
            onSurfaceVariant = onSurfaceVariant.light,
            surfaceTint = surfaceTint.light,
            inverseSurface = inverseSurface.light,
            inverseOnSurface = inverseOnSurface.light,
            error = error.light,
            onError = onError.light,
            errorContainer = errorContainer.light,
            onErrorContainer = onErrorContainer.light,
            outline = outline.light,
            outlineVariant = outlineVariant.light,
            scrim = scrim.light,
        )

    val materialDarkColorScheme: ColorScheme
        get() = darkColorScheme(
            primary = primary.dark,
            onPrimary = onPrimary.dark,
            primaryContainer = primaryContainer.dark,
            onPrimaryContainer = onPrimaryContainer.dark,
            inversePrimary = inversePrimary.dark,
            secondary = secondary.dark,
            onSecondary = onSecondary.dark,
            secondaryContainer = secondaryContainer.dark,
            onSecondaryContainer = onSecondaryContainer.dark,
            tertiary = tertiary.dark,
            onTertiary = onTertiary.dark,
            tertiaryContainer = tertiaryContainer.dark,
            onTertiaryContainer = onTertiaryContainer.dark,
            background = background.dark,
            onBackground = onBackground.dark,
            surface = surface.dark,
            onSurface = onSurface.dark,
            surfaceVariant = surfaceVariant.dark,
            onSurfaceVariant = onSurfaceVariant.dark,
            surfaceTint = surfaceTint.dark,
            inverseSurface = inverseSurface.dark,
            inverseOnSurface = inverseOnSurface.dark,
            error = error.dark,
            onError = onError.dark,
            errorContainer = errorContainer.dark,
            onErrorContainer = onErrorContainer.dark,
            outline = outline.dark,
            outlineVariant = outlineVariant.dark,
            scrim = scrim.dark,
        )
}

data class OudsColorTokenValue(val light: Color, val dark: Color)

enum class OudsColorToken {
    Background,
    Error,
    ErrorContainer,
    InverseOnSurface,
    InversePrimary,
    InverseSurface,
    OnBackground,
    OnError,
    OnErrorContainer,
    OnPrimary,
    OnPrimaryContainer,
    OnSecondary,
    OnSecondaryContainer,
    OnSurface,
    OnSurfaceVariant,
    OnTertiary,
    OnTertiaryContainer,
    Outline,
    OutlineVariant,
    Primary,
    PrimaryContainer,
    Scrim,
    Secondary,
    SecondaryContainer,
    Surface,
    SurfaceTint,
    SurfaceVariant,
    Tertiary,
    TertiaryContainer,
}