//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Orange brand tokens version 2.4.0
// Generated by Tokenator

package com.orange.ouds.theme.tokens.semantic

import com.orange.ouds.foundation.InternalOudsApi

/** @suppress */
@InternalOudsApi
interface OudsSizeSemanticTokens {
    val iconDecorative2xlarge: Float
    val iconDecorative2xsmall: Float
    val iconDecorative3xsmall: Float
    val iconDecorative4xsmall: Float
    val iconDecorativeLarge: Float
    val iconDecorativeMedium: Float
    val iconDecorativeSmall: Float
    val iconDecorativeXlarge: Float
    val iconDecorativeXsmall: Float
    val iconWithBodyLargeSizeLargeMobile: Float
    val iconWithBodyLargeSizeLargeTablet: Float
    val iconWithBodyLargeSizeMediumMobile: Float
    val iconWithBodyLargeSizeMediumTablet: Float
    val iconWithBodyLargeSizeSmallMobile: Float
    val iconWithBodyLargeSizeSmallTablet: Float
    val iconWithBodyMediumSizeLargeMobile: Float
    val iconWithBodyMediumSizeLargeTablet: Float
    val iconWithBodyMediumSizeMediumMobile: Float
    val iconWithBodyMediumSizeMediumTablet: Float
    val iconWithBodyMediumSizeSmallMobile: Float
    val iconWithBodyMediumSizeSmallTablet: Float
    val iconWithBodySmallSizeLargeMobile: Float
    val iconWithBodySmallSizeLargeTablet: Float
    val iconWithBodySmallSizeMediumMobile: Float
    val iconWithBodySmallSizeMediumTablet: Float
    val iconWithBodySmallSizeSmallMobile: Float
    val iconWithBodySmallSizeSmallTablet: Float
    val iconWithHeadingLargeSizeLargeMobile: Float
    val iconWithHeadingLargeSizeLargeTablet: Float
    val iconWithHeadingLargeSizeMediumMobile: Float
    val iconWithHeadingLargeSizeMediumTablet: Float
    val iconWithHeadingLargeSizeSmallMobile: Float
    val iconWithHeadingLargeSizeSmallTablet: Float
    val iconWithHeadingMediumSizeLargeMobile: Float
    val iconWithHeadingMediumSizeLargeTablet: Float
    val iconWithHeadingMediumSizeMediumMobile: Float
    val iconWithHeadingMediumSizeMediumTablet: Float
    val iconWithHeadingMediumSizeSmallMobile: Float
    val iconWithHeadingMediumSizeSmallTablet: Float
    val iconWithHeadingSmallSizeLargeMobile: Float
    val iconWithHeadingSmallSizeLargeTablet: Float
    val iconWithHeadingSmallSizeMediumMobile: Float
    val iconWithHeadingSmallSizeMediumTablet: Float
    val iconWithHeadingSmallSizeSmallMobile: Float
    val iconWithHeadingSmallSizeSmallTablet: Float
    val iconWithHeadingXlargeSizeLargeMobile: Float
    val iconWithHeadingXlargeSizeLargeTablet: Float
    val iconWithHeadingXlargeSizeMediumMobile: Float
    val iconWithHeadingXlargeSizeMediumTablet: Float
    val iconWithHeadingXlargeSizeSmallMobile: Float
    val iconWithHeadingXlargeSizeSmallTablet: Float
    val iconWithLabelLargeSizeLarge: Float
    val iconWithLabelLargeSizeMedium: Float
    val iconWithLabelLargeSizeSmall: Float
    val iconWithLabelLargeSizeXlarge: Float
    val iconWithLabelLargeSizeXsmall: Float
    val iconWithLabelMediumSizeLarge: Float
    val iconWithLabelMediumSizeMedium: Float
    val iconWithLabelMediumSizeSmall: Float
    val iconWithLabelMediumSizeXsmall: Float
    val iconWithLabelSmallSizeLarge: Float
    val iconWithLabelSmallSizeMedium: Float
    val iconWithLabelSmallSizeSmall: Float
    val iconWithLabelSmallSizeXsmall: Float
    val iconWithLabelXlargeSizeLarge: Float
    val iconWithLabelXlargeSizeMedium: Float
    val iconWithLabelXlargeSizeSmall: Float
    val iconWithLabelXlargeSizeXsmall: Float
    val maxWidthBodyLargeMobile: Float
    val maxWidthBodyLargeTablet: Float
    val maxWidthBodyMediumMobile: Float
    val maxWidthBodyMediumTablet: Float
    val maxWidthBodySmallMobile: Float
    val maxWidthBodySmallTablet: Float
    val maxWidthDisplayLargeMobile: Float
    val maxWidthDisplayLargeTablet: Float
    val maxWidthDisplayMediumMobile: Float
    val maxWidthDisplayMediumTablet: Float
    val maxWidthDisplaySmallMobile: Float
    val maxWidthDisplaySmallTablet: Float
    val maxWidthHeadingLargeMobile: Float
    val maxWidthHeadingLargeTablet: Float
    val maxWidthHeadingMediumMobile: Float
    val maxWidthHeadingMediumTablet: Float
    val maxWidthHeadingSmallMobile: Float
    val maxWidthHeadingSmallTablet: Float
    val maxWidthHeadingXlargeMobile: Float
    val maxWidthHeadingXlargeTablet: Float
    val maxWidthLabelLargeMobile: Float
    val maxWidthLabelLargeTablet: Float
    val maxWidthLabelMediumMobile: Float
    val maxWidthLabelMediumTablet: Float
    val maxWidthLabelSmallMobile: Float
    val maxWidthLabelSmallTablet: Float
    val maxWidthLabelXlargeMobile: Float
    val maxWidthLabelXlargeTablet: Float
    val minInteractiveArea: Float
}
