//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// OUDS Core tokens version 1.2.0
//
// Android Core tokens version 1.0.0
// Android System tokens version 1.0.0
//
// Orange Core tokens version 1.1.0
// Orange System tokens version 1.2.0
//
// Generated by Tokenator

package com.orange.ouds.theme.tokens.semantic

import androidx.compose.ui.graphics.Color

interface OudsColorActionSemanticTokens {
    val actionDisabledDark: Color
    val actionDisabledLight: Color
    val actionEnabledDark: Color
    val actionEnabledLight: Color
    val actionFocusDark: Color
    val actionFocusLight: Color
    val actionHighlightedDark: Color
    val actionHighlightedLight: Color
    val actionHoverDark: Color
    val actionHoverLight: Color
    val actionLoadingDark: Color
    val actionLoadingLight: Color
    val actionNegativeEnabledDark: Color
    val actionNegativeEnabledLight: Color
    val actionNegativeFocusDark: Color
    val actionNegativeFocusLight: Color
    val actionNegativeHoverDark: Color
    val actionNegativeHoverLight: Color
    val actionNegativeLoadingDark: Color
    val actionNegativeLoadingLight: Color
    val actionNegativePressedDark: Color
    val actionNegativePressedLight: Color
    val actionPressedDark: Color
    val actionPressedLight: Color
    val actionSelectedDark: Color
    val actionSelectedLight: Color
    val actionSupportEnabledDark: Color
    val actionSupportEnabledLight: Color
    val actionSupportFocusDark: Color
    val actionSupportFocusLight: Color
    val actionSupportHoverDark: Color
    val actionSupportHoverLight: Color
    val actionSupportLoadingDark: Color
    val actionSupportLoadingLight: Color
    val actionSupportPressedDark: Color
    val actionSupportPressedLight: Color
    val actionVisitedDark: Color
    val actionVisitedLight: Color
}
