//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Tokens version 0.6.0
// Generated by Tokenator

package com.orange.ouds.theme.tokens.semantic

import androidx.compose.ui.graphics.Color

interface OudsColorOpacitySemanticTokens {
    val opacityLowerDark: Color
    val opacityLowerLight: Color
    val opacityLowestDark: Color
    val opacityLowestLight: Color
    val opacityTransparentDark: Color
    val opacityTransparentLight: Color
}
