/*
 * Software Name: OUDS Android
 * SPDX-FileCopyrightText: Copyright (c) Orange SA
 * SPDX-License-Identifier: MIT
 *
 * This software is distributed under the MIT license,
 * the text of which is available at https://opensource.org/license/MIT/
 * or see the "LICENSE" file for more details.
 *
 * Software description: Android library of reusable graphical components
 */

package com.orange.ouds.theme.tokens.semantic

import com.orange.ouds.tokens.global.raw.FontRawTokens

data class OudsFontSemanticTokens(
    val weightDefault: Int = FontRawTokens.fontWeightRegular,
    val weightStrong: Int = FontRawTokens.fontWeightBold,
    val weightDisplay: Int = FontRawTokens.fontWeightBold,
    val weightHeading: Int = FontRawTokens.fontWeightBold,
    val weightBodyDefault: Int = FontRawTokens.fontWeightRegular,
    val weightBodyStrong: Int = FontRawTokens.fontWeightBold,
    val weightLabelDefault: Int = FontRawTokens.fontWeightRegular,
    val weightLabelStrong: Int = FontRawTokens.fontWeightBold,
    val sizeMobileDisplayLarge: Int = FontRawTokens.fontSize850,
    val sizeMobileDisplayMedium: Int = FontRawTokens.fontSize750,
    val sizeMobileDisplaySmall: Int = FontRawTokens.fontSize650,
    val sizeMobileHeadingXLarge: Int = FontRawTokens.fontSize550,
    val sizeMobileHeadingLarge: Int = FontRawTokens.fontSize450,
    val sizeMobileHeadingMedium: Int = FontRawTokens.fontSize350,
    val sizeMobileHeadingSmall: Int = FontRawTokens.fontSize300,
    val sizeMobileBodyLarge: Int = FontRawTokens.fontSize250,
    val sizeMobileBodyMedium: Int = FontRawTokens.fontSize200,
    val sizeMobileBodySmall: Int = FontRawTokens.fontSize150,
    val sizeTabletDisplayLarge: Int = FontRawTokens.fontSize1450,
    val sizeTabletDisplayMedium: Int = FontRawTokens.fontSize1050,
    val sizeTabletDisplaySmall: Int = FontRawTokens.fontSize850,
    val sizeTabletHeadingXLarge: Int = FontRawTokens.fontSize750,
    val sizeTabletHeadingLarge: Int = FontRawTokens.fontSize550,
    val sizeTabletHeadingMedium: Int = FontRawTokens.fontSize450,
    val sizeTabletHeadingSmall: Int = FontRawTokens.fontSize350,
    val sizeTabletBodyLarge: Int = FontRawTokens.fontSize250,
    val sizeTabletBodyMedium: Int = FontRawTokens.fontSize200,
    val sizeTabletBodySmall: Int = FontRawTokens.fontSize150,
    val sizeLabelXLarge: Int = FontRawTokens.fontSize300,
    val sizeLabelLarge: Int = FontRawTokens.fontSize250,
    val sizeLabelMedium: Int = FontRawTokens.fontSize200,
    val sizeLabelSmall: Int = FontRawTokens.fontSize150,
    val lineHeightMobileDisplayLarge: Int = FontRawTokens.fontLineHeight1050,
    val lineHeightMobileDisplayMedium: Int = FontRawTokens.fontLineHeight950,
    val lineHeightMobileDisplaySmall: Int = FontRawTokens.fontLineHeight850,
    val lineHeightMobileHeadingXLarge: Int = FontRawTokens.fontLineHeight750,
    val lineHeightMobileHeadingLarge: Int = FontRawTokens.fontLineHeight650,
    val lineHeightMobileHeadingMedium: Int = FontRawTokens.fontLineHeight550,
    val lineHeightMobileHeadingSmall: Int = FontRawTokens.fontLineHeight450,
    val lineHeightMobileBodyLarge: Int = FontRawTokens.fontLineHeight450,
    val lineHeightMobileBodyMedium: Int = FontRawTokens.fontLineHeight350,
    val lineHeightMobileBodySmall: Int = FontRawTokens.fontLineHeight250,
    val lineHeightTabletDisplayLarge: Int = FontRawTokens.fontLineHeight1850,
    val lineHeightTabletDisplayMedium: Int = FontRawTokens.fontLineHeight1250,
    val lineHeightTabletDisplaySmall: Int = FontRawTokens.fontLineHeight1050,
    val lineHeightTabletHeadingXLarge: Int = FontRawTokens.fontLineHeight950,
    val lineHeightTabletHeadingLarge: Int = FontRawTokens.fontLineHeight750,
    val lineHeightTabletHeadingMedium: Int = FontRawTokens.fontLineHeight650,
    val lineHeightTabletHeadingSmall: Int = FontRawTokens.fontLineHeight550,
    val lineHeightTabletBodyLarge: Int = FontRawTokens.fontLineHeight450,
    val lineHeightTabletBodyMedium: Int = FontRawTokens.fontLineHeight350,
    val lineHeightTabletBodySmall: Int = FontRawTokens.fontLineHeight250,
    val lineHeightLabelXLarge: Int = FontRawTokens.fontLineHeight450,
    val lineHeightLabelLarge: Int = FontRawTokens.fontLineHeight450,
    val lineHeightLabelMedium: Int = FontRawTokens.fontLineHeight350,
    val lineHeightLabelSmall: Int = FontRawTokens.fontLineHeight250,
    val letterSpacingMobileDisplayLarge: Float = FontRawTokens.fontLetterSpacing850,
    val letterSpacingMobileDisplayMedium: Float = FontRawTokens.fontLetterSpacing750,
    val letterSpacingMobileDisplaySmall: Float = FontRawTokens.fontLetterSpacing650,
    val letterSpacingMobileHeadingXLarge: Float = FontRawTokens.fontLetterSpacing550,
    val letterSpacingMobileHeadingLarge: Float = FontRawTokens.fontLetterSpacing450,
    val letterSpacingMobileHeadingMedium: Float = FontRawTokens.fontLetterSpacing350,
    val letterSpacingMobileHeadingSmall: Float = FontRawTokens.fontLetterSpacing300,
    val letterSpacingMobileBodyLarge: Float = FontRawTokens.fontLetterSpacing250,
    val letterSpacingMobileBodyMedium: Float = FontRawTokens.fontLetterSpacing200,
    val letterSpacingMobileBodySmall: Float = FontRawTokens.fontLetterSpacing150,
    val letterSpacingTabletDisplayLarge: Float = FontRawTokens.fontLetterSpacing1450,
    val letterSpacingTabletDisplayMedium: Float = FontRawTokens.fontLetterSpacing1050,
    val letterSpacingTabletDisplaySmall: Float = FontRawTokens.fontLetterSpacing850,
    val letterSpacingTabletHeadingXLarge: Float = FontRawTokens.fontLetterSpacing750,
    val letterSpacingTabletHeadingLarge: Float = FontRawTokens.fontLetterSpacing550,
    val letterSpacingTabletHeadingMedium: Float = FontRawTokens.fontLetterSpacing450,
    val letterSpacingTabletHeadingSmall: Float = FontRawTokens.fontLetterSpacing350,
    val letterSpacingTabletBodyLarge: Float = FontRawTokens.fontLetterSpacing250,
    val letterSpacingTabletBodyMedium: Float = FontRawTokens.fontLetterSpacing200,
    val letterSpacingTabletBodySmall: Float = FontRawTokens.fontLetterSpacing150,
    val letterSpacingLabelXLarge: Float = FontRawTokens.fontLetterSpacing300,
    val letterSpacingLabelLarge: Float = FontRawTokens.fontLetterSpacing250,
    val letterSpacingLabelMedium: Float = FontRawTokens.fontLetterSpacing200,
    val letterSpacingLabelSmall: Float = FontRawTokens.fontLetterSpacing150,
)