//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Orange brand tokens version 2.0.0
// Generated by Tokenator

package com.orange.ouds.theme.tokens.semantic

import androidx.compose.ui.graphics.Color

interface OudsColorSurfaceSemanticTokens {
    val surfaceBrandPrimaryDark: Color
    val surfaceBrandPrimaryLight: Color
    val surfaceBrandSecondaryDark: Color
    val surfaceBrandSecondaryLight: Color
    val surfaceBrandTertiaryDark: Color
    val surfaceBrandTertiaryLight: Color
    val surfaceInverseHighDark: Color
    val surfaceInverseHighLight: Color
    val surfaceInverseLowDark: Color
    val surfaceInverseLowLight: Color
    val surfacePrimaryDark: Color
    val surfacePrimaryLight: Color
    val surfaceSecondaryDark: Color
    val surfaceSecondaryLight: Color
    val surfaceStatusAccentEmphasizedDark: Color
    val surfaceStatusAccentEmphasizedLight: Color
    val surfaceStatusAccentMutedDark: Color
    val surfaceStatusAccentMutedLight: Color
    val surfaceStatusInfoEmphasizedDark: Color
    val surfaceStatusInfoEmphasizedLight: Color
    val surfaceStatusInfoMutedDark: Color
    val surfaceStatusInfoMutedLight: Color
    val surfaceStatusNegativeEmphasizedDark: Color
    val surfaceStatusNegativeEmphasizedLight: Color
    val surfaceStatusNegativeMutedDark: Color
    val surfaceStatusNegativeMutedLight: Color
    val surfaceStatusPositiveEmphasizedDark: Color
    val surfaceStatusPositiveEmphasizedLight: Color
    val surfaceStatusPositiveMutedDark: Color
    val surfaceStatusPositiveMutedLight: Color
    val surfaceStatusWarningEmphasizedDark: Color
    val surfaceStatusWarningEmphasizedLight: Color
    val surfaceStatusWarningMutedDark: Color
    val surfaceStatusWarningMutedLight: Color
    val surfaceTertiaryDark: Color
    val surfaceTertiaryLight: Color
}
