/*
 * Software Name: OUDS Android
 * SPDX-FileCopyrightText: Copyright (c) Orange SA
 * SPDX-License-Identifier: MIT
 *
 * This software is distributed under the MIT license,
 * the text of which is available at https://opensource.org/license/MIT/
 * or see the "LICENSE" file for more details.
 *
 * Software description: Android library of reusable graphical components
 */

package com.orange.ouds.theme.tokens.semantic

import com.orange.ouds.tokens.global.raw.DimensionRawTokens

data class OudsSpacingSemanticTokens(
    val fixedNone: Float = DimensionRawTokens.dimension0,
    val fixedSmash: Float = DimensionRawTokens.dimension25,
    val fixedShortest: Float = DimensionRawTokens.dimension50,
    val fixedShorter: Float = DimensionRawTokens.dimension100,
    val fixedShort: Float = DimensionRawTokens.dimension150,
    val fixedMedium: Float = DimensionRawTokens.dimension200,
    val fixedTall: Float = DimensionRawTokens.dimension300,
    val fixedTaller: Float = DimensionRawTokens.dimension400,
    val fixedTallest: Float = DimensionRawTokens.dimension500,
    val fixedSpacious: Float = DimensionRawTokens.dimension600,
    val fixedHuge: Float = DimensionRawTokens.dimension700,
    val fixedJumbo: Float = DimensionRawTokens.dimension800,
    val scaledMediumMobile: Float = DimensionRawTokens.dimension200,
    val scaledNoneMobile: Float = DimensionRawTokens.dimension0,
    val scaledShortMobile: Float = DimensionRawTokens.dimension150,
    val scaledShorterMobile: Float = DimensionRawTokens.dimension100,
    val scaledShortestMobile: Float = DimensionRawTokens.dimension50,
    val scaledSmashMobile: Float = DimensionRawTokens.dimension25,
    val scaledSpaciousMobile: Float = DimensionRawTokens.dimension600,
    val scaledTallMobile: Float = DimensionRawTokens.dimension300,
    val scaledTallerMobile: Float = DimensionRawTokens.dimension400,
    val scaledTallestMobile: Float = DimensionRawTokens.dimension500,
    val scaledMediumTablet: Float = DimensionRawTokens.dimension300,
    val scaledNoneTablet: Float = DimensionRawTokens.dimension0,
    val scaledShortTablet: Float = DimensionRawTokens.dimension200,
    val scaledShorterTablet: Float = DimensionRawTokens.dimension150,
    val scaledShortestTablet: Float = DimensionRawTokens.dimension100,
    val scaledSmashTablet: Float = DimensionRawTokens.dimension50,
    val scaledSpaciousTablet: Float = DimensionRawTokens.dimension700,
    val scaledTallTablet: Float = DimensionRawTokens.dimension400,
    val scaledTallerTablet: Float = DimensionRawTokens.dimension500,
    val scaledTallestTablet: Float = DimensionRawTokens.dimension600,
    val paddingInlineNone: Float = DimensionRawTokens.dimension0,
    val paddingInlineShorter: Float = DimensionRawTokens.dimension50,
    val paddingInlineShort: Float = DimensionRawTokens.dimension100,
    val paddingInlineMedium: Float = DimensionRawTokens.dimension200,
    val paddingInlineTall: Float = DimensionRawTokens.dimension300,
    val paddingInlineTaller: Float = DimensionRawTokens.dimension350,
    val paddingInlineTallest: Float = DimensionRawTokens.dimension400,
    val paddingInlineWithIconNone: Float = DimensionRawTokens.dimension0,
    val paddingInlineWithIconShortest: Float = DimensionRawTokens.dimension25,
    val paddingInlineWithIconShorter: Float = DimensionRawTokens.dimension50,
    val paddingInlineWithIconShort: Float = DimensionRawTokens.dimension100,
    val paddingInlineWithIconMedium: Float = DimensionRawTokens.dimension200,
    val paddingInlineWithIconTall: Float = DimensionRawTokens.dimension250,
    val paddingInlineWithIconTaller: Float = DimensionRawTokens.dimension300,
    val paddingInlineWithIconTallest: Float = DimensionRawTokens.dimension250,
    val paddingInlineWithArrowNone: Float = DimensionRawTokens.dimension0,
    val paddingInlineWithArrowShortest: Float = DimensionRawTokens.dimension25,
    val paddingInlineWithArrowShorter: Float = DimensionRawTokens.dimension50,
    val paddingInlineWithArrowShort: Float = DimensionRawTokens.dimension75,
    val paddingInlineWithArrowMedium: Float = DimensionRawTokens.dimension100,
    val paddingInlineWithArrowTall: Float = DimensionRawTokens.dimension200,
    val paddingInlineWithArrowTaller: Float = DimensionRawTokens.dimension250,
    val paddingInlineWithArrowTallest: Float = DimensionRawTokens.dimension300,
    val paddingBlockNone: Float = DimensionRawTokens.dimension0,
    val paddingBlockShorter: Float = DimensionRawTokens.dimension50,
    val paddingBlockShort: Float = DimensionRawTokens.dimension100,
    val paddingBlockMedium: Float = DimensionRawTokens.dimension150,
    val paddingBlockTall: Float = DimensionRawTokens.dimension200,
    val paddingBlockTaller: Float = DimensionRawTokens.dimension300,
    val paddingBlockTallest: Float = DimensionRawTokens.dimension400,
    val paddingBlockWithIconNone: Float = DimensionRawTokens.dimension0,
    val paddingBlockWithIconShortest: Float = DimensionRawTokens.dimension25,
    val paddingBlockWithIconShorter: Float = DimensionRawTokens.dimension50,
    val paddingBlockWithIconShort: Float = DimensionRawTokens.dimension75,
    val paddingBlockWithIconMedium: Float = DimensionRawTokens.dimension100,
    val paddingBlockWithIconTall: Float = DimensionRawTokens.dimension150,
    val paddingBlockWithIconTaller: Float = DimensionRawTokens.dimension200,
    val insetNone: Float = DimensionRawTokens.dimension0,
    val insetSmash: Float = DimensionRawTokens.dimension25,
    val insetShortest: Float = DimensionRawTokens.dimension50,
    val insetShorter: Float = DimensionRawTokens.dimension75,
    val insetShort: Float = DimensionRawTokens.dimension100,
    val insetMedium: Float = DimensionRawTokens.dimension150,
    val insetTall: Float = DimensionRawTokens.dimension200,
    val insetTaller: Float = DimensionRawTokens.dimension300,
    val insetTallest: Float = DimensionRawTokens.dimension400,
    val insetSpacious: Float = DimensionRawTokens.dimension500,
    val columnGapNone: Float = DimensionRawTokens.dimension0,
    val columnGapShorter: Float = DimensionRawTokens.dimension50,
    val columnGapShort: Float = DimensionRawTokens.dimension100,
    val columnGapMedium: Float = DimensionRawTokens.dimension200,
    val columnGapTall: Float = DimensionRawTokens.dimension300,
    val columnGapTaller: Float = DimensionRawTokens.dimension400,
    val columnGapWithIconNone: Float = DimensionRawTokens.dimension0,
    val columnGapWithIconShortest: Float = DimensionRawTokens.dimension25,
    val columnGapWithIconShorter: Float = DimensionRawTokens.dimension50,
    val columnGapWithIconShort: Float = DimensionRawTokens.dimension75,
    val columnGapWithIconMedium: Float = DimensionRawTokens.dimension100,
    val columnGapWithIconTall: Float = DimensionRawTokens.dimension200,
    val columnGapWithArrowNone: Float = DimensionRawTokens.dimension0,
    val columnGapWithArrowShortest: Float = DimensionRawTokens.dimension25,
    val columnGapWithArrowShorter: Float = DimensionRawTokens.dimension50,
    val columnGapWithArrowShort: Float = DimensionRawTokens.dimension75,
    val columnGapWithArrowMedium: Float = DimensionRawTokens.dimension100,
    val columnGapWithArrowTall: Float = DimensionRawTokens.dimension200,
    val rowGapNone: Float = DimensionRawTokens.dimension0,
    val rowGapShortest: Float = DimensionRawTokens.dimension25,
    val rowGapShorter: Float = DimensionRawTokens.dimension50,
    val rowGapShort: Float = DimensionRawTokens.dimension75,
    val rowGapMedium: Float = DimensionRawTokens.dimension100,
    val rowGapTall: Float = DimensionRawTokens.dimension200,
    val rowGapWithIconNone: Float = DimensionRawTokens.dimension0,
    val rowGapWithIconShortest: Float = DimensionRawTokens.dimension25,
    val rowGapWithIconShorter: Float = DimensionRawTokens.dimension50,
    val rowGapWithIconShort: Float = DimensionRawTokens.dimension75,
    val rowGapWithIconMedium: Float = DimensionRawTokens.dimension100,
    val rowGapWithIconTall: Float = DimensionRawTokens.dimension200,
)
