/*
 * Software Name: OUDS Android
 * SPDX-FileCopyrightText: Copyright (c) Orange SA
 * SPDX-License-Identifier: MIT
 *
 * This software is distributed under the MIT license,
 * the text of which is available at https://opensource.org/license/MIT/
 * or see the "LICENSE" file for more details.
 *
 * Software description: Android library of reusable graphical components
 */

package com.orange.ouds.theme.tokens.semantic

import com.orange.ouds.tokens.global.raw.FontRawTokens

data class OudsFontSemanticTokens(
    val weightDefault: Int = FontRawTokens.fontWeight400,
    val weightStrong: Int = FontRawTokens.fontWeight700,
    val weightDisplay: Int = FontRawTokens.fontWeight700,
    val weightHeading: Int = FontRawTokens.fontWeight700,
    val weightBodyDefault: Int = FontRawTokens.fontWeight400,
    val weightBodyStrong: Int = FontRawTokens.fontWeight700,
    val weightLabelDefault: Int = FontRawTokens.fontWeight400,
    val weightLabelStrong: Int = FontRawTokens.fontWeight700,
    val sizeDisplayLargeMobile: Int = FontRawTokens.fontSize850,
    val sizeDisplayMediumMobile: Int = FontRawTokens.fontSize750,
    val sizeDisplaySmallMobile: Int = FontRawTokens.fontSize650,
    val sizeHeadingXlargeMobile: Int = FontRawTokens.fontSize550,
    val sizeHeadingLargeMobile: Int = FontRawTokens.fontSize450,
    val sizeHeadingMediumMobile: Int = FontRawTokens.fontSize350,
    val sizeHeadingSmallMobile: Int = FontRawTokens.fontSize300,
    val sizeBodyLargeMobile: Int = FontRawTokens.fontSize250,
    val sizeBodyMediumMobile: Int = FontRawTokens.fontSize200,
    val sizeBodySmallMobile: Int = FontRawTokens.fontSize150,
    val sizeDisplayLargeTablet: Int = FontRawTokens.fontSize1450,
    val sizeDisplayMediumTablet: Int = FontRawTokens.fontSize1050,
    val sizeDisplaySmallTablet: Int = FontRawTokens.fontSize850,
    val sizeHeadingXlargeTablet: Int = FontRawTokens.fontSize750,
    val sizeHeadingLargeTablet: Int = FontRawTokens.fontSize550,
    val sizeHeadingMediumTablet: Int = FontRawTokens.fontSize450,
    val sizeHeadingSmallTablet: Int = FontRawTokens.fontSize350,
    val sizeBodyLargeTablet: Int = FontRawTokens.fontSize250,
    val sizeBodyMediumTablet: Int = FontRawTokens.fontSize200,
    val sizeBodySmallTablet: Int = FontRawTokens.fontSize150,
    val sizeLabelXlarge: Int = FontRawTokens.fontSize300,
    val sizeLabelLarge: Int = FontRawTokens.fontSize250,
    val sizeLabelMedium: Int = FontRawTokens.fontSize200,
    val sizeLabelSmall: Int = FontRawTokens.fontSize150,
    val lineHeightDisplayLargeMobile: Int = FontRawTokens.fontLineHeight1050,
    val lineHeightDisplayMediumMobile: Int = FontRawTokens.fontLineHeight950,
    val lineHeightDisplaySmallMobile: Int = FontRawTokens.fontLineHeight850,
    val lineHeightHeadingXlargeMobile: Int = FontRawTokens.fontLineHeight750,
    val lineHeightHeadingLargeMobile: Int = FontRawTokens.fontLineHeight650,
    val lineHeightHeadingMediumMobile: Int = FontRawTokens.fontLineHeight550,
    val lineHeightHeadingSmallMobile: Int = FontRawTokens.fontLineHeight450,
    val lineHeightBodyLargeMobile: Int = FontRawTokens.fontLineHeight450,
    val lineHeightBodyMediumMobile: Int = FontRawTokens.fontLineHeight350,
    val lineHeightBodySmallMobile: Int = FontRawTokens.fontLineHeight250,
    val lineHeightDisplayLargeTablet: Int = FontRawTokens.fontLineHeight1850,
    val lineHeightDisplayMediumTablet: Int = FontRawTokens.fontLineHeight1250,
    val lineHeightDisplaySmallTablet: Int = FontRawTokens.fontLineHeight1050,
    val lineHeightHeadingXlargeTablet: Int = FontRawTokens.fontLineHeight950,
    val lineHeightHeadingLargeTablet: Int = FontRawTokens.fontLineHeight750,
    val lineHeightHeadingMediumTablet: Int = FontRawTokens.fontLineHeight650,
    val lineHeightHeadingSmallTablet: Int = FontRawTokens.fontLineHeight550,
    val lineHeightBodyLargeTablet: Int = FontRawTokens.fontLineHeight450,
    val lineHeightBodyMediumTablet: Int = FontRawTokens.fontLineHeight350,
    val lineHeightBodySmallTablet: Int = FontRawTokens.fontLineHeight250,
    val lineHeightLabelXlarge: Int = FontRawTokens.fontLineHeight450,
    val lineHeightLabelLarge: Int = FontRawTokens.fontLineHeight450,
    val lineHeightLabelMedium: Int = FontRawTokens.fontLineHeight350,
    val lineHeightLabelSmall: Int = FontRawTokens.fontLineHeight250,
    val letterSpacingDisplayLargeMobile: Float = FontRawTokens.fontLetterSpacing850,
    val letterSpacingDisplayMediumMobile: Float = FontRawTokens.fontLetterSpacing750,
    val letterSpacingDisplaySmallMobile: Float = FontRawTokens.fontLetterSpacing650,
    val letterSpacingHeadingXlargeMobile: Float = FontRawTokens.fontLetterSpacing550,
    val letterSpacingHeadingLargeMobile: Float = FontRawTokens.fontLetterSpacing450,
    val letterSpacingHeadingMediumMobile: Float = FontRawTokens.fontLetterSpacing350,
    val letterSpacingHeadingSmallMobile: Float = FontRawTokens.fontLetterSpacing300,
    val letterSpacingBodyLargeMobile: Float = FontRawTokens.fontLetterSpacing250,
    val letterSpacingBodyMediumMobile: Float = FontRawTokens.fontLetterSpacing200,
    val letterSpacingBodySmallMobile: Float = FontRawTokens.fontLetterSpacing150,
    val letterSpacingDisplayLargeTablet: Float = FontRawTokens.fontLetterSpacing1450,
    val letterSpacingDisplayMediumTablet: Float = FontRawTokens.fontLetterSpacing1050,
    val letterSpacingDisplaySmallTablet: Float = FontRawTokens.fontLetterSpacing850,
    val letterSpacingHeadingXlargeTablet: Float = FontRawTokens.fontLetterSpacing750,
    val letterSpacingHeadingLargeTablet: Float = FontRawTokens.fontLetterSpacing550,
    val letterSpacingHeadingMediumTablet: Float = FontRawTokens.fontLetterSpacing450,
    val letterSpacingHeadingSmallTablet: Float = FontRawTokens.fontLetterSpacing350,
    val letterSpacingBodyLargeTablet: Float = FontRawTokens.fontLetterSpacing250,
    val letterSpacingBodyMediumTablet: Float = FontRawTokens.fontLetterSpacing200,
    val letterSpacingBodySmallTablet: Float = FontRawTokens.fontLetterSpacing150,
    val letterSpacingLabelXlarge: Float = FontRawTokens.fontLetterSpacing300,
    val letterSpacingLabelLarge: Float = FontRawTokens.fontLetterSpacing250,
    val letterSpacingLabelMedium: Float = FontRawTokens.fontLetterSpacing200,
    val letterSpacingLabelSmall: Float = FontRawTokens.fontLetterSpacing150,
)