//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Tokens version 0.9.0
// Generated by Tokenator

package com.orange.ouds.theme.tokens.semantic

interface OudsElevationSemanticTokens {
    val drag: Float
    val none: Float
    val overlayDefault: Float
    val overlayEmphasized: Float
    val raised: Float
    val stickyDefault: Float
    val stickyEmphasized: Float
    val stickyNavigationScrolled: Float
}
