/*
 * Software Name: OUDS Android
 * SPDX-FileCopyrightText: Copyright (c) Orange SA
 * SPDX-License-Identifier: MIT
 *
 * This software is distributed under the MIT license,
 * the text of which is available at https://opensource.org/license/MIT/
 * or see the "LICENSE" file for more details.
 *
 * Software description: Android library of reusable graphical components
 */

package com.orange.ouds.dokka

import org.jetbrains.dokka.CoreExtensions
import org.jetbrains.dokka.plugability.DokkaPlugin
import org.jetbrains.dokka.plugability.DokkaPluginApiPreview
import org.jetbrains.dokka.plugability.PluginApiPreviewAcknowledgement

/**
 * A Dokka plugin for OUDS Android documentation.
 *
 * This Dokka plugin performs transformation on the components KDoc.
 * More precisely, it replaces the component design version and guidelines link that are displayed as blockquotes in Android Studio quick documentation
 * with a table containing all this information in a design section of the component documentation generated by Dokka.
 */
class OudsDokkaPlugin : DokkaPlugin() {

    @OptIn(DokkaPluginApiPreview::class)
    override fun pluginApiPreviewAcknowledgement(): PluginApiPreviewAcknowledgement = PluginApiPreviewAcknowledgement

    // Add the transformer to the documentableTransformer core extension point
    val componentDocumentableTransformer by extending {
        CoreExtensions.documentableTransformer providing { OudsComponentDocumentableTransformer() }
    }
}
