//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Sosh brand tokens version 2.2.0
// Generated by Tokenator

package com.orange.ouds.theme.sosh.tokens.semantic

import androidx.compose.ui.graphics.Color
import com.orange.ouds.theme.sosh.tokens.raw.SoshColorRawTokens
import com.orange.ouds.theme.tokens.semantic.OudsColorActionSemanticTokens
import com.orange.ouds.tokens.raw.OudsColorRawTokens

data class SoshColorActionSemanticTokens(
    override val actionDisabledDark: Color = OudsColorRawTokens.colorOpacityWhite200,
    override val actionDisabledLight: Color = OudsColorRawTokens.colorOpacityBlack200,
    override val actionEnabledDark: Color = SoshColorRawTokens.colorBlueDuckLight800,
    override val actionEnabledLight: Color = SoshColorRawTokens.colorMagenta500,
    override val actionFocusDark: Color = OudsColorRawTokens.colorFunctionalGrayLight160,
    override val actionFocusLight: Color = OudsColorRawTokens.colorFunctionalBlack,
    override val actionHighlightedDark: Color = OudsColorRawTokens.colorFunctionalGrayLight160,
    override val actionHighlightedLight: Color = SoshColorRawTokens.colorBlueDuckDark400,
    override val actionHoverDark: Color = OudsColorRawTokens.colorFunctionalGrayLight160,
    override val actionHoverLight: Color = OudsColorRawTokens.colorFunctionalBlack,
    override val actionLoadingDark: Color = SoshColorRawTokens.colorCitrine300,
    override val actionLoadingLight: Color = SoshColorRawTokens.colorBlueDuckDark400,
    override val actionNegativeEnabledDark: Color = OudsColorRawTokens.colorFunctionalScarlet300,
    override val actionNegativeEnabledLight: Color = OudsColorRawTokens.colorFunctionalScarlet600,
    override val actionNegativeFocusDark: Color = OudsColorRawTokens.colorFunctionalScarlet200,
    override val actionNegativeFocusLight: Color = OudsColorRawTokens.colorFunctionalScarlet700,
    override val actionNegativeHoverDark: Color = OudsColorRawTokens.colorFunctionalScarlet200,
    override val actionNegativeHoverLight: Color = OudsColorRawTokens.colorFunctionalScarlet700,
    override val actionNegativeLoadingDark: Color = OudsColorRawTokens.colorFunctionalScarlet100,
    override val actionNegativeLoadingLight: Color = OudsColorRawTokens.colorFunctionalScarlet800,
    override val actionNegativePressedDark: Color = OudsColorRawTokens.colorFunctionalScarlet100,
    override val actionNegativePressedLight: Color = OudsColorRawTokens.colorFunctionalScarlet800,
    override val actionPressedDark: Color = SoshColorRawTokens.colorCitrine300,
    override val actionPressedLight: Color = SoshColorRawTokens.colorBlueDuckDark400,
    override val actionReadOnlyPrimaryDark: Color = OudsColorRawTokens.colorFunctionalGrayLight160,
    override val actionReadOnlyPrimaryLight: Color = OudsColorRawTokens.colorFunctionalBlack,
    override val actionReadOnlySecondaryDark: Color = OudsColorRawTokens.colorOpacityWhite200,
    override val actionReadOnlySecondaryLight: Color = OudsColorRawTokens.colorOpacityBlack200,
    override val actionSelectedDark: Color = SoshColorRawTokens.colorBlueDuckLight800,
    override val actionSelectedLight: Color = SoshColorRawTokens.colorMagenta500,
    override val actionSupportDisabledDark: Color = OudsColorRawTokens.colorOpacityWhite40,
    override val actionSupportDisabledLight: Color = OudsColorRawTokens.colorOpacityBlack40,
    override val actionSupportEnabledDark: Color = OudsColorRawTokens.colorOpacityWhite40,
    override val actionSupportEnabledLight: Color = OudsColorRawTokens.colorOpacityBlack40,
    override val actionSupportFocusDark: Color = OudsColorRawTokens.colorOpacityWhite80,
    override val actionSupportFocusLight: Color = OudsColorRawTokens.colorOpacityBlack80,
    override val actionSupportHoverDark: Color = OudsColorRawTokens.colorOpacityWhite80,
    override val actionSupportHoverLight: Color = OudsColorRawTokens.colorOpacityBlack80,
    override val actionSupportLoadingDark: Color = OudsColorRawTokens.colorOpacityWhite120,
    override val actionSupportLoadingLight: Color = OudsColorRawTokens.colorOpacityBlack120,
    override val actionSupportPressedDark: Color = OudsColorRawTokens.colorOpacityWhite120,
    override val actionSupportPressedLight: Color = OudsColorRawTokens.colorOpacityBlack120,
    override val actionVisitedDark: Color = OudsColorRawTokens.colorFunctionalAmethyst400,
    override val actionVisitedLight: Color = OudsColorRawTokens.colorFunctionalAmethyst600
) : OudsColorActionSemanticTokens
