//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Sosh brand tokens version 2.5.0
// Generated by Tokenator

package com.orange.ouds.theme.sosh.tokens.semantic

import androidx.compose.ui.graphics.Color
import com.orange.ouds.theme.sosh.tokens.raw.SoshColorRawTokens
import com.orange.ouds.theme.tokens.semantic.OudsColorActionSemanticTokens
import com.orange.ouds.tokens.raw.OudsColorRawTokens

internal data class SoshColorActionSemanticTokens(
    override val actionDisabledDark: Color = SoshColorRawTokens.ColorOpacityWhite200,
    override val actionDisabledLight: Color = SoshColorRawTokens.ColorOpacityBlack200,
    override val actionEnabledDark: Color = SoshColorRawTokens.ColorLochmaraLight640,
    override val actionEnabledLight: Color = SoshColorRawTokens.ColorRaspberry500,
    override val actionFocusDark: Color = SoshColorRawTokens.ColorFunctionalGrayLight160,
    override val actionFocusLight: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val actionHighlightedDark: Color = SoshColorRawTokens.ColorFunctionalGrayLight160,
    override val actionHighlightedLight: Color = SoshColorRawTokens.ColorLochmaraDark240,
    override val actionHoverDark: Color = SoshColorRawTokens.ColorFunctionalGrayLight160,
    override val actionHoverLight: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val actionLoadingDark: Color = SoshColorRawTokens.ColorTurbo300,
    override val actionLoadingLight: Color = SoshColorRawTokens.ColorLochmaraDark240,
    override val actionNegativeEnabledDark: Color = OudsColorRawTokens.ColorFunctionalScarlet300,
    override val actionNegativeEnabledLight: Color = OudsColorRawTokens.ColorFunctionalScarlet600,
    override val actionNegativeFocusDark: Color = OudsColorRawTokens.ColorFunctionalScarlet200,
    override val actionNegativeFocusLight: Color = OudsColorRawTokens.ColorFunctionalScarlet700,
    override val actionNegativeHoverDark: Color = OudsColorRawTokens.ColorFunctionalScarlet200,
    override val actionNegativeHoverLight: Color = OudsColorRawTokens.ColorFunctionalScarlet700,
    override val actionNegativeLoadingDark: Color = OudsColorRawTokens.ColorFunctionalScarlet100,
    override val actionNegativeLoadingLight: Color = OudsColorRawTokens.ColorFunctionalScarlet800,
    override val actionNegativePressedDark: Color = OudsColorRawTokens.ColorFunctionalScarlet100,
    override val actionNegativePressedLight: Color = OudsColorRawTokens.ColorFunctionalScarlet800,
    override val actionPressedDark: Color = SoshColorRawTokens.ColorTurbo300,
    override val actionPressedLight: Color = SoshColorRawTokens.ColorLochmaraDark240,
    override val actionReadOnlyPrimaryDark: Color = SoshColorRawTokens.ColorFunctionalGrayLight160,
    override val actionReadOnlyPrimaryLight: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val actionReadOnlySecondaryDark: Color = SoshColorRawTokens.ColorOpacityWhite200,
    override val actionReadOnlySecondaryLight: Color = SoshColorRawTokens.ColorOpacityBlack200,
    override val actionSelectedDark: Color = SoshColorRawTokens.ColorLochmaraLight640,
    override val actionSelectedLight: Color = SoshColorRawTokens.ColorRaspberry500,
    override val actionSupportDisabledDark: Color = SoshColorRawTokens.ColorOpacityWhite40,
    override val actionSupportDisabledLight: Color = SoshColorRawTokens.ColorOpacityBlack40,
    override val actionSupportEnabledDark: Color = SoshColorRawTokens.ColorOpacityWhite40,
    override val actionSupportEnabledLight: Color = SoshColorRawTokens.ColorOpacityBlack40,
    override val actionSupportFocusDark: Color = SoshColorRawTokens.ColorOpacityWhite80,
    override val actionSupportFocusLight: Color = SoshColorRawTokens.ColorOpacityBlack80,
    override val actionSupportHoverDark: Color = SoshColorRawTokens.ColorOpacityWhite80,
    override val actionSupportHoverLight: Color = SoshColorRawTokens.ColorOpacityBlack80,
    override val actionSupportLoadingDark: Color = SoshColorRawTokens.ColorOpacityWhite120,
    override val actionSupportLoadingLight: Color = SoshColorRawTokens.ColorOpacityBlack120,
    override val actionSupportPressedDark: Color = SoshColorRawTokens.ColorOpacityWhite120,
    override val actionSupportPressedLight: Color = SoshColorRawTokens.ColorOpacityBlack120,
    override val actionVisitedDark: Color = OudsColorRawTokens.ColorFunctionalAmethyst400,
    override val actionVisitedLight: Color = OudsColorRawTokens.ColorFunctionalAmethyst600
) : OudsColorActionSemanticTokens
