//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// OUDS Core tokens version 1.3.0
//
// Android Core tokens version 1.0.0
// Android System tokens version 1.0.0
//
// Orange Core tokens version 1.1.0
// Orange Brand tokens version 1.3.0
//
// Generated by Tokenator

package com.orange.ouds.theme.sosh.tokens.semantic

import androidx.compose.ui.graphics.Color
import com.orange.ouds.theme.tokens.semantic.OudsColorOpacitySemanticTokens
import com.orange.ouds.tokens.raw.ColorRawTokens

data class SoshColorOpacitySemanticTokens(
    override val opacityLowerDark: Color = ColorRawTokens.colorOpacityWhite80,
    override val opacityLowerLight: Color = ColorRawTokens.colorOpacityBlack80,
    override val opacityLowestDark: Color = ColorRawTokens.colorOpacityWhite40,
    override val opacityLowestLight: Color = ColorRawTokens.colorOpacityBlack40,
    override val opacityTransparentDark: Color = ColorRawTokens.colorOpacityWhite0,
    override val opacityTransparentLight: Color = ColorRawTokens.colorOpacityBlack0
) : OudsColorOpacitySemanticTokens
