//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Sosh brand tokens version 2.4.0
// Generated by Tokenator

package com.orange.ouds.theme.sosh.tokens.semantic

import com.orange.ouds.theme.tokens.semantic.OudsOpacitySemanticTokens
import com.orange.ouds.tokens.raw.OudsOpacityRawTokens

internal data class SoshOpacitySemanticTokens(
    override val disabled: Float = OudsOpacityRawTokens.Opacity200,
    override val invisible: Float = OudsOpacityRawTokens.Opacity0,
    override val medium: Float = OudsOpacityRawTokens.Opacity560,
    override val opaque: Float = OudsOpacityRawTokens.Opacity1000,
    override val strong: Float = OudsOpacityRawTokens.Opacity640,
    override val weak: Float = OudsOpacityRawTokens.Opacity320,
    override val weaker: Float = OudsOpacityRawTokens.Opacity160,
    override val weakest: Float = OudsOpacityRawTokens.Opacity40
) : OudsOpacitySemanticTokens
