//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Sosh brand tokens version 2.2.0
// Generated by Tokenator

package com.orange.ouds.theme.sosh.tokens.semantic

import androidx.compose.ui.graphics.Color
import com.orange.ouds.theme.sosh.tokens.raw.SoshColorRawTokens
import com.orange.ouds.theme.tokens.semantic.OudsColorBorderSemanticTokens
import com.orange.ouds.tokens.raw.OudsColorRawTokens

data class SoshColorBorderSemanticTokens(
    override val borderBrandPrimaryDark: Color = SoshColorRawTokens.colorMagenta300,
    override val borderBrandPrimaryLight: Color = SoshColorRawTokens.colorMagenta500,
    override val borderBrandSecondaryDark: Color = SoshColorRawTokens.colorBlueDuckLight800,
    override val borderBrandSecondaryLight: Color = SoshColorRawTokens.colorBlueDuckDark400,
    override val borderBrandTertiaryDark: Color = SoshColorRawTokens.colorCitrine300,
    override val borderBrandTertiaryLight: Color = SoshColorRawTokens.colorCitrine500,
    override val borderDefaultDark: Color = OudsColorRawTokens.colorOpacityWhite200,
    override val borderDefaultLight: Color = OudsColorRawTokens.colorOpacityBlack200,
    override val borderEmphasizedDark: Color = OudsColorRawTokens.colorOpacityWhite920,
    override val borderEmphasizedLight: Color = OudsColorRawTokens.colorFunctionalBlack,
    override val borderFocusDark: Color = OudsColorRawTokens.colorFunctionalGrayLight160,
    override val borderFocusInsetDark: Color = OudsColorRawTokens.colorFunctionalGrayDark880,
    override val borderFocusInsetLight: Color = OudsColorRawTokens.colorFunctionalWhite,
    override val borderFocusLight: Color = OudsColorRawTokens.colorFunctionalBlack,
    override val borderMinimalDark: Color = OudsColorRawTokens.colorOpacityWhite40,
    override val borderMinimalLight: Color = OudsColorRawTokens.colorOpacityBlack40,
    override val borderMutedDark: Color = OudsColorRawTokens.colorOpacityWhite80,
    override val borderMutedLight: Color = OudsColorRawTokens.colorOpacityBlack80,
    override val borderOnBrandPrimaryDark: Color = SoshColorRawTokens.colorBlueDuckDark960,
    override val borderOnBrandPrimaryLight: Color = OudsColorRawTokens.colorFunctionalWhite,
    override val borderOnBrandSecondaryDark: Color = SoshColorRawTokens.colorBlueDuckDark960,
    override val borderOnBrandSecondaryLight: Color = OudsColorRawTokens.colorFunctionalWhite,
    override val borderOnBrandTertiaryDark: Color = SoshColorRawTokens.colorBlueDuckDark960,
    override val borderOnBrandTertiaryLight: Color = OudsColorRawTokens.colorFunctionalBlack,
    override val borderStatusAccentDark: Color = SoshColorRawTokens.colorMagenta300,
    override val borderStatusAccentLight: Color = SoshColorRawTokens.colorMagenta500,
    override val borderStatusInfoDark: Color = OudsColorRawTokens.colorFunctionalDodgerBlue300,
    override val borderStatusInfoLight: Color = OudsColorRawTokens.colorFunctionalDodgerBlue700,
    override val borderStatusNegativeDark: Color = OudsColorRawTokens.colorFunctionalScarlet300,
    override val borderStatusNegativeLight: Color = OudsColorRawTokens.colorFunctionalScarlet600,
    override val borderStatusPositiveDark: Color = OudsColorRawTokens.colorFunctionalMalachite300,
    override val borderStatusPositiveLight: Color = OudsColorRawTokens.colorFunctionalMalachite750,
    override val borderStatusWarningDark: Color = OudsColorRawTokens.colorFunctionalSun300,
    override val borderStatusWarningLight: Color = OudsColorRawTokens.colorFunctionalSun500
) : OudsColorBorderSemanticTokens
