//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Sosh brand tokens version 2.2.0
// Generated by Tokenator

package com.orange.ouds.theme.sosh.tokens.semantic

import com.orange.ouds.theme.tokens.semantic.OudsSpaceSemanticTokens
import com.orange.ouds.tokens.raw.OudsDimensionRawTokens

data class SoshSpaceSemanticTokens(
    override val columnGap2xlarge: Float = OudsDimensionRawTokens.dimension300,
    override val columnGap2xsmall: Float = OudsDimensionRawTokens.dimension50,
    override val columnGap3xsmall: Float = OudsDimensionRawTokens.dimensionOutOfSystem50,
    override val columnGapLarge: Float = OudsDimensionRawTokens.dimension200,
    override val columnGapMedium: Float = OudsDimensionRawTokens.dimension150,
    override val columnGapNone: Float = OudsDimensionRawTokens.dimension0,
    override val columnGapSmall: Float = OudsDimensionRawTokens.dimension100,
    override val columnGapXlarge: Float = OudsDimensionRawTokens.dimension250,
    override val columnGapXsmall: Float = OudsDimensionRawTokens.dimensionOutOfSystem150,
    override val fixed2xlarge: Float = OudsDimensionRawTokens.dimension500,
    override val fixed2xsmall: Float = OudsDimensionRawTokens.dimension50,
    override val fixed3xlarge: Float = OudsDimensionRawTokens.dimension600,
    override val fixed3xsmall: Float = OudsDimensionRawTokens.dimensionOutOfSystem50,
    override val fixed4xlarge: Float = OudsDimensionRawTokens.dimension700,
    override val fixed5xlarge: Float = OudsDimensionRawTokens.dimension800,
    override val fixedLarge: Float = OudsDimensionRawTokens.dimension300,
    override val fixedMedium: Float = OudsDimensionRawTokens.dimension200,
    override val fixedNone: Float = OudsDimensionRawTokens.dimension0,
    override val fixedSmall: Float = OudsDimensionRawTokens.dimension150,
    override val fixedXlarge: Float = OudsDimensionRawTokens.dimension400,
    override val fixedXsmall: Float = OudsDimensionRawTokens.dimension100,
    override val inset2xlarge: Float = OudsDimensionRawTokens.dimension400,
    override val inset2xsmall: Float = OudsDimensionRawTokens.dimension50,
    override val inset3xlarge: Float = OudsDimensionRawTokens.dimension500,
    override val inset3xsmall: Float = OudsDimensionRawTokens.dimensionOutOfSystem50,
    override val inset4xsmall: Float = OudsDimensionRawTokens.dimensionOutOfSystem25,
    override val insetLarge: Float = OudsDimensionRawTokens.dimension200,
    override val insetMedium: Float = OudsDimensionRawTokens.dimension150,
    override val insetNone: Float = OudsDimensionRawTokens.dimension0,
    override val insetSmall: Float = OudsDimensionRawTokens.dimension100,
    override val insetXlarge: Float = OudsDimensionRawTokens.dimension300,
    override val insetXsmall: Float = OudsDimensionRawTokens.dimensionOutOfSystem150,
    override val paddingBlock2xlarge: Float = OudsDimensionRawTokens.dimension300,
    override val paddingBlock2xsmall: Float = OudsDimensionRawTokens.dimensionOutOfSystem150,
    override val paddingBlock3xlarge: Float = OudsDimensionRawTokens.dimension350,
    override val paddingBlock3xsmall: Float = OudsDimensionRawTokens.dimension50,
    override val paddingBlock4xlarge: Float = OudsDimensionRawTokens.dimension400,
    override val paddingBlock4xsmall: Float = OudsDimensionRawTokens.dimensionOutOfSystem50,
    override val paddingBlockLarge: Float = OudsDimensionRawTokens.dimension200,
    override val paddingBlockMedium: Float = OudsDimensionRawTokens.dimension150,
    override val paddingBlockNone: Float = OudsDimensionRawTokens.dimension0,
    override val paddingBlockSmall: Float = OudsDimensionRawTokens.dimensionOutOfSystem250,
    override val paddingBlockXlarge: Float = OudsDimensionRawTokens.dimension250,
    override val paddingBlockXsmall: Float = OudsDimensionRawTokens.dimension100,
    override val paddingInline2xlarge: Float = OudsDimensionRawTokens.dimension300,
    override val paddingInline2xsmall: Float = OudsDimensionRawTokens.dimensionOutOfSystem150,
    override val paddingInline3xlarge: Float = OudsDimensionRawTokens.dimension350,
    override val paddingInline3xsmall: Float = OudsDimensionRawTokens.dimension50,
    override val paddingInline4xlarge: Float = OudsDimensionRawTokens.dimension400,
    override val paddingInline4xsmall: Float = OudsDimensionRawTokens.dimensionOutOfSystem50,
    override val paddingInlineLarge: Float = OudsDimensionRawTokens.dimension200,
    override val paddingInlineMedium: Float = OudsDimensionRawTokens.dimension150,
    override val paddingInlineNone: Float = OudsDimensionRawTokens.dimension0,
    override val paddingInlineSmall: Float = OudsDimensionRawTokens.dimensionOutOfSystem250,
    override val paddingInlineXlarge: Float = OudsDimensionRawTokens.dimension250,
    override val paddingInlineXsmall: Float = OudsDimensionRawTokens.dimension100,
    override val rowGap2xsmall: Float = OudsDimensionRawTokens.dimension50,
    override val rowGap3xsmall: Float = OudsDimensionRawTokens.dimensionOutOfSystem50,
    override val rowGapLarge: Float = OudsDimensionRawTokens.dimension200,
    override val rowGapMedium: Float = OudsDimensionRawTokens.dimension150,
    override val rowGapNone: Float = OudsDimensionRawTokens.dimension0,
    override val rowGapSmall: Float = OudsDimensionRawTokens.dimension100,
    override val rowGapXsmall: Float = OudsDimensionRawTokens.dimensionOutOfSystem150,
    override val scaled2xlargeMobile: Float = OudsDimensionRawTokens.dimension500,
    override val scaled2xlargeTablet: Float = OudsDimensionRawTokens.dimension600,
    override val scaled2xsmallMobile: Float = OudsDimensionRawTokens.dimension50,
    override val scaled2xsmallTablet: Float = OudsDimensionRawTokens.dimension100,
    override val scaled3xlargeMobile: Float = OudsDimensionRawTokens.dimension600,
    override val scaled3xlargeTablet: Float = OudsDimensionRawTokens.dimension700,
    override val scaled3xsmallMobile: Float = OudsDimensionRawTokens.dimensionOutOfSystem50,
    override val scaled3xsmallTablet: Float = OudsDimensionRawTokens.dimension50,
    override val scaledLargeMobile: Float = OudsDimensionRawTokens.dimension300,
    override val scaledLargeTablet: Float = OudsDimensionRawTokens.dimension400,
    override val scaledMediumMobile: Float = OudsDimensionRawTokens.dimension200,
    override val scaledMediumTablet: Float = OudsDimensionRawTokens.dimension300,
    override val scaledNoneMobile: Float = OudsDimensionRawTokens.dimension0,
    override val scaledNoneTablet: Float = OudsDimensionRawTokens.dimension0,
    override val scaledSmallMobile: Float = OudsDimensionRawTokens.dimension150,
    override val scaledSmallTablet: Float = OudsDimensionRawTokens.dimension200,
    override val scaledXlargeMobile: Float = OudsDimensionRawTokens.dimension400,
    override val scaledXlargeTablet: Float = OudsDimensionRawTokens.dimension500,
    override val scaledXsmallMobile: Float = OudsDimensionRawTokens.dimension100,
    override val scaledXsmallTablet: Float = OudsDimensionRawTokens.dimension150
) : OudsSpaceSemanticTokens
