//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// OUDS Core tokens version 1.2.0
//
// Android Core tokens version 1.0.0
// Android System tokens version 1.0.0
//
// Orange Core tokens version 1.1.0
// Orange Brand tokens version 1.2.0
//
// Generated by Tokenator

package com.orange.ouds.theme.sosh.tokens.semantic

import androidx.compose.ui.graphics.Color
import com.orange.ouds.theme.sosh.tokens.raw.SoshColorRawTokens
import com.orange.ouds.theme.tokens.semantic.OudsColorActionSemanticTokens
import com.orange.ouds.tokens.raw.ColorRawTokens

data class SoshColorActionSemanticTokens(
    override val actionDisabledDark: Color = ColorRawTokens.colorOpacityWhite200,
    override val actionDisabledLight: Color = ColorRawTokens.colorOpacityBlack200,
    override val actionEnabledDark: Color = SoshColorRawTokens.colorBlueDuckLight800,
    override val actionEnabledLight: Color = SoshColorRawTokens.colorMagenta500,
    override val actionFocusDark: Color = ColorRawTokens.colorFunctionalGrayLight160,
    override val actionFocusLight: Color = ColorRawTokens.colorFunctionalBlack,
    override val actionHighlightedDark: Color = ColorRawTokens.colorFunctionalGrayLight160,
    override val actionHighlightedLight: Color = SoshColorRawTokens.colorBlueDuckDark400,
    override val actionHoverDark: Color = ColorRawTokens.colorFunctionalGrayLight160,
    override val actionHoverLight: Color = ColorRawTokens.colorFunctionalBlack,
    override val actionLoadingDark: Color = SoshColorRawTokens.colorCitrine300,
    override val actionLoadingLight: Color = SoshColorRawTokens.colorBlueDuckDark400,
    override val actionNegativeEnabledDark: Color = ColorRawTokens.colorFunctionalScarlet300,
    override val actionNegativeEnabledLight: Color = ColorRawTokens.colorFunctionalScarlet600,
    override val actionNegativeFocusDark: Color = ColorRawTokens.colorFunctionalScarlet200,
    override val actionNegativeFocusLight: Color = ColorRawTokens.colorFunctionalScarlet700,
    override val actionNegativeHoverDark: Color = ColorRawTokens.colorFunctionalScarlet200,
    override val actionNegativeHoverLight: Color = ColorRawTokens.colorFunctionalScarlet700,
    override val actionNegativeLoadingDark: Color = ColorRawTokens.colorFunctionalScarlet100,
    override val actionNegativeLoadingLight: Color = ColorRawTokens.colorFunctionalScarlet800,
    override val actionNegativePressedDark: Color = ColorRawTokens.colorFunctionalScarlet100,
    override val actionNegativePressedLight: Color = ColorRawTokens.colorFunctionalScarlet800,
    override val actionPressedDark: Color = SoshColorRawTokens.colorCitrine300,
    override val actionPressedLight: Color = SoshColorRawTokens.colorBlueDuckDark400,
    override val actionSelectedDark: Color = SoshColorRawTokens.colorBlueDuckLight800,
    override val actionSelectedLight: Color = SoshColorRawTokens.colorMagenta500,
    override val actionSupportEnabledDark: Color = ColorRawTokens.colorOpacityWhite40,
    override val actionSupportEnabledLight: Color = ColorRawTokens.colorOpacityBlack40,
    override val actionSupportFocusDark: Color = ColorRawTokens.colorOpacityWhite80,
    override val actionSupportFocusLight: Color = ColorRawTokens.colorOpacityBlack80,
    override val actionSupportHoverDark: Color = ColorRawTokens.colorOpacityWhite80,
    override val actionSupportHoverLight: Color = ColorRawTokens.colorOpacityBlack80,
    override val actionSupportLoadingDark: Color = ColorRawTokens.colorOpacityWhite120,
    override val actionSupportLoadingLight: Color = ColorRawTokens.colorOpacityBlack120,
    override val actionSupportPressedDark: Color = ColorRawTokens.colorOpacityWhite120,
    override val actionSupportPressedLight: Color = ColorRawTokens.colorOpacityBlack120,
    override val actionVisitedDark: Color = SoshColorRawTokens.colorCitrine300,
    override val actionVisitedLight: Color = SoshColorRawTokens.colorCitrine500
) : OudsColorActionSemanticTokens
