//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Sosh brand tokens version 2.3.0
// Generated by Tokenator

package com.orange.ouds.theme.sosh.tokens.semantic

import androidx.compose.ui.graphics.Color
import com.orange.ouds.theme.sosh.tokens.raw.SoshColorRawTokens
import com.orange.ouds.theme.tokens.semantic.OudsColorBgSemanticTokens
import com.orange.ouds.tokens.raw.OudsColorRawTokens

internal data class SoshColorBgSemanticTokens(
    override val bgInverseHighDark: Color = OudsColorRawTokens.ColorFunctionalGrayLight160,
    override val bgInverseHighLight: Color = SoshColorRawTokens.ColorBlueDuckDark880,
    override val bgInverseLowDark: Color = SoshColorRawTokens.ColorBlueDuckDark720,
    override val bgInverseLowLight: Color = SoshColorRawTokens.ColorBlueDuckDark880,
    override val bgPrimaryDark: Color = SoshColorRawTokens.ColorBlueDuckDark960,
    override val bgPrimaryLight: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val bgSecondaryDark: Color = SoshColorRawTokens.ColorBlueDuckDark880,
    override val bgSecondaryLight: Color = SoshColorRawTokens.ColorBlueDuckLight80,
    override val bgTertiaryDark: Color = SoshColorRawTokens.ColorCitrine950,
    override val bgTertiaryLight: Color = SoshColorRawTokens.ColorCitrine50
) : OudsColorBgSemanticTokens
