/*
 * Software Name: OUDS Android
 * SPDX-FileCopyrightText: Copyright (c) Orange SA
 * SPDX-License-Identifier: MIT
 *
 * This software is distributed under the MIT license,
 * the text of which is available at https://opensource.org/license/MIT/
 * or see the "LICENSE" file for more details.
 *
 * Software description: Android library of reusable graphical components 
 */

package com.orange.ouds.foundation

/**
 * Generic provider interface for accessing deprecated tokens.
 *
 * This interface enables token classes to expose deprecated tokens through a separate [deprecated] property,
 * isolating them from the main token definitions that are generated by Tokenator. This ensures that
 * manually maintained deprecated tokens are not overwritten during automated token regeneration.
 *
 * ```kotlin
 * // Token class implements the provider
 * class MyTokens : MyTokensInterface, MyDeprecatedTokensProvider<MyDeprecatedTokensInterface> {
 *     // Regular tokens...
 * }
 *
 * // Provider implementation returns deprecated tokens
 * interface MyDeprecatedTokensProvider<T> : OudsDeprecatedTokensProvider<T> {
 *     @Suppress("UNCHECKED_CAST")
 *     override val deprecated: T
 *         get() = when (this) {
 *             is MyTokens -> MyDeprecatedTokensImpl() as T
 *             else -> error("No deprecated tokens available for this type.")
 *         }
 * }
 *
 * // Consumers access deprecated tokens with suppression
 * @Suppress("DEPRECATION")
 * val value = tokens.deprecated.someDeprecatedToken
 * ```
 *
 * Deprecated token files should be organized in a `deprecated/` subdirectory within their respective
 * modules to clearly distinguish them from generated code.
 *
 * @param T The type of the deprecated token interface
 */
@InternalOudsApi
interface OudsDeprecatedTokensProvider<T> {

    /**
     * The deprecated tokens.
     */
    val deprecated: T
}
