//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// OUDS core tokens version 1.5.0
// Generated by Tokenator

package com.orange.ouds.tokens.raw

object BorderRawTokens {
  const val borderBase = 4
  const val borderRadius0 = borderBase * 0f // 0
  const val borderRadius25 = borderBase * 0.25f // 1
  const val borderRadius50 = borderBase * 0.5f // 2
  const val borderRadius75 = borderBase * 0.75f // 3
  const val borderRadius100 = borderBase * 1f // 4
  const val borderRadius150 = borderBase * 1.5f // 6
  const val borderRadius200 = borderBase * 2f // 8
  const val borderRadius300 = borderBase * 3f // 12
  const val borderRadius400 = borderBase * 4f // 16
  const val borderRadius500 = borderBase * 5f // 20
  const val borderRadius600 = borderBase * 6f // 24
  const val borderRadius800 = borderBase * 8f // 32
  const val borderRadius9999 = 2000f
  const val borderStyleDashed = "dashed"
  const val borderStyleDotted = "dotted"
  const val borderStyleNone = "none"
  const val borderStyleSolid = "solid"
  const val borderWidth0 = borderBase * 0f // 0
  const val borderWidth25 = borderBase * 0.25f // 1
  const val borderWidth50 = borderBase * 0.5f // 2
  const val borderWidth75 = borderBase * 0.75f // 3
  const val borderWidth100 = borderBase * 1f // 4
  const val borderWidth125 = borderBase * 1.25f // 5
  const val borderWidth150 = borderBase * 1.5f // 6
  const val borderWidth200 = borderBase * 2f // 8
}
