//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// OUDS core tokens version 1.9.0
// Generated by Tokenator

package com.orange.ouds.tokens.raw

object OudsGridRawTokens {
  const val GridColumnCount100 = 1
  const val GridColumnCount200 = 2
  const val GridColumnCount400 = 4
  const val GridColumnCount600 = 6
  const val GridColumnCount800 = 8
  const val GridColumnCount1000 = 10
  const val GridColumnCount1200 = 12
  const val GridColumnGap10 = DimensionRawTokens.DimensionBase * 0.25 // 1
  const val GridColumnGap100 = DimensionRawTokens.DimensionBase * 2 // 8
  const val GridColumnGap200 = DimensionRawTokens.DimensionBase * 4 // 16
  const val GridColumnGap300 = DimensionRawTokens.DimensionBase * 5 // 20
  const val GridColumnGap400 = DimensionRawTokens.DimensionBase * 6 // 24
  const val GridColumnGap600 = DimensionRawTokens.DimensionBase * 8 // 32
  const val GridColumnGap800 = DimensionRawTokens.DimensionBase * 10 // 40
  const val GridMargin100 = DimensionRawTokens.DimensionBase * 4 // 16
  const val GridMargin300 = DimensionRawTokens.DimensionBase * 6 // 24
  const val GridMargin400 = DimensionRawTokens.DimensionBase * 7 // 28
  const val GridMargin500 = DimensionRawTokens.DimensionBase * 8 // 32
  const val GridMargin600 = DimensionRawTokens.DimensionBase * 9 // 36
  const val GridMargin700 = DimensionRawTokens.DimensionBase * 10 // 40
  const val GridMargin1000 = DimensionRawTokens.DimensionBase * 13 // 52
  const val GridMargin1100 = DimensionRawTokens.DimensionBase * 14 // 56
  const val GridMargin1700 = DimensionRawTokens.DimensionBase * 20 // 80
  const val GridMargin2500 = DimensionRawTokens.DimensionBase * 28 // 112
  const val GridMaxWidthCompact = 599
  const val GridMaxWidthExtraCompact = 389
  const val GridMaxWidthMedium = 1200
  const val GridMinWidthCompact = 390
  const val GridMinWidthExtraCompact = 320
  const val GridMinWidthMedium = 600
}
