//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// OUDS core tokens version 1.9.0
// Generated by Tokenator

package com.orange.ouds.tokens.raw

object OudsDimensionRawTokens {
  const val DimensionBase = 4
  const val Dimension0 = DimensionBase * 0f // 0
  const val Dimension50 = DimensionBase * 1f // 4
  const val Dimension100 = DimensionBase * 2f // 8
  const val Dimension150 = DimensionBase * 3f // 12
  const val Dimension200 = DimensionBase * 4f // 16
  const val Dimension250 = DimensionBase * 5f // 20
  const val Dimension300 = DimensionBase * 6f // 24
  const val Dimension350 = DimensionBase * 7f // 28
  const val Dimension400 = DimensionBase * 8f // 32
  const val Dimension450 = DimensionBase * 9f // 36
  const val Dimension500 = DimensionBase * 10f // 40
  const val Dimension550 = DimensionBase * 11f // 44
  const val Dimension600 = DimensionBase * 12f // 48
  const val Dimension650 = DimensionBase * 13f // 52
  const val Dimension700 = DimensionBase * 14f // 56
  const val Dimension750 = DimensionBase * 15f // 60
  const val Dimension800 = DimensionBase * 16f // 64
  const val Dimension850 = DimensionBase * 17f // 68
  const val Dimension900 = DimensionBase * 18f // 72
  const val Dimension950 = DimensionBase * 19f // 76
  const val Dimension1000 = DimensionBase * 20f // 80
  const val Dimension1050 = DimensionBase * 21f // 84
  const val Dimension1100 = DimensionBase * 22f // 88
  const val Dimension1200 = DimensionBase * 24f // 96
  const val Dimension1250 = DimensionBase * 25f // 100
  const val Dimension1400 = DimensionBase * 28f // 112
  const val Dimension1600 = DimensionBase * 32f // 128
  const val Dimension1800 = DimensionBase * 36f // 144
  const val Dimension2000 = DimensionBase * 40f // 160
  const val Dimension2225 = DimensionBase * 50f // 200
  const val Dimension2500 = DimensionBase * 60f // 240
  const val Dimension3000 = DimensionBase * 80f // 320
  const val Dimension4000 = DimensionBase * 120f // 480
  const val Dimension5000 = DimensionBase * 140f // 560
  const val Dimension6000 = DimensionBase * 160f // 640
  const val Dimension7000 = DimensionBase * 180f // 720
  const val Dimension9000 = DimensionBase * 220f // 880
  const val Dimension11000 = DimensionBase * 260f // 1040
  const val DimensionOutOfSystem25 = DimensionBase * 0.25f // 1
  const val DimensionOutOfSystem50 = DimensionBase * 0.5f // 2
  const val DimensionOutOfSystem75 = DimensionBase * 0.75f // 3
  const val DimensionOutOfSystem150 = DimensionBase * 1.5f // 6
  const val DimensionOutOfSystem250 = DimensionBase * 2.5f // 10
}
