//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// OUDS core tokens version 1.9.0
// Generated by Tokenator

package com.orange.ouds.tokens.raw

object OudsFontRawTokens {
  const val FontLetterSpacing150 = 0.18f
  const val FontLetterSpacing175 = 0.19f
  const val FontLetterSpacing200 = 0.17f
  const val FontLetterSpacing250 = 0.2f
  const val FontLetterSpacing300 = 0.18f
  const val FontLetterSpacing350 = 0f
  const val FontLetterSpacing450 = -0.12f
  const val FontLetterSpacing550 = -0.28f
  const val FontLetterSpacing650 = -0.32f
  const val FontLetterSpacing750 = -0.36f
  const val FontLetterSpacing850 = -0.4f
  const val FontLetterSpacing950 = -0.55f
  const val FontLetterSpacing1050 = -0.6f
  const val FontLetterSpacing1150 = -0.65f
  const val FontLetterSpacing1250 = -0.7f
  const val FontLetterSpacing1450 = -0.96f
  const val FontLetterSpacing1850 = -1.08f
  const val FontLineHeight250 = 16
  const val FontLineHeight350 = 20
  const val FontLineHeight450 = 24
  const val FontLineHeight550 = 28
  const val FontLineHeight650 = 32
  const val FontLineHeight750 = 36
  const val FontLineHeight850 = 40
  const val FontLineHeight950 = 44
  const val FontLineHeight1050 = 48
  const val FontLineHeight1150 = 52
  const val FontLineHeight1250 = 56
  const val FontLineHeight1350 = 60
  const val FontLineHeight1450 = 64
  const val FontLineHeight1850 = 72
  const val FontLineHeight2050 = 80
  const val FontSize150 = 12
  const val FontSize175 = 13
  const val FontSize200 = 14
  const val FontSize250 = 16
  const val FontSize300 = 18
  const val FontSize350 = 20
  const val FontSize450 = 24
  const val FontSize550 = 28
  const val FontSize650 = 32
  const val FontSize750 = 36
  const val FontSize850 = 40
  const val FontSize950 = 44
  const val FontSize1050 = 48
  const val FontSize1150 = 52
  const val FontSize1250 = 56
  const val FontSize1450 = 64
  const val FontSize1850 = 72
  const val FontWeight100 = 100
  const val FontWeight200 = 200
  const val FontWeight300 = 300
  const val FontWeight400 = 400
  const val FontWeight500 = 500
  const val FontWeight600 = 600
  const val FontWeight700 = 700
  const val FontWeight800 = 800
  const val FontWeight900 = 900
  const val FontWeight950 = 950
}
