//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Android core tokens version 1.0.0
// Generated by Tokenator

package com.orange.ouds.tokens.raw

object OudsElevationRawTokens {
  const val Elevation0 = 0f
  const val Elevation1 = 1f
  const val Elevation2 = 3f
  const val Elevation3 = 6f
  const val Elevation4 = 8f
  const val Elevation5 = 12f
}
