//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Orange Compact brand tokens version 2.6.0
// Generated by Tokenator

package com.orange.ouds.theme.orangecompact.tokens.semantic

import androidx.compose.ui.graphics.Color
import com.orange.ouds.theme.orange.tokens.raw.OrangeColorRawTokens
import com.orange.ouds.theme.tokens.semantic.OudsColorAiSemanticTokens

internal data class OrangeCompactColorAiSemanticTokens(
    override val aiPrimaryDark: Color = OrangeColorRawTokens.ColorOrange500,
    override val aiPrimaryLight: Color = OrangeColorRawTokens.ColorOrange550,
    override val aiQuaternaryDark: Color = OrangeColorRawTokens.ColorDecorativeSky400,
    override val aiQuaternaryLight: Color = OrangeColorRawTokens.ColorDecorativeSky400,
    override val aiSecondaryDark: Color = OrangeColorRawTokens.ColorDecorativeShockingPink200,
    override val aiSecondaryLight: Color = OrangeColorRawTokens.ColorDecorativeShockingPink200,
    override val aiTertiaryDark: Color = OrangeColorRawTokens.ColorDecorativeAmethyst400,
    override val aiTertiaryLight: Color = OrangeColorRawTokens.ColorDecorativeAmethyst400
) : OudsColorAiSemanticTokens
