//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Orange Compact brand tokens version 2.4.0
// Generated by Tokenator

package com.orange.ouds.theme.orangecompact.tokens.semantic

import androidx.compose.ui.graphics.Color
import com.orange.ouds.theme.orange.tokens.raw.OrangeColorRawTokens
import com.orange.ouds.theme.tokens.semantic.OudsColorBorderSemanticTokens
import com.orange.ouds.tokens.raw.OudsColorRawTokens

internal data class OrangeCompactColorBorderSemanticTokens(
    override val borderBrandPrimaryDark: Color = OrangeColorRawTokens.ColorOrange500,
    override val borderBrandPrimaryLight: Color = OrangeColorRawTokens.ColorOrange550,
    override val borderBrandSecondaryDark: Color = Color.Unspecified,
    override val borderBrandSecondaryLight: Color = Color.Unspecified,
    override val borderBrandTertiaryDark: Color = Color.Unspecified,
    override val borderBrandTertiaryLight: Color = Color.Unspecified,
    override val borderDefaultDark: Color = OudsColorRawTokens.ColorOpacityWhite200,
    override val borderDefaultLight: Color = OudsColorRawTokens.ColorOpacityBlack200,
    override val borderEmphasizedDark: Color = OudsColorRawTokens.ColorFunctionalGrayLight160,
    override val borderEmphasizedLight: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val borderFocusDark: Color = OudsColorRawTokens.ColorFunctionalGrayLight160,
    override val borderFocusInsetDark: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val borderFocusInsetLight: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val borderFocusLight: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val borderMinimalDark: Color = OudsColorRawTokens.ColorOpacityWhite40,
    override val borderMinimalLight: Color = OudsColorRawTokens.ColorOpacityBlack40,
    override val borderMutedDark: Color = OudsColorRawTokens.ColorOpacityWhite80,
    override val borderMutedLight: Color = OudsColorRawTokens.ColorOpacityBlack80,
    override val borderOnBrandPrimaryDark: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val borderOnBrandPrimaryLight: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val borderOnBrandSecondaryDark: Color = Color.Unspecified,
    override val borderOnBrandSecondaryLight: Color = Color.Unspecified,
    override val borderOnBrandTertiaryDark: Color = Color.Unspecified,
    override val borderOnBrandTertiaryLight: Color = Color.Unspecified,
    override val borderStatusAccentDark: Color = OrangeColorRawTokens.ColorOrange500,
    override val borderStatusAccentLight: Color = OrangeColorRawTokens.ColorOrange500,
    override val borderStatusInfoDark: Color = OudsColorRawTokens.ColorFunctionalDodgerBlue300,
    override val borderStatusInfoLight: Color = OudsColorRawTokens.ColorFunctionalDodgerBlue700,
    override val borderStatusNegativeDark: Color = OudsColorRawTokens.ColorFunctionalScarlet300,
    override val borderStatusNegativeLight: Color = OudsColorRawTokens.ColorFunctionalScarlet600,
    override val borderStatusPositiveDark: Color = OudsColorRawTokens.ColorFunctionalMalachite300,
    override val borderStatusPositiveLight: Color = OudsColorRawTokens.ColorFunctionalMalachite750,
    override val borderStatusWarningDark: Color = OudsColorRawTokens.ColorFunctionalSun300,
    override val borderStatusWarningLight: Color = OudsColorRawTokens.ColorFunctionalSun500
) : OudsColorBorderSemanticTokens
