//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Orange Business Tools brand tokens version 2.3.0
// Generated by Tokenator

package com.orange.ouds.theme.orangecompact.tokens.semantic

import com.orange.ouds.theme.tokens.semantic.OudsFontSemanticTokens
import com.orange.ouds.tokens.raw.OudsFontRawTokens

internal data class OrangeCompactFontSemanticTokens(
    override val letterSpacingBodyLargeMobile: Float = OudsFontRawTokens.FontLetterSpacing200,
    override val letterSpacingBodyLargeTablet: Float = OudsFontRawTokens.FontLetterSpacing200,
    override val letterSpacingBodyMediumMobile: Float = OudsFontRawTokens.FontLetterSpacing175,
    override val letterSpacingBodyMediumTablet: Float = OudsFontRawTokens.FontLetterSpacing175,
    override val letterSpacingBodySmallMobile: Float = OudsFontRawTokens.FontLetterSpacing150,
    override val letterSpacingBodySmallTablet: Float = OudsFontRawTokens.FontLetterSpacing150,
    override val letterSpacingDisplayLargeMobile: Float = OudsFontRawTokens.FontLetterSpacing750,
    override val letterSpacingDisplayLargeTablet: Float = OudsFontRawTokens.FontLetterSpacing750,
    override val letterSpacingDisplayMediumMobile: Float = OudsFontRawTokens.FontLetterSpacing650,
    override val letterSpacingDisplayMediumTablet: Float = OudsFontRawTokens.FontLetterSpacing650,
    override val letterSpacingDisplaySmallMobile: Float = OudsFontRawTokens.FontLetterSpacing550,
    override val letterSpacingDisplaySmallTablet: Float = OudsFontRawTokens.FontLetterSpacing550,
    override val letterSpacingHeadingLargeMobile: Float = OudsFontRawTokens.FontLetterSpacing350,
    override val letterSpacingHeadingLargeTablet: Float = OudsFontRawTokens.FontLetterSpacing350,
    override val letterSpacingHeadingMediumMobile: Float = OudsFontRawTokens.FontLetterSpacing300,
    override val letterSpacingHeadingMediumTablet: Float = OudsFontRawTokens.FontLetterSpacing300,
    override val letterSpacingHeadingSmallMobile: Float = OudsFontRawTokens.FontLetterSpacing250,
    override val letterSpacingHeadingSmallTablet: Float = OudsFontRawTokens.FontLetterSpacing250,
    override val letterSpacingHeadingXlargeMobile: Float = OudsFontRawTokens.FontLetterSpacing450,
    override val letterSpacingHeadingXlargeTablet: Float = OudsFontRawTokens.FontLetterSpacing450,
    override val letterSpacingLabelLarge: Float = OudsFontRawTokens.FontLetterSpacing200,
    override val letterSpacingLabelMedium: Float = OudsFontRawTokens.FontLetterSpacing175,
    override val letterSpacingLabelSmall: Float = OudsFontRawTokens.FontLetterSpacing150,
    override val letterSpacingLabelXlarge: Float = OudsFontRawTokens.FontLetterSpacing250,
    override val lineHeightBodyLargeMobile: Int = OudsFontRawTokens.FontLineHeight350,
    override val lineHeightBodyLargeTablet: Int = OudsFontRawTokens.FontLineHeight350,
    override val lineHeightBodyMediumMobile: Int = OudsFontRawTokens.FontLineHeight250,
    override val lineHeightBodyMediumTablet: Int = OudsFontRawTokens.FontLineHeight250,
    override val lineHeightBodySmallMobile: Int = OudsFontRawTokens.FontLineHeight250,
    override val lineHeightBodySmallTablet: Int = OudsFontRawTokens.FontLineHeight250,
    override val lineHeightDisplayLargeMobile: Int = OudsFontRawTokens.FontLineHeight950,
    override val lineHeightDisplayLargeTablet: Int = OudsFontRawTokens.FontLineHeight950,
    override val lineHeightDisplayMediumMobile: Int = OudsFontRawTokens.FontLineHeight850,
    override val lineHeightDisplayMediumTablet: Int = OudsFontRawTokens.FontLineHeight850,
    override val lineHeightDisplaySmallMobile: Int = OudsFontRawTokens.FontLineHeight750,
    override val lineHeightDisplaySmallTablet: Int = OudsFontRawTokens.FontLineHeight750,
    override val lineHeightHeadingLargeMobile: Int = OudsFontRawTokens.FontLineHeight550,
    override val lineHeightHeadingLargeTablet: Int = OudsFontRawTokens.FontLineHeight550,
    override val lineHeightHeadingMediumMobile: Int = OudsFontRawTokens.FontLineHeight450,
    override val lineHeightHeadingMediumTablet: Int = OudsFontRawTokens.FontLineHeight450,
    override val lineHeightHeadingSmallMobile: Int = OudsFontRawTokens.FontLineHeight450,
    override val lineHeightHeadingSmallTablet: Int = OudsFontRawTokens.FontLineHeight450,
    override val lineHeightHeadingXlargeMobile: Int = OudsFontRawTokens.FontLineHeight650,
    override val lineHeightHeadingXlargeTablet: Int = OudsFontRawTokens.FontLineHeight650,
    override val lineHeightLabelLarge: Int = OudsFontRawTokens.FontLineHeight350,
    override val lineHeightLabelMedium: Int = OudsFontRawTokens.FontLineHeight250,
    override val lineHeightLabelSmall: Int = OudsFontRawTokens.FontLineHeight250,
    override val lineHeightLabelXlarge: Int = OudsFontRawTokens.FontLineHeight450,
    override val sizeBodyLargeMobile: Int = OudsFontRawTokens.FontSize200,
    override val sizeBodyLargeTablet: Int = OudsFontRawTokens.FontSize200,
    override val sizeBodyMediumMobile: Int = OudsFontRawTokens.FontSize175,
    override val sizeBodyMediumTablet: Int = OudsFontRawTokens.FontSize175,
    override val sizeBodySmallMobile: Int = OudsFontRawTokens.FontSize150,
    override val sizeBodySmallTablet: Int = OudsFontRawTokens.FontSize150,
    override val sizeDisplayLargeMobile: Int = OudsFontRawTokens.FontSize750,
    override val sizeDisplayLargeTablet: Int = OudsFontRawTokens.FontSize750,
    override val sizeDisplayMediumMobile: Int = OudsFontRawTokens.FontSize650,
    override val sizeDisplayMediumTablet: Int = OudsFontRawTokens.FontSize650,
    override val sizeDisplaySmallMobile: Int = OudsFontRawTokens.FontSize550,
    override val sizeDisplaySmallTablet: Int = OudsFontRawTokens.FontSize550,
    override val sizeHeadingLargeMobile: Int = OudsFontRawTokens.FontSize350,
    override val sizeHeadingLargeTablet: Int = OudsFontRawTokens.FontSize350,
    override val sizeHeadingMediumMobile: Int = OudsFontRawTokens.FontSize300,
    override val sizeHeadingMediumTablet: Int = OudsFontRawTokens.FontSize300,
    override val sizeHeadingSmallMobile: Int = OudsFontRawTokens.FontSize250,
    override val sizeHeadingSmallTablet: Int = OudsFontRawTokens.FontSize250,
    override val sizeHeadingXlargeMobile: Int = OudsFontRawTokens.FontSize450,
    override val sizeHeadingXlargeTablet: Int = OudsFontRawTokens.FontSize450,
    override val sizeLabelLarge: Int = OudsFontRawTokens.FontSize200,
    override val sizeLabelMedium: Int = OudsFontRawTokens.FontSize175,
    override val sizeLabelSmall: Int = OudsFontRawTokens.FontSize150,
    override val sizeLabelXlarge: Int = OudsFontRawTokens.FontSize250,
    override val weightBodyDefault: Int = OudsFontRawTokens.FontWeight400,
    override val weightBodyModerate: Int = OudsFontRawTokens.FontWeight500,
    override val weightBodyStrong: Int = OudsFontRawTokens.FontWeight700,
    override val weightDisplay: Int = OudsFontRawTokens.FontWeight700,
    override val weightHeading: Int = OudsFontRawTokens.FontWeight700,
    override val weightLabelDefault: Int = OudsFontRawTokens.FontWeight400,
    override val weightLabelModerate: Int = OudsFontRawTokens.FontWeight500,
    override val weightLabelStrong: Int = OudsFontRawTokens.FontWeight700,
    override val weightSystemDefault: Int = OudsFontRawTokens.FontWeight400,
    override val weightSystemModerate: Int = OudsFontRawTokens.FontWeight500,
    override val weightSystemStrong: Int = OudsFontRawTokens.FontWeight700
) : OudsFontSemanticTokens
