//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

package com.orange.ouds.theme.whitelabel.tokens.semantic

import androidx.compose.ui.graphics.Color
import com.orange.ouds.theme.tokens.semantic.OudsColorRepositorySemanticTokens
import com.orange.ouds.theme.whitelabel.tokens.raw.WhiteLabelColorRawTokens
import com.orange.ouds.tokens.raw.ColorRawTokens

data class WhiteLabelColorRepositorySemanticTokens(
    override val repositoryPrimaryLowest: Color = Color(0x00ff0000),
    override val repositoryPrimaryLower: Color = Color(0x00ff0000),
    override val repositoryPrimaryLow: Color = WhiteLabelColorRawTokens.colorBlue500,
    override val repositoryPrimaryDefault: Color = WhiteLabelColorRawTokens.colorBlue600,
    override val repositoryPrimaryHigh: Color = Color(0x00ff0000),
    override val repositoryPrimaryHigher: Color = Color(0x00ff0000),
    override val repositoryPrimaryHighest: Color = Color(0x00ff0000),
    override val repositorySecondaryLowest: Color = Color(0x00ff0000),
    override val repositorySecondaryLower: Color = Color(0x00ff0000),
    override val repositorySecondaryLow: Color = Color(0x00ff0000),
    override val repositorySecondaryDefault: Color = Color(0x00ff0000),
    override val repositorySecondaryHigh: Color = Color(0x00ff0000),
    override val repositorySecondaryHigher: Color = Color(0x00ff0000),
    override val repositorySecondaryHighest: Color = Color(0x00ff0000),
    override val repositoryTertiaryLowest: Color = Color(0x00ff0000),
    override val repositoryTertiaryLower: Color = Color(0x00ff0000),
    override val repositoryTertiaryLow: Color = Color(0x00ff0000),
    override val repositoryTertiaryDefault: Color = Color(0x00ff0000),
    override val repositoryTertiaryHigh: Color = Color(0x00ff0000),
    override val repositoryTertiaryHigher: Color = Color(0x00ff0000),
    override val repositoryTertiaryHighest: Color = Color(0x00ff0000),
    override val repositoryNeutralMutedWhite: Color = ColorRawTokens.colorFunctionalWhite,
    override val repositoryNeutralMutedLowest: Color = ColorRawTokens.colorFunctionalGrayLight80,
    override val repositoryNeutralMutedLower: Color = ColorRawTokens.colorFunctionalGrayLight160,
    override val repositoryNeutralMutedLow: Color = Color(0x00ff0000),
    override val repositoryNeutralMutedMedium: Color = Color(0x00ff0000),
    override val repositoryNeutralMutedHigh: Color = Color(0x00ff0000),
    override val repositoryNeutralMutedHigher: Color = Color(0x00ff0000),
    override val repositoryNeutralMutedHighest: Color = Color(0x00ff0000),
    override val repositoryNeutralEmphasizedLowest: Color = Color(0x00ff0000),
    override val repositoryNeutralEmphasizedLower: Color = Color(0x00ff0000),
    override val repositoryNeutralEmphasizedLow: Color = Color(0x00ff0000),
    override val repositoryNeutralEmphasizedMedium: Color = ColorRawTokens.colorFunctionalGrayDark640,
    override val repositoryNeutralEmphasizedHigh: Color = ColorRawTokens.colorFunctionalGrayDark720,
    override val repositoryNeutralEmphasizedHigher: Color = ColorRawTokens.colorFunctionalGrayDark800,
    override val repositoryNeutralEmphasizedHighest: Color = ColorRawTokens.colorFunctionalGrayDark880,
    override val repositoryNeutralEmphasizedBlack: Color = ColorRawTokens.colorFunctionalBlack,
    override val repositoryWarningLowest: Color = ColorRawTokens.colorFunctionalSun100,
    override val repositoryWarningLower: Color = Color(0x00ff0000),
    override val repositoryWarningLow: Color = ColorRawTokens.colorFunctionalSun300,
    override val repositoryWarningDefault: Color = ColorRawTokens.colorFunctionalSun500,
    override val repositoryWarningHigh: Color = Color(0x00ff0000),
    override val repositoryWarningHigher: Color = Color(0x00ff0000),
    override val repositoryWarningHighest: Color = ColorRawTokens.colorFunctionalSun900,
    override val repositoryNegativeLowest: Color = ColorRawTokens.colorFunctionalScarlet100,
    override val repositoryNegativeLower: Color = ColorRawTokens.colorFunctionalScarlet200,
    override val repositoryNegativeLow: Color = ColorRawTokens.colorFunctionalScarlet300,
    override val repositoryNegativeDefault: Color = ColorRawTokens.colorFunctionalScarlet600,
    override val repositoryNegativeHigh: Color = ColorRawTokens.colorFunctionalScarlet700,
    override val repositoryNegativeHigher: Color = ColorRawTokens.colorFunctionalScarlet800,
    override val repositoryNegativeHighest: Color = ColorRawTokens.colorFunctionalScarlet900,
    override val repositoryPositiveLowest: Color = ColorRawTokens.colorFunctionalMalachite100,
    override val repositoryPositiveLower: Color = Color(0x00ff0000),
    override val repositoryPositiveLow: Color = ColorRawTokens.colorFunctionalMalachite300,
    override val repositoryPositiveDefault: Color = ColorRawTokens.colorFunctionalMalachite500,
    override val repositoryPositiveHigh: Color = ColorRawTokens.colorFunctionalMalachite600,
    override val repositoryPositiveHigher: Color = Color(0x00ff0000),
    override val repositoryPositiveHighest: Color = ColorRawTokens.colorFunctionalMalachite900,
    override val repositoryInfoLowest: Color = ColorRawTokens.colorFunctionalDodgerBlue100,
    override val repositoryInfoLower: Color = Color(0x00ff0000),
    override val repositoryInfoLow: Color = ColorRawTokens.colorFunctionalDodgerBlue300,
    override val repositoryInfoDefault: Color = ColorRawTokens.colorFunctionalDodgerBlue500,
    override val repositoryInfoHigh: Color = Color(0x00ff0000),
    override val repositoryInfoHigher: Color = Color(0x00ff0000),
    override val repositoryInfoHighest: Color = ColorRawTokens.colorFunctionalDodgerBlue900,
    override val repositoryAccentLowest: Color = WhiteLabelColorRawTokens.colorWarmGray100,
    override val repositoryAccentLower: Color = Color(0x00ff0000),
    override val repositoryAccentLow: Color = ColorRawTokens.colorFunctionalSun300,
    override val repositoryAccentDefault: Color = ColorRawTokens.colorFunctionalSun500,
    override val repositoryAccentHigh: Color = Color(0x00ff0000),
    override val repositoryAccentHigher: Color = Color(0x00ff0000),
    override val repositoryAccentHighest: Color = WhiteLabelColorRawTokens.colorWarmGray900,
    override val repositoryOpacityAccent: Color = WhiteLabelColorRawTokens.colorOpacityWarmGray,
    override val repositoryOpacityNegative: Color = ColorRawTokens.colorOpacityScarlet,
    override val repositoryOpacityWarning: Color = ColorRawTokens.colorOpacitySun,
    override val repositoryOpacityPositive: Color = ColorRawTokens.colorOpacityMalachite,
    override val repositoryOpacityInfo: Color = ColorRawTokens.colorOpacityDodgerBlue,
    override val repositoryOpacityBlackTransparent: Color = ColorRawTokens.colorOpacityBlack0,
    override val repositoryOpacityBlackLowest: Color = ColorRawTokens.colorOpacityBlack40,
    override val repositoryOpacityBlackLower: Color = ColorRawTokens.colorOpacityBlack80,
    override val repositoryOpacityBlackLow: Color = ColorRawTokens.colorOpacityBlack120,
    override val repositoryOpacityBlackMediumLow: Color = ColorRawTokens.colorOpacityBlack200,
    override val repositoryOpacityBlackMedium: Color = ColorRawTokens.colorOpacityBlack280,
    override val repositoryOpacityBlackMediumHigh: Color = ColorRawTokens.colorOpacityBlack440,
    override val repositoryOpacityBlackHigh: Color = ColorRawTokens.colorOpacityBlack520,
    override val repositoryOpacityBlackHigher: Color = ColorRawTokens.colorOpacityBlack680,
    override val repositoryOpacityBlackHighest: Color = ColorRawTokens.colorOpacityBlack840,
    override val repositoryOpacityWhiteTransparent: Color = ColorRawTokens.colorOpacityWhite0,
    override val repositoryOpacityWhiteLowest: Color = ColorRawTokens.colorOpacityWhite40,
    override val repositoryOpacityWhiteLower: Color = ColorRawTokens.colorOpacityWhite80,
    override val repositoryOpacityWhiteLow: Color = ColorRawTokens.colorOpacityWhite120,
    override val repositoryOpacityWhiteMediumLow: Color = ColorRawTokens.colorOpacityWhite200,
    override val repositoryOpacityWhiteMedium: Color = ColorRawTokens.colorOpacityWhite440,
    override val repositoryOpacityWhiteHigh: Color = ColorRawTokens.colorOpacityWhite640,
    override val repositoryOpacityWhiteHigher: Color = ColorRawTokens.colorOpacityWhite800,
    override val repositoryOpacityWhiteHighest: Color = ColorRawTokens.colorOpacityWhite920,
    override val repositoryOpacityPrimaryTransparent: Color = Color(0x00ff0000),
    override val repositoryOpacityPrimaryLowest: Color = Color(0x00ff0000),
    override val repositoryOpacityPrimaryLower: Color = Color(0x00ff0000),
    override val repositoryOpacityPrimaryLow: Color = Color(0x00ff0000),
    override val repositoryOpacityPrimaryMedium: Color = Color(0x00ff0000),
    override val repositoryOpacityPrimaryHigh: Color = Color(0x00ff0000),
    override val repositoryOpacityPrimaryHigher: Color = Color(0x00ff0000),
    override val repositoryOpacityPrimaryHighest: Color = Color(0x00ff0000)
) : OudsColorRepositorySemanticTokens
