//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Generated by Tokenator

package com.orange.ouds.theme

object OudsVersion {
    object Component {
        const val Badge = "1.2.0"
        const val BulletList = "1.0.0"
        const val Button = "3.2.0"
        const val Checkbox = "2.3.0"
        const val Chip = "1.3.0"
        const val Divider = "1.0.0"
        const val Link = "2.2.0"
        const val RadioButton = "1.3.0"
        const val Switch = "1.4.0"
        const val Tag = "1.4.0"
        const val TextInput = "1.3.0"
    }
    object Tokens {
        const val OudsCore = "1.8.0"
        const val AndroidCore = "1.0.0"
        const val AndroidSystem = "1.2.0"
        const val OrangeCore = "1.2.0"
        const val OrangeBrand = "2.1.0"
        const val SoshCore = "1.2.0"
        const val SoshBrand = "2.1.0"
        const val WireframeCore = "1.3.0"
        const val WireframeBrand = "2.1.0"
    }
}
