//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Sosh brand tokens version 2.5.0
// Generated by Tokenator

package com.orange.ouds.theme.sosh.tokens.semantic

import androidx.compose.ui.graphics.Color
import com.orange.ouds.theme.sosh.tokens.raw.SoshColorRawTokens
import com.orange.ouds.theme.tokens.semantic.OudsColorOpacitySemanticTokens

internal data class SoshColorOpacitySemanticTokens(
    override val opacityLowerDark: Color = SoshColorRawTokens.ColorOpacityWhite80,
    override val opacityLowerLight: Color = SoshColorRawTokens.ColorOpacityBlack80,
    override val opacityLowestDark: Color = SoshColorRawTokens.ColorOpacityWhite40,
    override val opacityLowestLight: Color = SoshColorRawTokens.ColorOpacityBlack40,
    override val opacityTransparentDark: Color = SoshColorRawTokens.ColorOpacityWhite0,
    override val opacityTransparentLight: Color = SoshColorRawTokens.ColorOpacityBlack0
) : OudsColorOpacitySemanticTokens
