//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Sosh brand tokens version 2.5.0
// Generated by Tokenator

package com.orange.ouds.theme.sosh.tokens.semantic

import androidx.compose.ui.graphics.Color
import com.orange.ouds.theme.sosh.tokens.raw.SoshColorRawTokens
import com.orange.ouds.theme.tokens.semantic.OudsColorContentSemanticTokens
import com.orange.ouds.tokens.raw.OudsColorRawTokens

internal data class SoshColorContentSemanticTokens(
    override val contentBrandPrimaryDark: Color = SoshColorRawTokens.ColorRaspberry300,
    override val contentBrandPrimaryLight: Color = SoshColorRawTokens.ColorRaspberry500,
    override val contentBrandSecondaryDark: Color = SoshColorRawTokens.ColorLochmaraLight640,
    override val contentBrandSecondaryLight: Color = SoshColorRawTokens.ColorLochmaraDark240,
    override val contentBrandTertiaryDark: Color = SoshColorRawTokens.ColorTurbo300,
    override val contentBrandTertiaryLight: Color = SoshColorRawTokens.ColorTurbo500,
    override val contentDefaultDark: Color = SoshColorRawTokens.ColorFunctionalGrayLight160,
    override val contentDefaultLight: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val contentDisabledDark: Color = SoshColorRawTokens.ColorOpacityWhite200,
    override val contentDisabledLight: Color = SoshColorRawTokens.ColorOpacityBlack200,
    override val contentInverseDark: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val contentInverseLight: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val contentMutedDark: Color = SoshColorRawTokens.ColorOpacityWhite640,
    override val contentMutedLight: Color = SoshColorRawTokens.ColorOpacityBlack720,
    override val contentOnActionDisabledDark: Color = SoshColorRawTokens.ColorLochmaraDark960,
    override val contentOnActionDisabledLight: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val contentOnActionEnabledDark: Color = SoshColorRawTokens.ColorLochmaraDark960,
    override val contentOnActionEnabledLight: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val contentOnActionFocusDark: Color = SoshColorRawTokens.ColorLochmaraDark960,
    override val contentOnActionFocusLight: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val contentOnActionHighlightedDark: Color = SoshColorRawTokens.ColorLochmaraDark960,
    override val contentOnActionHighlightedLight: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val contentOnActionHoverDark: Color = SoshColorRawTokens.ColorLochmaraDark960,
    override val contentOnActionHoverLight: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val contentOnActionLoadingDark: Color = SoshColorRawTokens.ColorLochmaraDark960,
    override val contentOnActionLoadingLight: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val contentOnActionPressedDark: Color = SoshColorRawTokens.ColorLochmaraDark960,
    override val contentOnActionPressedLight: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val contentOnActionSelectedDark: Color = SoshColorRawTokens.ColorLochmaraDark960,
    override val contentOnActionSelectedLight: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val contentOnBrandPrimaryDark: Color = SoshColorRawTokens.ColorLochmaraDark960,
    override val contentOnBrandPrimaryLight: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val contentOnBrandSecondaryDark: Color = SoshColorRawTokens.ColorLochmaraDark960,
    override val contentOnBrandSecondaryLight: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val contentOnBrandTertiaryDark: Color = SoshColorRawTokens.ColorLochmaraDark960,
    override val contentOnBrandTertiaryLight: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val contentOnStatusAccentEmphasizedDark: Color = SoshColorRawTokens.ColorLochmaraDark960,
    override val contentOnStatusAccentEmphasizedLight: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val contentOnStatusAccentMutedDark: Color = SoshColorRawTokens.ColorFunctionalGrayLight160,
    override val contentOnStatusAccentMutedLight: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val contentOnStatusInfoEmphasizedDark: Color = SoshColorRawTokens.ColorLochmaraDark960,
    override val contentOnStatusInfoEmphasizedLight: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val contentOnStatusInfoMutedDark: Color = SoshColorRawTokens.ColorFunctionalGrayLight160,
    override val contentOnStatusInfoMutedLight: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val contentOnStatusNegativeEmphasizedDark: Color = SoshColorRawTokens.ColorLochmaraDark960,
    override val contentOnStatusNegativeEmphasizedLight: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val contentOnStatusNegativeMutedDark: Color = SoshColorRawTokens.ColorFunctionalGrayLight160,
    override val contentOnStatusNegativeMutedLight: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val contentOnStatusPositiveEmphasizedDark: Color = SoshColorRawTokens.ColorLochmaraDark960,
    override val contentOnStatusPositiveEmphasizedLight: Color = OudsColorRawTokens.ColorFunctionalWhite,
    override val contentOnStatusPositiveMutedDark: Color = SoshColorRawTokens.ColorFunctionalGrayLight160,
    override val contentOnStatusPositiveMutedLight: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val contentOnStatusWarningEmphasizedDark: Color = SoshColorRawTokens.ColorLochmaraDark960,
    override val contentOnStatusWarningEmphasizedLight: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val contentOnStatusWarningMutedDark: Color = SoshColorRawTokens.ColorFunctionalGrayLight160,
    override val contentOnStatusWarningMutedLight: Color = OudsColorRawTokens.ColorFunctionalBlack,
    override val contentStatusAccentDark: Color = SoshColorRawTokens.ColorRaspberry300,
    override val contentStatusAccentLight: Color = SoshColorRawTokens.ColorRaspberry500,
    override val contentStatusInfoDark: Color = SoshColorRawTokens.ColorLochmaraLight400,
    override val contentStatusInfoLight: Color = SoshColorRawTokens.ColorLochmaraDark240,
    override val contentStatusNegativeDark: Color = OudsColorRawTokens.ColorFunctionalScarlet300,
    override val contentStatusNegativeLight: Color = OudsColorRawTokens.ColorFunctionalScarlet600,
    override val contentStatusPositiveDark: Color = OudsColorRawTokens.ColorFunctionalMalachite300,
    override val contentStatusPositiveLight: Color = OudsColorRawTokens.ColorFunctionalMalachite750,
    override val contentStatusWarningDark: Color = SoshColorRawTokens.ColorTurbo300,
    override val contentStatusWarningLight: Color = SoshColorRawTokens.ColorTurbo750
) : OudsColorContentSemanticTokens
