//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Wireframe brand tokens version 2.1.0
// Generated by Tokenator

package com.orange.ouds.theme.wireframe.tokens.semantic

import androidx.compose.ui.graphics.Color
import com.orange.ouds.theme.wireframe.tokens.raw.WireframeColorRawTokens
import com.orange.ouds.theme.tokens.semantic.OudsColorBgSemanticTokens
import com.orange.ouds.tokens.raw.ColorRawTokens

data class WireframeColorBgSemanticTokens(
    override val bgInverseHighDark: Color = WireframeColorRawTokens.colorFunctionalGrayLight160,
    override val bgInverseHighLight: Color = WireframeColorRawTokens.colorFunctionalGrayDark800,
    override val bgInverseLowDark: Color = WireframeColorRawTokens.colorFunctionalGrayDark720,
    override val bgInverseLowLight: Color = WireframeColorRawTokens.colorFunctionalGrayDark800,
    override val bgPrimaryDark: Color = WireframeColorRawTokens.colorFunctionalGrayDark880,
    override val bgPrimaryLight: Color = ColorRawTokens.colorFunctionalWhite,
    override val bgSecondaryDark: Color = WireframeColorRawTokens.colorFunctionalGrayDark800,
    override val bgSecondaryLight: Color = WireframeColorRawTokens.colorFunctionalGrayLight80,
    override val bgTertiaryDark: Color = WireframeColorRawTokens.colorRustyRed1000,
    override val bgTertiaryLight: Color = WireframeColorRawTokens.colorRustyRed50
) : OudsColorBgSemanticTokens
