//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Wireframe brand tokens version 1.5.0
// Generated by Tokenator

package com.orange.ouds.theme.wireframe.tokens.semantic

import androidx.compose.ui.graphics.Color
import com.orange.ouds.theme.tokens.semantic.OudsColorActionSemanticTokens
import com.orange.ouds.tokens.raw.ColorRawTokens

data class WireframeColorActionSemanticTokens(
    override val actionDisabledDark: Color = WframeColorRawTokens.colorOpacityWhite200,
    override val actionDisabledLight: Color = WframeColorRawTokens.colorOpacityBlack200,
    override val actionEnabledDark: Color = WframeColorRawTokens.colorRoyalBlue300,
    override val actionEnabledLight: Color = WframeColorRawTokens.colorRoyalBlue600,
    override val actionFocusDark: Color = WframeColorRawTokens.colorRoyalBlue200,
    override val actionFocusLight: Color = WframeColorRawTokens.colorRoyalBlue800,
    override val actionHighlightedDark: Color = WframeColorRawTokens.colorFunctionalGrayLight160,
    override val actionHighlightedLight: Color = WframeColorRawTokens.colorRoyalBlue800,
    override val actionHoverDark: Color = WframeColorRawTokens.colorRoyalBlue200,
    override val actionHoverLight: Color = WframeColorRawTokens.colorRoyalBlue800,
    override val actionLoadingDark: Color = WframeColorRawTokens.colorRoyalBlue100,
    override val actionLoadingLight: Color = WframeColorRawTokens.colorRoyalBlue900,
    override val actionNegativeEnabledDark: Color = ColorRawTokens.colorFunctionalScarlet300,
    override val actionNegativeEnabledLight: Color = ColorRawTokens.colorFunctionalScarlet600,
    override val actionNegativeFocusDark: Color = ColorRawTokens.colorFunctionalScarlet200,
    override val actionNegativeFocusLight: Color = ColorRawTokens.colorFunctionalScarlet700,
    override val actionNegativeHoverDark: Color = ColorRawTokens.colorFunctionalScarlet200,
    override val actionNegativeHoverLight: Color = ColorRawTokens.colorFunctionalScarlet700,
    override val actionNegativeLoadingDark: Color = ColorRawTokens.colorFunctionalScarlet100,
    override val actionNegativeLoadingLight: Color = ColorRawTokens.colorFunctionalScarlet800,
    override val actionNegativePressedDark: Color = ColorRawTokens.colorFunctionalScarlet100,
    override val actionNegativePressedLight: Color = ColorRawTokens.colorFunctionalScarlet800,
    override val actionPressedDark: Color = WframeColorRawTokens.colorRoyalBlue100,
    override val actionPressedLight: Color = WframeColorRawTokens.colorRoyalBlue900,
    override val actionSelectedDark: Color = WframeColorRawTokens.colorRoyalBlue300,
    override val actionSelectedLight: Color = WframeColorRawTokens.colorRoyalBlue600,
    override val actionSupportDisabledDark: Color = WframeColorRawTokens.colorOpacityWhite40,
    override val actionSupportDisabledLight: Color = WframeColorRawTokens.colorOpacityBlack40,
    override val actionSupportEnabledDark: Color = WframeColorRawTokens.colorOpacityWhite40,
    override val actionSupportEnabledLight: Color = WframeColorRawTokens.colorOpacityBlack40,
    override val actionSupportFocusDark: Color = WframeColorRawTokens.colorOpacityWhite80,
    override val actionSupportFocusLight: Color = WframeColorRawTokens.colorOpacityBlack80,
    override val actionSupportHoverDark: Color = WframeColorRawTokens.colorOpacityWhite80,
    override val actionSupportHoverLight: Color = WframeColorRawTokens.colorOpacityBlack80,
    override val actionSupportLoadingDark: Color = WframeColorRawTokens.colorOpacityWhite120,
    override val actionSupportLoadingLight: Color = WframeColorRawTokens.colorOpacityBlack120,
    override val actionSupportPressedDark: Color = WframeColorRawTokens.colorOpacityWhite120,
    override val actionSupportPressedLight: Color = WframeColorRawTokens.colorOpacityBlack120,
    override val actionVisitedDark: Color = ColorRawTokens.colorFunctionalAmethyst400,
    override val actionVisitedLight: Color = ColorRawTokens.colorFunctionalAmethyst600
) : OudsColorActionSemanticTokens
