//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Wireframe brand tokens version 1.6.0
// Generated by Tokenator

package com.orange.ouds.theme.wireframe.tokens.semantic

import androidx.compose.ui.graphics.Color
import com.orange.ouds.theme.wireframe.tokens.raw.WireframeColorRawTokens
import com.orange.ouds.theme.tokens.semantic.OudsColorOverlaySemanticTokens
import com.orange.ouds.tokens.raw.ColorRawTokens

data class WireframeColorOverlaySemanticTokens(
    override val overlayDefaultDark: Color = WireframeColorRawTokens.colorOpacityWhite80,
    override val overlayDefaultLight: Color = ColorRawTokens.colorFunctionalWhite,
    override val overlayDragDark: Color = WireframeColorRawTokens.colorOpacityWhite200,
    override val overlayDragLight: Color = WireframeColorRawTokens.colorOpacityBlack40,
    override val overlayEmphasizedDark: Color = WireframeColorRawTokens.colorFunctionalGrayLight160,
    override val overlayEmphasizedLight: Color = WireframeColorRawTokens.colorFunctionalGrayDark720,
    override val overlayModalDark: Color = WireframeColorRawTokens.colorFunctionalGrayDark720,
    override val overlayModalLight: Color = ColorRawTokens.colorFunctionalWhite
) : OudsColorOverlaySemanticTokens
