//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Wireframe brand tokens version 2.2.0
// Generated by Tokenator

package com.orange.ouds.theme.wireframe.tokens.semantic

import androidx.compose.ui.graphics.Color
import com.orange.ouds.theme.wireframe.tokens.raw.WireframeColorRawTokens
import com.orange.ouds.theme.tokens.semantic.OudsColorSurfaceSemanticTokens
import com.orange.ouds.tokens.raw.OudsColorRawTokens

data class WireframeColorSurfaceSemanticTokens(
    override val surfaceBrandPrimaryDark: Color = WireframeColorRawTokens.colorRoyalBlue300,
    override val surfaceBrandPrimaryLight: Color = WireframeColorRawTokens.colorRoyalBlue600,
    override val surfaceBrandSecondaryDark: Color = WireframeColorRawTokens.colorRustyRed400,
    override val surfaceBrandSecondaryLight: Color = WireframeColorRawTokens.colorRustyRed600,
    override val surfaceBrandTertiaryDark: Color = Color.Unspecified,
    override val surfaceBrandTertiaryLight: Color = Color.Unspecified,
    override val surfaceInverseHighDark: Color = WireframeColorRawTokens.colorFunctionalGrayLight160,
    override val surfaceInverseHighLight: Color = WireframeColorRawTokens.colorFunctionalGrayDark720,
    override val surfaceInverseLowDark: Color = WireframeColorRawTokens.colorOpacityWhite120,
    override val surfaceInverseLowLight: Color = WireframeColorRawTokens.colorFunctionalGrayDark720,
    override val surfacePrimaryDark: Color = WireframeColorRawTokens.colorOpacityWhite40,
    override val surfacePrimaryLight: Color = OudsColorRawTokens.colorFunctionalWhite,
    override val surfaceSecondaryDark: Color = WireframeColorRawTokens.colorOpacityWhite80,
    override val surfaceSecondaryLight: Color = WireframeColorRawTokens.colorOpacityBlack40,
    override val surfaceStatusAccentEmphasizedDark: Color = WireframeColorRawTokens.colorRustyRed300,
    override val surfaceStatusAccentEmphasizedLight: Color = WireframeColorRawTokens.colorRustyRed600,
    override val surfaceStatusAccentMutedDark: Color = WireframeColorRawTokens.colorOpacityRustyRed680,
    override val surfaceStatusAccentMutedLight: Color = WireframeColorRawTokens.colorOpacityRustyRed80,
    override val surfaceStatusInfoEmphasizedDark: Color = OudsColorRawTokens.colorFunctionalDodgerBlue300,
    override val surfaceStatusInfoEmphasizedLight: Color = OudsColorRawTokens.colorFunctionalDodgerBlue700,
    override val surfaceStatusInfoMutedDark: Color = OudsColorRawTokens.colorOpacityDodgerBlue520,
    override val surfaceStatusInfoMutedLight: Color = OudsColorRawTokens.colorOpacityDodgerBlue80,
    override val surfaceStatusNegativeEmphasizedDark: Color = OudsColorRawTokens.colorFunctionalScarlet300,
    override val surfaceStatusNegativeEmphasizedLight: Color = OudsColorRawTokens.colorFunctionalScarlet600,
    override val surfaceStatusNegativeMutedDark: Color = OudsColorRawTokens.colorOpacityScarlet320,
    override val surfaceStatusNegativeMutedLight: Color = OudsColorRawTokens.colorOpacityScarlet80,
    override val surfaceStatusPositiveEmphasizedDark: Color = OudsColorRawTokens.colorFunctionalMalachite300,
    override val surfaceStatusPositiveEmphasizedLight: Color = OudsColorRawTokens.colorFunctionalMalachite750,
    override val surfaceStatusPositiveMutedDark: Color = OudsColorRawTokens.colorOpacityMalachite640,
    override val surfaceStatusPositiveMutedLight: Color = OudsColorRawTokens.colorOpacityMalachite120,
    override val surfaceStatusWarningEmphasizedDark: Color = OudsColorRawTokens.colorFunctionalSun300,
    override val surfaceStatusWarningEmphasizedLight: Color = OudsColorRawTokens.colorFunctionalSun500,
    override val surfaceStatusWarningMutedDark: Color = OudsColorRawTokens.colorOpacitySun480,
    override val surfaceStatusWarningMutedLight: Color = OudsColorRawTokens.colorOpacitySun160,
    override val surfaceTertiaryDark: Color = WireframeColorRawTokens.colorOpacityRustyRed680,
    override val surfaceTertiaryLight: Color = WireframeColorRawTokens.colorOpacityRustyRed80
) : OudsColorSurfaceSemanticTokens
