//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Wireframe brand tokens version 2.2.0
// Generated by Tokenator

package com.orange.ouds.theme.wireframe.tokens.semantic

import com.orange.ouds.theme.tokens.semantic.OudsFontSemanticTokens
import com.orange.ouds.tokens.raw.OudsFontRawTokens

data class WireframeFontSemanticTokens(
    override val letterSpacingBodyLargeMobile: Float = OudsFontRawTokens.fontLetterSpacing250,
    override val letterSpacingBodyLargeTablet: Float = OudsFontRawTokens.fontLetterSpacing250,
    override val letterSpacingBodyMediumMobile: Float = OudsFontRawTokens.fontLetterSpacing200,
    override val letterSpacingBodyMediumTablet: Float = OudsFontRawTokens.fontLetterSpacing200,
    override val letterSpacingBodySmallMobile: Float = OudsFontRawTokens.fontLetterSpacing150,
    override val letterSpacingBodySmallTablet: Float = OudsFontRawTokens.fontLetterSpacing150,
    override val letterSpacingDisplayLargeMobile: Float = OudsFontRawTokens.fontLetterSpacing850,
    override val letterSpacingDisplayLargeTablet: Float = OudsFontRawTokens.fontLetterSpacing1450,
    override val letterSpacingDisplayMediumMobile: Float = OudsFontRawTokens.fontLetterSpacing750,
    override val letterSpacingDisplayMediumTablet: Float = OudsFontRawTokens.fontLetterSpacing1050,
    override val letterSpacingDisplaySmallMobile: Float = OudsFontRawTokens.fontLetterSpacing650,
    override val letterSpacingDisplaySmallTablet: Float = OudsFontRawTokens.fontLetterSpacing850,
    override val letterSpacingHeadingLargeMobile: Float = OudsFontRawTokens.fontLetterSpacing450,
    override val letterSpacingHeadingLargeTablet: Float = OudsFontRawTokens.fontLetterSpacing550,
    override val letterSpacingHeadingMediumMobile: Float = OudsFontRawTokens.fontLetterSpacing350,
    override val letterSpacingHeadingMediumTablet: Float = OudsFontRawTokens.fontLetterSpacing450,
    override val letterSpacingHeadingSmallMobile: Float = OudsFontRawTokens.fontLetterSpacing300,
    override val letterSpacingHeadingSmallTablet: Float = OudsFontRawTokens.fontLetterSpacing350,
    override val letterSpacingHeadingXlargeMobile: Float = OudsFontRawTokens.fontLetterSpacing550,
    override val letterSpacingHeadingXlargeTablet: Float = OudsFontRawTokens.fontLetterSpacing750,
    override val letterSpacingLabelLarge: Float = OudsFontRawTokens.fontLetterSpacing250,
    override val letterSpacingLabelMedium: Float = OudsFontRawTokens.fontLetterSpacing200,
    override val letterSpacingLabelSmall: Float = OudsFontRawTokens.fontLetterSpacing150,
    override val letterSpacingLabelXlarge: Float = OudsFontRawTokens.fontLetterSpacing300,
    override val lineHeightBodyLargeMobile: Int = OudsFontRawTokens.fontLineHeight450,
    override val lineHeightBodyLargeTablet: Int = OudsFontRawTokens.fontLineHeight450,
    override val lineHeightBodyMediumMobile: Int = OudsFontRawTokens.fontLineHeight350,
    override val lineHeightBodyMediumTablet: Int = OudsFontRawTokens.fontLineHeight350,
    override val lineHeightBodySmallMobile: Int = OudsFontRawTokens.fontLineHeight250,
    override val lineHeightBodySmallTablet: Int = OudsFontRawTokens.fontLineHeight250,
    override val lineHeightDisplayLargeMobile: Int = OudsFontRawTokens.fontLineHeight1050,
    override val lineHeightDisplayLargeTablet: Int = OudsFontRawTokens.fontLineHeight1850,
    override val lineHeightDisplayMediumMobile: Int = OudsFontRawTokens.fontLineHeight950,
    override val lineHeightDisplayMediumTablet: Int = OudsFontRawTokens.fontLineHeight1250,
    override val lineHeightDisplaySmallMobile: Int = OudsFontRawTokens.fontLineHeight850,
    override val lineHeightDisplaySmallTablet: Int = OudsFontRawTokens.fontLineHeight1050,
    override val lineHeightHeadingLargeMobile: Int = OudsFontRawTokens.fontLineHeight650,
    override val lineHeightHeadingLargeTablet: Int = OudsFontRawTokens.fontLineHeight750,
    override val lineHeightHeadingMediumMobile: Int = OudsFontRawTokens.fontLineHeight550,
    override val lineHeightHeadingMediumTablet: Int = OudsFontRawTokens.fontLineHeight650,
    override val lineHeightHeadingSmallMobile: Int = OudsFontRawTokens.fontLineHeight450,
    override val lineHeightHeadingSmallTablet: Int = OudsFontRawTokens.fontLineHeight550,
    override val lineHeightHeadingXlargeMobile: Int = OudsFontRawTokens.fontLineHeight750,
    override val lineHeightHeadingXlargeTablet: Int = OudsFontRawTokens.fontLineHeight950,
    override val lineHeightLabelLarge: Int = OudsFontRawTokens.fontLineHeight450,
    override val lineHeightLabelMedium: Int = OudsFontRawTokens.fontLineHeight350,
    override val lineHeightLabelSmall: Int = OudsFontRawTokens.fontLineHeight250,
    override val lineHeightLabelXlarge: Int = OudsFontRawTokens.fontLineHeight450,
    override val sizeBodyLargeMobile: Int = OudsFontRawTokens.fontSize250,
    override val sizeBodyLargeTablet: Int = OudsFontRawTokens.fontSize250,
    override val sizeBodyMediumMobile: Int = OudsFontRawTokens.fontSize200,
    override val sizeBodyMediumTablet: Int = OudsFontRawTokens.fontSize200,
    override val sizeBodySmallMobile: Int = OudsFontRawTokens.fontSize150,
    override val sizeBodySmallTablet: Int = OudsFontRawTokens.fontSize150,
    override val sizeDisplayLargeMobile: Int = OudsFontRawTokens.fontSize850,
    override val sizeDisplayLargeTablet: Int = OudsFontRawTokens.fontSize1450,
    override val sizeDisplayMediumMobile: Int = OudsFontRawTokens.fontSize750,
    override val sizeDisplayMediumTablet: Int = OudsFontRawTokens.fontSize1050,
    override val sizeDisplaySmallMobile: Int = OudsFontRawTokens.fontSize650,
    override val sizeDisplaySmallTablet: Int = OudsFontRawTokens.fontSize850,
    override val sizeHeadingLargeMobile: Int = OudsFontRawTokens.fontSize450,
    override val sizeHeadingLargeTablet: Int = OudsFontRawTokens.fontSize550,
    override val sizeHeadingMediumMobile: Int = OudsFontRawTokens.fontSize350,
    override val sizeHeadingMediumTablet: Int = OudsFontRawTokens.fontSize450,
    override val sizeHeadingSmallMobile: Int = OudsFontRawTokens.fontSize300,
    override val sizeHeadingSmallTablet: Int = OudsFontRawTokens.fontSize350,
    override val sizeHeadingXlargeMobile: Int = OudsFontRawTokens.fontSize550,
    override val sizeHeadingXlargeTablet: Int = OudsFontRawTokens.fontSize750,
    override val sizeLabelLarge: Int = OudsFontRawTokens.fontSize250,
    override val sizeLabelMedium: Int = OudsFontRawTokens.fontSize200,
    override val sizeLabelSmall: Int = OudsFontRawTokens.fontSize150,
    override val sizeLabelXlarge: Int = OudsFontRawTokens.fontSize300,
    override val weightBodyDefault: Int = OudsFontRawTokens.fontWeight400,
    override val weightBodyModerate: Int = OudsFontRawTokens.fontWeight500,
    override val weightBodyStrong: Int = OudsFontRawTokens.fontWeight700,
    override val weightDisplay: Int = OudsFontRawTokens.fontWeight700,
    override val weightHeading: Int = OudsFontRawTokens.fontWeight700,
    override val weightLabelDefault: Int = OudsFontRawTokens.fontWeight400,
    override val weightLabelModerate: Int = OudsFontRawTokens.fontWeight500,
    override val weightLabelStrong: Int = OudsFontRawTokens.fontWeight700,
    override val weightSystemDefault: Int = OudsFontRawTokens.fontWeight400,
    override val weightSystemModerate: Int = OudsFontRawTokens.fontWeight500,
    override val weightSystemStrong: Int = OudsFontRawTokens.fontWeight700
) : OudsFontSemanticTokens
