name: app-distribution-alpha

on:
  workflow_dispatch:

jobs:
  app-distribution-alpha:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up our JDK environment
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up signing configuration
        uses: ./.github/actions/setup-signing
        with:
          keystore: ${{ secrets.SIGNING_KEYSTORE }}
          store-password: ${{ secrets.SIGNING_STORE_PASSWORD }}
          key-alias: ${{ secrets.SIGNING_KEY_ALIAS }}
          key-password: ${{ secrets.SIGNING_KEY_PASSWORD }}

      - name: Decode Google service account
        shell: bash
        run: |
          GOOGLE_SERVICE_ACCOUNT_FILE_PATH=${RUNNER_TEMP}/google-service-account.json
          echo "GOOGLE_SERVICE_ACCOUNT_FILE_PATH=${GOOGLE_SERVICE_ACCOUNT_FILE_PATH}" >> $GITHUB_ENV
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT }}" | base64 -d > ${GOOGLE_SERVICE_ACCOUNT_FILE_PATH}

      - name: Upload APK to Firebase App Distribution
        uses: ./.github/actions/app-distribution
        with:
          append-git-sha-to-version-name: 'true'
          variant: 'alphaRelease'
          firebase-token: ${{ secrets.FIREBASE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          group: 'ouds-android-alpha'

      - name: Publish Firebase App Distribution QR code
        run: ./gradlew publishAppDistributionQrCode -Pvariant=alphaRelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
