name: app-distribution-beta

on:
  schedule:
    - cron: '31 3 * * MON-FRI'
  workflow_dispatch:

permissions: read-all

jobs:
  app-distribution-beta:
    runs-on: ubuntu-latest
    if: github.repository == 'Orange-OpenSource/ouds-android'
    permissions:
      contents: write # Required to create tag on repository
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Set up our JDK environment
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}

      - name: Set up signing configuration
        uses: ./.github/actions/setup-signing
        with:
          keystore: ${{ secrets.SIGNING_KEYSTORE }}
          store-password: ${{ secrets.SIGNING_STORE_PASSWORD }}
          key-alias: ${{ secrets.SIGNING_KEY_ALIAS }}
          key-password: ${{ secrets.SIGNING_KEY_PASSWORD }}

      - name: Upload APK to Firebase App Distribution
        uses: ./.github/actions/app-distribution
        with:
          append-git-sha-to-version-name: 'true'
          variant: 'betaRelease'
          firebase-token: ${{ secrets.FIREBASE_TOKEN }}
          git-tag-prefix: 'ci/beta-app'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          group: 'ouds-android-beta'
