name: app-distribution-daily

on:
  schedule:
    - cron: '31 7 * * MON-FRI'
  workflow_dispatch:

jobs:
  app-distribution-daily:
    runs-on: ubuntu-latest
    if: github.repository == 'Orange-OpenSource/ouds-android'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up our JDK environment
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up signing configuration
        uses: ./.github/actions/setup-signing
        with:
          keystore: ${{ secrets.SIGNING_KEYSTORE }}
          store-password: ${{ secrets.SIGNING_STORE_PASSWORD }}
          key-alias: ${{ secrets.SIGNING_KEY_ALIAS }}
          key-password: ${{ secrets.SIGNING_KEY_PASSWORD }}

      - name: Decode Google service account
        shell: bash
        run: |
          GOOGLE_SERVICE_ACCOUNT_FILE_PATH=${RUNNER_TEMP}/google-service-account.json
          echo "GOOGLE_SERVICE_ACCOUNT_FILE_PATH=${GOOGLE_SERVICE_ACCOUNT_FILE_PATH}" >> $GITHUB_ENV
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT }}" | base64 -d > ${GOOGLE_SERVICE_ACCOUNT_FILE_PATH}

      - name: Upload APK to Firebase App Distribution
        uses: ./.github/actions/app-distribution
        with:
          append-git-sha-to-version-name: 'true'
          application-id: 'com.orange.ouds.test.app'
          firebase-token: ${{ secrets.FIREBASE_TOKEN }}
          git-tag-prefix: 'ci/daily-app'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          group: 'ouds-android-test'

      - name: Publish Firebase App Distribution QR code
        run: ./gradlew publishAppDistributionQrCode
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
