name: app-distribution-beta

on:
  schedule:
    - cron: '31 3 * * MON-FRI'
  workflow_dispatch:

permissions: read-all

jobs:
  app-distribution-beta:
    runs-on: ubuntu-latest
    if: github.repository == 'Orange-OpenSource/ouds-android'
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Set up our JDK environment
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0

      - name: Set up signing configuration
        uses: ./.github/actions/setup-signing
        with:
          keystore: ${{ secrets.SIGNING_KEYSTORE }}
          store-password: ${{ secrets.SIGNING_STORE_PASSWORD }}
          key-alias: ${{ secrets.SIGNING_KEY_ALIAS }}
          key-password: ${{ secrets.SIGNING_KEY_PASSWORD }}

      - name: Upload APK to Firebase App Distribution
        uses: ./.github/actions/app-distribution
        with:
          append-git-sha-to-version-name: 'true'
          variant: 'betaRelease'
          firebase-token: ${{ secrets.FIREBASE_TOKEN }}
          git-tag-prefix: 'ci/beta-app'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          group: 'ouds-android-beta'
