//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Wireframe brand tokens version 2.3.0
// Generated by Tokenator

package com.orange.ouds.theme.wireframe.tokens.components

import com.orange.ouds.theme.tokens.OudsSpaceKeyToken
import com.orange.ouds.theme.tokens.components.OudsPinCodeInputTokens
import com.orange.ouds.tokens.raw.OudsDimensionRawTokens

internal data class WireframePinCodeInputTokens(
    override val sizeMaxWidth: Float = OudsDimensionRawTokens.Dimension700,
    override val sizeMinWidth: Float = OudsDimensionRawTokens.Dimension550,
    override val spaceColumnGapDigitInput: OudsSpaceKeyToken.ColumnGap = OudsSpaceKeyToken.ColumnGap.Medium
) : OudsPinCodeInputTokens
