//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Wireframe brand tokens version 2.3.0
// Generated by Tokenator

package com.orange.ouds.theme.wireframe.tokens.components

import androidx.compose.ui.graphics.Color
import com.orange.ouds.theme.tokens.components.OudsBarTokens
import com.orange.ouds.theme.tokens.components.OudsLightDarkColor
import com.orange.ouds.theme.tokens.OudsBorderKeyToken
import com.orange.ouds.theme.tokens.OudsColorKeyToken
import com.orange.ouds.theme.tokens.OudsOpacityKeyToken
import com.orange.ouds.tokens.raw.DimensionRawTokens
import com.orange.ouds.tokens.raw.EffectRawTokens

data class WireframeBarTokens(
    override val borderRadiusActiveIndicatorCustomBottom: OudsBorderKeyToken.Radius = OudsBorderKeyToken.Radius.Pill,
    override val borderRadiusActiveIndicatorCustomTop: OudsBorderKeyToken.Radius = OudsBorderKeyToken.Radius.Default,
    override val colorActiveIndicatorAndroidSelectedDisabled: OudsColorKeyToken = OudsColorKeyToken.Action.Support.Disabled,
    override val colorActiveIndicatorAndroidSelectedEnabled: OudsColorKeyToken = OudsColorKeyToken.Action.Support.Enabled,
    override val colorActiveIndicatorAndroidSelectedFocus: OudsColorKeyToken = OudsColorKeyToken.Action.Support.Focus,
    override val colorActiveIndicatorAndroidSelectedHover: OudsColorKeyToken = OudsColorKeyToken.Action.Support.Hover,
    override val colorActiveIndicatorAndroidSelectedPressed: OudsColorKeyToken = OudsColorKeyToken.Action.Support.Pressed,
    override val colorActiveIndicatorAndroidUnselectedDisabled: OudsColorKeyToken = OudsColorKeyToken.Action.Support.Disabled,
    override val colorActiveIndicatorAndroidUnselectedFocus: OudsColorKeyToken = OudsColorKeyToken.Action.Support.Focus,
    override val colorActiveIndicatorAndroidUnselectedHover: OudsColorKeyToken = OudsColorKeyToken.Action.Support.Hover,
    override val colorActiveIndicatorAndroidUnselectedPressed: OudsColorKeyToken = OudsColorKeyToken.Action.Support.Pressed,
    override val colorActiveIndicatorCustomSelectedEnabled: OudsColorKeyToken = OudsColorKeyToken.Action.Selected,
    override val colorActiveIndicatorCustomSelectedFocus: OudsColorKeyToken = OudsColorKeyToken.Action.Focus,
    override val colorActiveIndicatorCustomSelectedHover: OudsColorKeyToken = OudsColorKeyToken.Action.Hover,
    override val colorActiveIndicatorCustomSelectedPressed: OudsColorKeyToken = OudsColorKeyToken.Action.Pressed,
    override val colorBgOpaque: OudsColorKeyToken = OudsColorKeyToken.Background.Secondary,
    override val colorBgTranslucent: OudsLightDarkColor = OudsLightDarkColor(Color(0xccf7f8fa), Color(0xcc181c26)),
    override val colorBorderBadge: OudsColorKeyToken = OudsColorKeyToken.Background.Secondary,
    override val colorContentOnIosAccent: OudsColorKeyToken = OudsColorKeyToken.Content.OnAction.Selected,
    override val colorContentSelectedEnabled: OudsColorKeyToken = OudsColorKeyToken.Action.Selected,
    override val colorContentSelectedFocus: OudsColorKeyToken = OudsColorKeyToken.Action.Focus,
    override val colorContentSelectedHover: OudsColorKeyToken = OudsColorKeyToken.Action.Hover,
    override val colorContentSelectedPressed: OudsColorKeyToken = OudsColorKeyToken.Action.Pressed,
    override val colorContentUnselectedEnabled: OudsLightDarkColor = OudsLightDarkColor(Color(0x99000000), Color(0x99ffffff)),
    override val colorContentUnselectedFocus: OudsColorKeyToken = OudsColorKeyToken.Action.Focus,
    override val colorContentUnselectedHover: OudsColorKeyToken = OudsColorKeyToken.Action.Hover,
    override val colorContentUnselectedPressed: OudsColorKeyToken = OudsColorKeyToken.Action.Pressed,
    override val effectBgBlur: Int = EffectRawTokens.effectBlur160,
    override val opacityActiveIndicatorCustom: OudsOpacityKeyToken = OudsOpacityKeyToken.Invisible,
    override val sizeHeightActiveIndicatorCustom: Float = DimensionRawTokens.dimensionOutOfSystem75,
    override val sizeWidthActiveIndicatorCustomBottom: Float = DimensionRawTokens.dimension300,
    override val sizeWidthActiveIndicatorCustomTop: Float = DimensionRawTokens.dimension650
) : OudsBarTokens
