//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Wireframe brand tokens version 2.4.0
// Generated by Tokenator

package com.orange.ouds.theme.wireframe.tokens.components

import com.orange.ouds.theme.tokens.OudsBorderKeyToken
import com.orange.ouds.theme.tokens.OudsColorKeyToken
import com.orange.ouds.theme.tokens.OudsOpacityKeyToken
import com.orange.ouds.theme.tokens.OudsSizeKeyToken
import com.orange.ouds.theme.tokens.OudsSpaceKeyToken
import com.orange.ouds.theme.tokens.components.OudsControlItemTokens
import com.orange.ouds.tokens.raw.OudsDimensionRawTokens
import com.orange.ouds.tokens.raw.OudsFontRawTokens

internal data class WireframeControlItemTokens(
    override val borderRadiusCurrentIndicator: OudsBorderKeyToken.Radius = OudsBorderKeyToken.Radius.Default,
    override val borderRadiusDefault: OudsBorderKeyToken.Radius = OudsBorderKeyToken.Radius.Default,
    override val borderRadiusMedia: OudsBorderKeyToken.Radius = OudsBorderKeyToken.Radius.Default,
    override val borderRadiusMediaRoundedCorner: OudsBorderKeyToken.Radius = OudsBorderKeyToken.Radius.Small,
    override val borderRadiusRounded: OudsBorderKeyToken.Radius = OudsBorderKeyToken.Radius.Default,
    override val borderWidthCurrentPage: OudsBorderKeyToken.Width = OudsBorderKeyToken.Width.Medium,
    override val borderWidthDefault: OudsBorderKeyToken.Width = OudsBorderKeyToken.Width.Default,
    override val colorBadgeSafetyArea: OudsColorKeyToken = OudsColorKeyToken.Background.Primary,
    override val colorBgCurrentDisabled: OudsColorKeyToken = OudsColorKeyToken.Action.Disabled,
    override val colorBgCurrentEnabled: OudsColorKeyToken = OudsColorKeyToken.Action.Selected,
    override val colorBgCurrentFocus: OudsColorKeyToken = OudsColorKeyToken.Action.Focus,
    override val colorBgCurrentHover: OudsColorKeyToken = OudsColorKeyToken.Action.Hover,
    override val colorBgCurrentPressed: OudsColorKeyToken = OudsColorKeyToken.Action.Pressed,
    override val colorContentCurrentDisabled: OudsColorKeyToken = OudsColorKeyToken.Content.OnAction.Disabled,
    override val colorContentCurrentEnabled: OudsColorKeyToken = OudsColorKeyToken.Content.OnAction.Selected,
    override val colorContentCurrentFocus: OudsColorKeyToken = OudsColorKeyToken.Content.OnAction.Focus,
    override val colorContentCurrentHover: OudsColorKeyToken = OudsColorKeyToken.Content.OnAction.Hover,
    override val colorContentCurrentPressed: OudsColorKeyToken = OudsColorKeyToken.Content.OnAction.Pressed,
    override val fontLetterSpacingAvatarInitialXlarge: Float = OudsFontRawTokens.FontLetterSpacing450,
    override val fontLineHeightAvatarInitialXlarge: Int = OudsFontRawTokens.FontLineHeight650,
    override val fontSizeAvatarInitialXlarge: Int = OudsFontRawTokens.FontSize450,
    override val opacityCurrentDivider: OudsOpacityKeyToken = OudsOpacityKeyToken.Invisible,
    override val opacityCurrentIndicator: OudsOpacityKeyToken = OudsOpacityKeyToken.Invisible,
    override val sizeAssetLarge: Float = OudsDimensionRawTokens.Dimension500,
    override val sizeAssetMedium: OudsSizeKeyToken.Icon = OudsSizeKeyToken.Icon.WithLabel.Large.SizeMedium,
    override val sizeAssetSmall: OudsSizeKeyToken.Icon = OudsSizeKeyToken.Icon.WithLabel.Large.SizeSmall,
    override val sizeAssetXlarge: Float = OudsDimensionRawTokens.Dimension700,
    override val sizeControlIndicator: OudsSizeKeyToken.Icon = OudsSizeKeyToken.Icon.WithLabel.Large.SizeExtraSmall,
    override val sizeCurrentIndicatorWidth: Float = OudsDimensionRawTokens.Dimension50,
    override val sizeFlagHeight: OudsSizeKeyToken.Icon = OudsSizeKeyToken.Icon.WithLabel.Large.SizeExtraSmall,
    override val sizeMaxWidth: Float = OudsDimensionRawTokens.Dimension4000,
    override val sizeMinHeightCompact: OudsSizeKeyToken = OudsSizeKeyToken.MinInteractiveArea,
    override val sizeMinHeightDefault: Float = OudsDimensionRawTokens.Dimension750,
    override val sizeMinWidth: Float = OudsDimensionRawTokens.Dimension2000,
    override val spaceColumnGap: OudsSpaceKeyToken.ColumnGap = OudsSpaceKeyToken.ColumnGap.Medium,
    override val spacePaddingBlockBottomSlot: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.ThreeExtraSmall,
    override val spacePaddingBlockDensityCompact: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.ExtraSmall,
    override val spacePaddingBlockDensityCompactBottomExpandContainer: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.TwoExtraLarge,
    override val spacePaddingBlockDensityCompactTopAlignmentTopCounterweight: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.ExtraSmall,
    override val spacePaddingBlockDensityCompactTopAlignmentTopTextContainer: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.None,
    override val spacePaddingBlockDensityDefault: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.Medium,
    override val spacePaddingBlockDensityDefaultBottomExpandContainer: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.ThreeExtraLarge,
    override val spacePaddingBlockDensityDefaultTopAlignmentTopCounterweight: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.Small,
    override val spacePaddingBlockDensityDefaultTopAlignmentTopTextContainer: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.FourExtraSmall,
    override val spacePaddingBlockTopHelperText: OudsSpaceKeyToken.PaddingBlock = OudsSpaceKeyToken.PaddingBlock.ExtraSmall,
    override val spacePaddingInline: OudsSpaceKeyToken.PaddingInline = OudsSpaceKeyToken.PaddingInline.Large,
    override val spaceRowGap: OudsSpaceKeyToken.RowGap = OudsSpaceKeyToken.RowGap.None
) : OudsControlItemTokens
