//
// Software Name: OUDS Android
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Software description: Android library of reusable graphical components
//

// Wireframe brand tokens version 2.0.1
// Generated by Tokenator

package com.orange.ouds.theme.wireframe.tokens.components

import com.orange.ouds.theme.tokens.components.OudsIconTokens
import com.orange.ouds.theme.tokens.OudsColorKeyToken
import com.orange.ouds.theme.tokens.OudsLightDarkColorKeyToken

data class WireframeIconTokens(
    override val colorContentStatusWarningExternalShape: OudsColorKeyToken = OudsLightDarkColorKeyToken(OudsColorKeyToken.Repository.Warning.Default, OudsColorKeyToken.Repository.Warning.Low),
    override val colorContentStatusWarningInternalShape: OudsColorKeyToken = OudsLightDarkColorKeyToken(OudsColorKeyToken.Repository.Warning.High, OudsColorKeyToken.Opacity.Transparent)
) : OudsIconTokens
